const RESOURCE_URLS={horn:'/assets/ashyk/audio/smaller-horn-dropped-on-stone-floor.mp3',clack:'/assets/ashyk/audio/clack.mp3',wood:'/assets/ashyk/audio/wood-hard-hit.wav'};
const PROFILES={ashyk:{threshold:.035,fullScale:5.8,cooldownMs:30,gain:.98},board:{threshold:.045,fullScale:7.2,cooldownMs:34,gain:.84},rim:{threshold:.06,fullScale:8.2,cooldownMs:38,gain:.88}};
const SEGMENTS={
 ashyk:{weak:[['horn',0,.18,.86,1],['horn',.18,.2,.9,1.04],['clack',0,.18,.56,1.08]],medium:[['horn',.05,.32,.94,1],['horn',.25,.34,.96,.96],['clack',.04,.29,.74,.99]],strong:[['horn',0,.43,1,1],['horn',.2,.44,1,.96],['wood',0,.4,.86,.95]]},
 board:{weak:[['horn',.30,.26,.62,1.06],['horn',.42,.24,.62,1.03]],medium:[['horn',.10,.34,.74,.96],['horn',.28,.34,.72,.96]],strong:[['wood',0,.4,.88,1],['wood',0,.4,.82,.95]]},
 rim:{weak:[['clack',0,.2,.5,1.02],['horn',.38,.27,.58,1.03]],medium:[['horn',.18,.36,.75,.96],['clack',.04,.31,.68,.94]],strong:[['wood',0,.4,.96,.93],['wood',0,.4,.9,.89]]}
};
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
function band(kind,strength){const p=PROFILES[kind],n=clamp((strength-p.threshold)/Math.max(.001,p.fullScale-p.threshold),0,1);return n<.28?'weak':n<.67?'medium':'strong';}
export function createWebAshykAudio(){let context=null,master=null,samples={},loading=null,disposed=false,flushPending=()=>{};const lastImpact=new Map(),lastRoll=new Map(),pendingImpacts=[];
 const ensure=()=>{if(disposed)return null;if(context)return context;const C=globalThis.AudioContext||globalThis.webkitAudioContext;if(!C)return null;context=new C();master=context.createGain();master.gain.value=.9;master.connect(context.destination);return context;};
 const load=()=>{const ctx=ensure();if(!ctx||loading)return;loading=Promise.all(Object.entries(RESOURCE_URLS).map(async([name,url])=>{try{const response=await fetch(url);if(!response.ok)return;samples[name]=await ctx.decodeAudioData((await response.arrayBuffer()).slice(0));}catch{}})).then(()=>undefined);};
 flushPending=()=>{const ctx=context;if(!ctx||ctx.state!=='running'||!pendingImpacts.length)return;const time=performance.now(),rows=pendingImpacts.splice(0);for(const row of rows)if(time-row.time<900)play(row.kind,row.strength,row.key,row.pan);};
 const preload=()=>{ensure();load();};
 const unlock=()=>{const ctx=ensure();if(!ctx)return;load();if(ctx.state==='suspended')void ctx.resume().then(flushPending).catch(()=>{});else flushPending();};
 const play=(kind,strength,key,pan=0)=>{const p=PROFILES[kind];if(!p||strength<p.threshold)return;const ctx=ensure();if(!ctx||!master)return;load();const time=performance.now(),previous=lastImpact.get(key)??-Infinity;if(time-previous<p.cooldownMs)return;const list=SEGMENTS[kind][band(kind,strength)].filter(([name])=>samples[name]);if(ctx.state!=='running'||!list.length){pendingImpacts.push({kind,strength,key,pan,time});if(pendingImpacts.length>16)pendingImpacts.shift();return;}lastImpact.set(key,time);const [name,start,duration,segmentGain,rate]=list[Math.floor(Math.random()*list.length)],buffer=samples[name];if(!buffer)return;const source=ctx.createBufferSource(),gain=ctx.createGain(),panner=ctx.createStereoPanner(),normalized=clamp(Math.pow(Math.max(0,strength-p.threshold)/p.fullScale,.54),0,1);source.buffer=buffer;source.playbackRate.value=clamp(rate*(1+(Math.random()-.5)*.045),.84,1.14);gain.gain.value=clamp((.2+normalized*.8)*p.gain*segmentGain,0,1.15);panner.pan.value=clamp(pan,-.82,.82);source.connect(gain);gain.connect(panner);panner.connect(master);const offset=clamp(start,0,Math.max(0,buffer.duration-.015)),length=Math.min(duration,Math.max(.02,buffer.duration-offset));source.start(ctx.currentTime,offset,length);source.stop(ctx.currentTime+length/source.playbackRate.value+.035);};
 const click=()=>{const ctx=ensure();if(!ctx||ctx.state!=='running'||!master)return;load();const buffer=samples.clack;if(!buffer)return;const now=performance.now(),previous=lastImpact.get('ui')??-Infinity;if(now-previous<38)return;lastImpact.set('ui',now);const source=ctx.createBufferSource(),gain=ctx.createGain();source.buffer=buffer;source.playbackRate.value=1.08+Math.random()*.035;gain.gain.value=.22;source.connect(gain);gain.connect(master);const length=Math.min(.09,Math.max(.02,buffer.duration));source.start(ctx.currentTime,0,length);source.stop(ctx.currentTime+length/source.playbackRate.value+.02);};
 const rolling=(key,linearSpeed,angularSpeed,grounded,pan=0)=>{if(!grounded||(linearSpeed<.09&&angularSpeed<.85))return;const ctx=ensure();if(!ctx||ctx.state!=='running'||!master)return;load();const buffer=samples.horn;if(!buffer)return;const motion=Math.max(0,linearSpeed*.82+Math.min(angularSpeed,14)*.055);if(motion<.18)return;const now=performance.now(),cooldown=clamp(172-motion*22,52,155),previous=lastRoll.get(key)??-Infinity;if(now-previous<cooldown)return;lastRoll.set(key,now);const starts=[.08,.28,.48],start=clamp(starts[Math.floor(Math.random()*starts.length)],0,Math.max(0,buffer.duration-.04)),duration=Math.min(.1+Math.min(motion,4)*.012,Math.max(.025,buffer.duration-start)),source=ctx.createBufferSource(),gain=ctx.createGain(),panner=ctx.createStereoPanner();source.buffer=buffer;source.playbackRate.value=clamp(.92+Math.min(motion,5)*.035+(Math.random()-.5)*.035,.9,1.12);gain.gain.value=clamp(.1+motion*.055,.1,.34);panner.pan.value=clamp(pan,-.82,.82);source.connect(gain);gain.connect(panner);panner.connect(master);source.start(ctx.currentTime,start,duration);source.stop(ctx.currentTime+duration/source.playbackRate.value+.025);};
 const dispose=()=>{disposed=true;lastImpact.clear();lastRoll.clear();pendingImpacts.length=0;samples={};if(context&&context.state!=='closed')void context.close();context=null;master=null;loading=null;};
 return{preload,unlock,playImpact:play,playUiClick:click,updateRolling:rolling,dispose};}
