import React,{useEffect,useMemo,useRef,useState} from 'react';
import {socialMessage} from '../../alantil-core/social-i18n.js';
import {ashykAccessForUser} from '../../alantil-core/ashyk-access.js';
import {createAshykEngine} from '../engine.js';
import {createAshykGameStore} from '../store.js';
import {createAshykOnlineAdapter} from '../online.js';
import {createAshykOnlineSessionController} from '../session.js';
import {DIFFICULTIES,DIFFICULTY_ORDER} from '../constants.js';
import {ashykMessages,difficultyLabel} from '../i18n.js';
import {faceValue} from '../faces.js';
import {SHOT_ICON_PATHS,SHOT_ICON_VIEWBOX} from '../shot-icons.js';
import {AshykWebScene} from './scene.jsx';
import {createWebAshykAudio} from './audio.js';

const FACE_HELP=Object.freeze([['chyk','faceChyk',1],['fok','faceFok',2],['tau','faceTau',3],['alchi','faceAlchi',4],['biy','faceBiy',15],['kyt','faceKyt',6]]);

function useStore(store){const[state,setState]=useState(()=>store.getState());useEffect(()=>store.subscribe(setState),[store]);return state;}
function Segmented({value,items,onChange,disabled=false,label}){return <div className="settingsSegments ashykSegmented" role="radiogroup" aria-label={label}>{items.map(([id,text])=><label className="settingsChoice" key={id}><input type="radio" name={`ashyk-${label||'choice'}`} value={id} checked={value===id} disabled={disabled} onChange={()=>onChange(id)}/><span>{text}</span></label>)}</div>;}
function PlayerName({player,state,m,locale}){if(state.gameMode==='computer')return player===1?m.you:m.computerPlayer;if(state.gameMode==='local')return socialMessage(locale,player===1?'player1':'player2');return player===state.localPlayer?m.you:m.opponent;}
function outcomeText(outcome,m){if(!outcome)return'';if(outcome.code==='miss')return`${m.miss} · −1`;if(outcome.code==='faceMismatch')return`${m.faceMismatch} · 0`;if(outcome.code==='thirdTouched')return`${m.thirdTouched} · 0`;if(outcome.code==='correct')return`${m.correct} · +3`;if(outcome.code==='wrong')return`${m.wrong} · −1`;if(outcome.code==='timeout')return`${m.timeout} · ${m.noPenalty}`;if(outcome.code==='noPenalty')return m.noPenalty;if(outcome.code==='opponentResigned')return m.opponentResigned;if(outcome.code==='resigned')return m.resigned;if(outcome.code==='opponentDisconnected')return m.opponentDisconnected;if(outcome.code==='questionPoolError')return m.questionPoolError;if(outcome.code==='capture')return outcome.instant?`КЪЫТ × КЪЫТ · ${m.instantWin}`:`${outcome.face||m.capture} · +${outcome.delta||0}`;return outcome.code;}

function ShotIcon({kind,size=22}){const icon=SHOT_ICON_PATHS[kind];return <svg className="ashykShotSvg" width={size} height={size} viewBox={SHOT_ICON_VIEWBOX} aria-hidden="true" fill="none" stroke="currentColor" strokeWidth="1.7" strokeLinecap="round" strokeLinejoin="round">{icon?.circles?.map((circle,index)=><circle key={`c${index}`} {...circle} opacity={index?0.42:1}/>)||null}{icon?.paths?.map((d,index)=><path key={`p${index}`} d={d} strokeDasharray={(kind==='flat'||kind==='hop')&&index===0?'2.2 2.3':undefined}/>)||null}</svg>;}
function DialogShell({open,onClose,title,children,className=''}){if(!open)return null;return <div className="ashykDialogBackdrop" role="presentation" onMouseDown={(event)=>{if(event.target===event.currentTarget)onClose();}}><section className={`ashykDialog ${className}`} role="dialog" aria-modal="true"><header><h2>{title}</h2><button className="ashykCircleButton" type="button" aria-label="Close" onClick={onClose}>×</button></header>{children}</section></div>;}

function Setup({state,store,m,locale,userId,online,engine,audio,friends,onInvite}){const config=DIFFICULTIES[state.selectedDifficulty],[busy,setBusy]=useState(false),[error,setError]=useState(''),sm=(key,params)=>socialMessage(locale,key,params);
 const invite=async(friend)=>{if(!online||!userId||busy||!friend?.user_id)return;audio.playUiClick();setBusy(true);setError('');try{const field=engine.isReady()?engine.snapshot():engine.settleInitial(),initial={field,scores:[0,0],currentPlayer:1,remainingAshyks:engine.getAliveCount(),winner:null,winByKyt:false,difficulty:state.selectedDifficulty},result=await online.createFriendInvite(friend.user_id,initial);onInvite(result,friend);}catch(e){setError(String(e?.message||m.roomError));}finally{setBusy(false);}};
 const click=(fn)=>(value)=>{audio.playUiClick();fn(value);setError('');};
 const modes=ashykAccessForUser(userId).modes.map((id)=>[id,id==='computer'?sm('computer'):id==='local'?sm('local'):sm('friend')]);
 return <div className="ashykSetupScroll"><section className="ashykSetup" aria-labelledby="ashyk-setup-title"><div className="ashykPageHead"><span className="ashykEyebrow">{m.title}</span><h1 id="ashyk-setup-title">{m.newGame}</h1></div><div className="ashykSetupSection"><div className="ashykSectionLabel">{m.modeLabel}</div><Segmented value={state.gameMode} label={m.modeLabel} items={modes} onChange={click(store.setMode)}/></div><div className="ashykSetupSection"><div className="ashykSectionLabel">{m.difficultyLabel}</div><Segmented value={state.selectedDifficulty} label={m.difficultyLabel} items={DIFFICULTY_ORDER.map((id)=>[id,difficultyLabel(id,locale)])} onChange={click(store.setDifficulty)}/></div><div className="ashykFacts"><div><span>{m.shotTime}</span><b>{config.humanShotSeconds} {m.seconds}</b></div><div><span>{m.answerTime}</span><b>{config.humanQuestionSeconds} {m.seconds}</b></div>{state.gameMode==='computer'?<><div><span>{m.computerAccuracy}</span><b>{Math.round(config.computerShotAccuracy*100)}%</b></div><div><span>{m.computerAnswers}</span><b>{Math.round(config.computerAnswerAccuracy*100)}%</b></div></>:null}</div><p className="ashykScopeNote">{m.mediumWords}</p>{!userId?<p className="ashykInlineNotice">{sm('loginForModes')}</p>:null}{state.gameMode==='computer'?<button className="ashykPrimary" type="button" onClick={()=>{audio.playUiClick();store.startComputer(state.selectedDifficulty);}}>{m.start}</button>:state.gameMode==='local'?<button className="ashykPrimary" type="button" onClick={()=>{audio.playUiClick();store.startLocal(state.selectedDifficulty);}}>{m.start}</button>:<div className="ashykOnlineSetup"><div className="ashykSectionLabel">{sm('chooseFriend')}</div>{friends.length?friends.map((friend)=><button className="ashykFriendChoice" type="button" key={friend.user_id} disabled={busy} onClick={()=>void invite(friend)}><span><strong>{friend.nickname||'—'}</strong><small>{sm('score',{score:friend.rating_score||0})}</small></span><b>{sm('challenge')}</b></button>):<p className="ashykInlineNotice">{sm('noFriendsForGame')}</p>}{error?<p className="ashykInlineError" role="alert">{error}</p>:null}</div>}</section></div>;
}

function Help({open,onClose,m,audio}){const close=()=>{audio.playUiClick();onClose();};return <DialogShell open={open} onClose={close} title={m.rules} className="ashykHelp"><div className="ashykHelpSection"><h3>{m.helpGoalTitle}</h3><p>{m.helpGoalText}</p></div><div className="ashykHelpSection"><h3>{m.helpControlsTitle}</h3><p>{m.helpControlsText}</p><div className="ashykHelpControls"><div><span className="ashykHelpIcon"><ShotIcon kind="tap"/></span><p><b>{m.tapAction}</b><small>{m.tapActionHelp}</small></p></div><div><span className="ashykHelpIcon"><ShotIcon kind="flat"/></span><p><b>{m.flatAction}</b><small>{m.flatActionHelp}</small></p></div><div><span className="ashykHelpIcon"><ShotIcon kind="hop"/></span><p><b>{m.hopAction}</b><small>{m.hopActionHelp}</small></p></div></div></div><div className="ashykHelpSection"><h3>{m.helpFacesTitle}</h3><p>{m.helpFacesText}</p><div className="ashykFacesGrid">{FACE_HELP.map(([face,key,score])=><div className={face==='kyt'?'ashykFaceRule kyt':'ashykFaceRule'} key={face}><strong>{m[key]}</strong><span>{score} {m.points}</span>{face==='kyt'?<small>{m.instantWin}</small>:null}</div>)}</div></div><div className="ashykHelpSection"><h3>{m.helpQuestionsTitle}</h3><p>{m.helpQuestionsText}</p></div><div className="ashykHelpSection ashykHelpKyt"><h3>{m.helpKytTitle}</h3><p>{m.helpKytText}</p></div><button className="ashykSecondary" type="button" onClick={close}>{m.close}</button></DialogShell>;}
function Menu({open,onClose,onHelp,onAppearance,onEndGame,room,m,audio}){const action=(fn)=>()=>{audio.playUiClick();onClose();fn();},active=room&&['waiting','preparing','playing'].includes(room.status),status=room?.status==='waiting'?m.inviteSent:room?.status==='preparing'?m.preparingGameStatus:m.gameInProgress;return <DialogShell open={open} onClose={onClose} title={m.menu} className="ashykMenu"><div className="ashykMenuActions">{active?<div className="ashykMenuCurrent"><span className="ashykEyebrow">{m.currentGame}</span><strong>{status}</strong><button className="ashykSecondary" type="button" onClick={action(onEndGame)}>{room.status==='playing'?m.resignGame:m.cancelCurrentGame}</button></div>:null}<button className="ashykSecondary" type="button" onClick={action(onHelp)}>{m.help}</button><button className="ashykSecondary" type="button" onClick={action(onAppearance)}>{m.appearance}</button></div></DialogShell>;}
function Appearance({open,onClose,m,cameraMode,setCameraMode,audio}){return <DialogShell open={open} onClose={onClose} title={m.appearance} className="ashykAppearance"><div className="ashykAppearanceRow"><span>{m.cameraLabel}</span><Segmented value={cameraMode} label={m.cameraLabel} items={[["orbit",m.orbit],["top",m.top]]} onChange={(value)=>{audio.playUiClick();setCameraMode(value);}}/></div></DialogShell>;}

function Question({state,store,m,audio,onVisual}){const review=state.questionReview,question=review?.question||state.question,[selectedId,setSelectedId]=useState(null);useEffect(()=>{if(!review)setSelectedId(null);},[question?.id,state.phase,review?.id]);if(!question||(!review&&(state.status!=='playing'||state.phase!=='bonus-question')))return null;const local=store.isLocalTurn()&&!review,computer=store.isComputerTurn()&&!review,remote=state.gameMode==='online'&&!store.isLocalTurn()&&!review,blocked=Boolean(review)||state.questionLocked||computer||remote,visualSelected=String(review?.selectedOptionId||(remote?state.remoteQuestionSelectedId:selectedId)||''),skipLabel=computer?m.computerAnswersNow:remote?m.opponentAnswersNow:m.skip,submit=()=>{if(!selectedId||blocked)return;audio.playUiClick();onVisual?.('question-submit',{optionId:String(selectedId)});store.submitAnswer(selectedId);};return <div className="ashykDialogBackdrop ashykQuestionBackdrop" role="presentation"><section className="ashykQuestionSession" role="dialog" aria-modal="true"><header className="ashykQuestionMeta"><div><span className="ashykEyebrow">{m.bonusQuestion}</span><strong>{m.translate}</strong></div><div className={state.questionSeconds<=3&&local&&!blocked?'ashykTimer danger':'ashykTimer'}>{blocked?'…':state.questionSeconds}</div></header><div className="ashykQuestionMain"><div className="ashykQuestionPrompt">{question.prompt}</div></div><div className="ashykTestOptions">{question.options.map((option)=>{const id=String(option.id),selected=visualSelected===id,wrong=review?.resultCode==='wrong'&&String(review.selectedOptionId)===id,correct=Boolean(review)&&String(review.correctOptionId)===id;return <button key={option.id} type="button" disabled={blocked} aria-pressed={selected} className={`choiceControl optionBtn ashykTestOption${selected?' selected':''}${correct?' correct':''}${wrong?' wrong':''}`} onClick={()=>{audio.playUiClick();setSelectedId(id);onVisual?.('question-select',{optionId:id});}}>{option.text}</button>;})}</div><footer className="ashykQuestionActions"><button className="ashykSecondary ashykQuestionAction" type="button" disabled={blocked} onClick={()=>{audio.playUiClick();onVisual?.('question-skip',{});store.skipQuestion();}}>{skipLabel}</button><button className="ashykPrimary ashykQuestionAction" type="button" disabled={!selectedId||blocked} onClick={submit}>{remote&&state.remoteQuestionSubmitting?m.opponentSubmitted:m.answer}</button></footer><p className="ashykRuleNote ashykQuestionRule">{m.questionRule}</p></section></div>;}
function Finish({state,m,audio,onExit,locale}){if(state.status!=='finished')return null;const sm=(key,params)=>socialMessage(locale,key,params),localName=state.winner===1?sm('player1'):sm('player2'),title=state.winner==='draw'?m.draw:state.gameMode==='local'?sm('playerWon',{name:localName}):state.winner===state.localPlayer?m.youWon:m.youLost;return <div className="ashykDialogBackdrop" role="presentation"><section className="ashykDialog ashykFinish" role="dialog" aria-modal="true"><span className="ashykEyebrow">{m.gameOver}</span><h2>{title}</h2><div className="ashykFinalScore"><strong>{state.scores[0]}</strong><span>:</span><strong>{state.scores[1]}</strong></div>{state.winByKyt?<p className="ashykKytResult">КЪЫТ × КЪЫТ · {m.instantWin}</p>:null}<button className="ashykPrimary" type="button" onClick={()=>{audio.playUiClick();onExit?.();}}>{m.backToPractice}</button></section></div>;}

function Hud({state,store,m,locale,shotMode,setShotMode,onMenu,audio}){const local=store.isLocalTurn(),waiting=state.gameMode==='online'&&['waiting','preparing'].includes(state.onlineRoom?.status),displayShotMode=!local&&state.gameMode==='online'&&state.remoteShotMode?state.remoteShotMode:shotMode,shotDisabled=state.status!=='playing'||!local||!state.ready||state.phase==='bonus-question'||waiting,showStatus=Boolean(state.statusCode&&state.statusCode!=='statusChoosePiece'),pulse=state.scorePulse?.player;return <><div className="ashykScore"><div className={`${state.player===1?'active':''}${pulse===1?' scorePulse':''}`}><span><PlayerName player={1} state={state} m={m} locale={locale}/></span><strong>{state.scores[0]}</strong></div><b>:</b><div className={`${state.player===2?'active':''}${pulse===2?' scorePulse':''}`}><strong>{state.scores[1]}</strong><span><PlayerName player={2} state={state} m={m} locale={locale}/></span></div></div><div className={state.shotSeconds<=5&&local?'ashykTurnTimer danger':'ashykTurnTimer'} aria-label={m.shotTime}>{state.status==='playing'&&local&&state.phase!=='bonus-question'&&!waiting&&state.ready?`${state.shotSeconds} ${m.seconds}`:'—'}</div><button className="ashykMenuButton" type="button" aria-label={m.menu} onClick={()=>{audio.playUiClick();onMenu();}}>•••</button><div className="ashykShotIcons" role="group" aria-label={m.shotType}><span className="ashykShotInfo" aria-label={m.tapAction} title={m.tapAction}><ShotIcon kind="tap" size={20}/></span><button type="button" className={displayShotMode==='flat'?'active':''} disabled={shotDisabled} aria-pressed={displayShotMode==='flat'} aria-label={m.flatAction} title={m.flatAction} onClick={()=>{audio.playUiClick();setShotMode('flat');}}><ShotIcon kind="flat" size={21}/></button><button type="button" className={displayShotMode==='hop'?'active':''} disabled={shotDisabled} aria-pressed={displayShotMode==='hop'} aria-label={m.hopAction} title={m.hopAction} onClick={()=>{audio.playUiClick();setShotMode('hop');}}><ShotIcon kind="hop" size={21}/></button></div>{state.selectedFace?<div className="ashykFace"><span>{m.position}</span><strong>{state.selectedFace}</strong><b>{state.selectedFace==='КЪЫТ'?m.kytWin:`${faceValue(state.selectedFace)}`}</b></div>:null}{showStatus?<div className="ashykStatus"><i className={state.ready?'ready':''}/><strong>{m[state.statusCode]||m.statusChoosePiece}</strong></div>:null}</>;}

export function AshykGame({words=[],locale='ru',supabaseClient=null,userId='',friends=[],initialRoom=null,onSessionActiveChange=null,onRoomChange=null,onExit=null}){
 const m=ashykMessages(locale),sm=(key,params)=>socialMessage(locale,key,params),audioRef=useRef(null),sessionRef=useRef(null),storeRef=useRef(null);
 if(!audioRef.current)audioRef.current=createWebAshykAudio();
 if(!storeRef.current){let store=null;const engine=createAshykEngine({onEvent:(event)=>{if(event.type==='impact')audioRef.current?.playImpact(event.kind,event.strength,event.key,event.pan);if(event.type==='rolling')audioRef.current?.updateRolling(event.key,event.linearSpeed,event.angularSpeed,event.grounded,event.pan);sessionRef.current?.handleEngineEvent(event);store?.handleEngineEvent(event);}});store=createAshykGameStore({engine,words});storeRef.current={engine,store};}
 const {engine,store}=storeRef.current,state=useStore(store),[cameraMode,setCameraMode]=useState('orbit'),[shotMode,setShotMode]=useState('flat'),[help,setHelp]=useState(false),[menu,setMenu]=useState(false),[appearance,setAppearance]=useState(false),[onlineRoom,setOnlineRoom]=useState(null),[waitingFriend,setWaitingFriend]=useState(null),[connection,setConnection]=useState('online'),[visualConnection,setVisualConnection]=useState('offline'),[networkNow,setNetworkNow]=useState(()=>Date.now());
 const online=useMemo(()=>supabaseClient?createAshykOnlineAdapter(supabaseClient):null,[supabaseClient]),unsubscribeRoom=useRef(null),unsubscribeInvite=useRef(null),onlineRoomRef=useRef(null),inviteRef=useRef(null);
 useEffect(()=>{store.setWords(words);},[store,words]);
 useEffect(()=>{onSessionActiveChange?.(state.status==='playing');return()=>onSessionActiveChange?.(false);},[state.status,onSessionActiveChange]);
 const stopInvite=()=>{unsubscribeInvite.current?.();unsubscribeInvite.current=null;};
 const applyRoom=(room,force=false,hydrate=true)=>{if(!room)return null;const prev=onlineRoomRef.current,changed=force||!prev||Number(prev.revision)!==Number(room.revision)||Number(prev.phase_seq||0)!==Number(room.phase_seq||0)||prev.status!==room.status||prev.active_user_id!==room.active_user_id;onlineRoomRef.current=room;setOnlineRoom(room);setNetworkNow(Date.now());setConnection('online');onRoomChange?.(room);if(changed&&hydrate)store.hydrateOnline(room,userId);if(room.status==='playing')setWaitingFriend(null);if(!['waiting','preparing','playing'].includes(room.status))sessionRef.current?.detachVisual();return room;};
 const refreshRoom=async(roomId=onlineRoomRef.current?.id)=>{if(!online||!roomId)return null;try{return applyRoom(await online.getRoom(roomId));}catch{setConnection('reconnecting');return null;}};
 const session=()=>{if(!sessionRef.current&&online&&userId)sessionRef.current=createAshykOnlineSessionController({online,userId,store,engine,getRoom:()=>onlineRoomRef.current,applyRoom,setConnection,setVisualConnection});return sessionRef.current;};
 const attachRoom=async(room)=>{if(!room||!online)return;unsubscribeRoom.current?.();applyRoom(room,true);session()?.attachVisual(room.id);unsubscribeRoom.current=online.subscribeRoom(room.id,(next)=>applyRoom(next),(error)=>{void error;setConnection('reconnecting');void refreshRoom(room.id);});try{const ready=await online.markReady(room.id);if(ready)applyRoom(ready);}catch{setConnection('reconnecting');void refreshRoom(room.id);}};
 const attachInvite=(invite,friend)=>{if(!invite)return;inviteRef.current=invite;setWaitingFriend(friend||null);stopInvite();unsubscribeInvite.current=online?.subscribeInvite(invite.id,(next)=>{inviteRef.current=next;if(next.status==='accepted')setWaitingFriend(null);if(['declined','cancelled','expired'].includes(next.status)){setWaitingFriend(null);unsubscribeRoom.current?.();unsubscribeRoom.current=null;sessionRef.current?.detachVisual();onlineRoomRef.current=null;setOnlineRoom(null);onRoomChange?.(null);store.restart();}})||null;};
 const onInvite=(result,friend)=>{if(!result?.room)return;void attachRoom(result.room);attachInvite(result.invite,friend);};
 const clearRoomLocal=()=>{stopInvite();unsubscribeRoom.current?.();unsubscribeRoom.current=null;sessionRef.current?.detachVisual();onlineRoomRef.current=null;inviteRef.current=null;setOnlineRoom(null);setWaitingFriend(null);onRoomChange?.(null);store.restart();};
 const cancelInvite=async()=>{const room=onlineRoomRef.current,invite=inviteRef.current;if(online&&room?.id)await online.leaveRoom(room.id).catch(()=>{});else if(invite&&online)await online.cancelInvite(invite.id).catch(()=>{});clearRoomLocal();};
 const endCurrentGame=async()=>{const room=onlineRoomRef.current;if(!room||!online)return;if(room.status==='playing'&&globalThis.confirm&&!globalThis.confirm(m.confirmResign))return;const wasPlaying=room.status==='playing';await online.leaveRoom(room.id).catch(()=>{});clearRoomLocal();if(wasPlaying)onExit?.();};
 const claimForfeit=async()=>{const room=onlineRoomRef.current;if(!room||!online)return;try{const next=await online.claimForfeit(room.id);if(next)applyRoom(next,true,true);}catch{setConnection('reconnecting');void refreshRoom(room.id);}};
 useEffect(()=>{if(initialRoom&&online&&userId&&onlineRoomRef.current?.id!==initialRoom.id)void attachRoom(initialRoom);},[initialRoom,online,userId]);
 useEffect(()=>{const roomId=onlineRoom?.id;if(!online||!roomId||!['waiting','preparing','playing'].includes(onlineRoom.status))return;let disposed=false;const pulse=async()=>{if(disposed)return;try{const next=await online.pingRoom(roomId);if(disposed||!next)return;applyRoom(next);}catch{if(!disposed){setConnection('reconnecting');await refreshRoom(roomId);}}};void pulse();const timer=globalThis.setInterval(()=>void pulse(),12000);return()=>{disposed=true;globalThis.clearInterval(timer);};},[online,onlineRoom?.id,onlineRoom?.status,userId]);
 useEffect(()=>{audioRef.current?.preload?.();const unlock=()=>audioRef.current?.unlock();window.addEventListener('pointerdown',unlock,{capture:true});window.addEventListener('keydown',unlock,{capture:true});return()=>{window.removeEventListener('pointerdown',unlock,{capture:true});window.removeEventListener('keydown',unlock,{capture:true});audioRef.current?.dispose();sessionRef.current?.destroy();sessionRef.current=null;store.destroy();engine.destroy();unsubscribeRoom.current?.();stopInvite();};},[]);
 useEffect(()=>{if(state.gameMode==='online'&&state.onlineAction)session()?.enqueue(state.onlineAction);},[state.gameMode,state.onlineAction?.id]);
 useEffect(()=>{if(!online||!onlineRoom?.id||onlineRoom.status!=='playing')return;const timer=globalThis.setInterval(()=>void session()?.resolveTimeoutIfDue(),500);return()=>globalThis.clearInterval(timer);},[online,onlineRoom?.id,onlineRoom?.status]);
 if(state.status==='setup')return <Setup state={state} store={store} m={m} locale={locale} userId={userId} online={online} engine={engine} audio={audioRef.current} friends={friends} onInvite={onInvite}/>;
 const lobby=state.gameMode==='online'&&['waiting','preparing'].includes(onlineRoom?.status),preparing=onlineRoom?.status==='preparing',localIsHost=onlineRoom?.host_user_id===userId,opponentSeenAt=localIsHost?onlineRoom?.guest_seen_at:onlineRoom?.host_seen_at,opponentAwayMs=onlineRoom?.status==='playing'&&opponentSeenAt?Math.max(0,networkNow-new Date(opponentSeenAt).getTime()):0,opponentAway=opponentAwayMs>30000,canFinishAway=opponentAwayMs>120000,blocked=help||menu||appearance||lobby||connection!=='online'||opponentAway,changeShotMode=(mode)=>{setShotMode(mode);session()?.sendLive('shot-mode',{mode});},sendVisual=(event,payload)=>session()?.sendLive(event,payload);
 return <div className="ashykGame"><AshykWebScene engine={engine} interactionUnlocked={state.status==='playing'&&store.isLocalTurn()&&state.phase!=='bonus-question'&&!blocked} cameraMode={cameraMode} shotMode={shotMode} launchShot={state.gameMode==='online'?((pieceId,command)=>session()?.launchOnlineShot(pieceId,command)):null}/><Hud state={state} store={store} m={m} locale={locale} shotMode={shotMode} setShotMode={changeShotMode} onMenu={()=>setMenu(true)} audio={audioRef.current}/>
 {lobby?<div className="ashykWaiting"><span>{sm('friend')}</span><strong>{preparing?sm('preparingGame'):sm('waitingFor',{name:waitingFriend?.nickname||m.opponent})}</strong><button className="ashykSecondary" type="button" onClick={()=>void cancelInvite()}>{sm('cancelInvite')}</button></div>:null}
 {connection!=='online'&&!lobby?<div className="ashykWaiting"><span>{sm('friend')}</span><strong>{sm('reconnecting')}</strong></div>:null}
 {connection==='online'&&opponentAway&&!lobby?<div className="ashykWaiting"><span>{sm('friend')}</span><strong>{sm('opponentAway')}</strong>{canFinishAway?<button className="ashykSecondary" type="button" onClick={()=>void claimForfeit()}>{sm('finishGame')}</button>:null}</div>:null}
 {state.outcome?<div className="ashykOutcome">{outcomeText(state.outcome,m)}</div>:null}<Menu open={menu} onClose={()=>setMenu(false)} onHelp={()=>setHelp(true)} onAppearance={()=>setAppearance(true)} onEndGame={()=>void endCurrentGame()} room={onlineRoom} m={m} audio={audioRef.current}/><Help open={help} onClose={()=>setHelp(false)} m={m} audio={audioRef.current}/><Appearance open={appearance} onClose={()=>setAppearance(false)} m={m} cameraMode={cameraMode} setCameraMode={setCameraMode} audio={audioRef.current}/><Question state={state} store={store} m={m} audio={audioRef.current} onVisual={sendVisual}/><Finish state={state} m={m} audio={audioRef.current} locale={locale} onExit={onExit}/></div>;
}
