import React,{useEffect,useMemo,useRef,useState} from 'react';
import {createAshykEngine} from '../engine.js';
import {createAshykGameStore} from '../store.js';
import {createAshykOnlineAdapter} from '../online.js';
import {DIFFICULTIES,DIFFICULTY_ORDER} from '../constants.js';
import {ashykMessages,difficultyLabel} from '../i18n.js';
import {faceValue} from '../faces.js';
import {SHOT_ICON_PATHS,SHOT_ICON_VIEWBOX} from '../shot-icons.js';
import {AshykWebScene} from './scene.jsx';
import {createWebAshykAudio} from './audio.js';

const FACE_HELP=Object.freeze([['chyk','faceChyk',1],['fok','faceFok',2],['tau','faceTau',3],['alchi','faceAlchi',4],['biy','faceBiy',15],['kyt','faceKyt',6]]);

function useStore(store){const[state,setState]=useState(()=>store.getState());useEffect(()=>store.subscribe(setState),[store]);return state;}
function Segmented({value,items,onChange,disabled=false,label}){return <div className="settingsSegments ashykSegmented" role="radiogroup" aria-label={label}>{items.map(([id,text])=><label className="settingsChoice" key={id}><input type="radio" name={`ashyk-${label||'choice'}`} value={id} checked={value===id} disabled={disabled} onChange={()=>onChange(id)}/><span>{text}</span></label>)}</div>;}
function PlayerName({player,state,m}){if(state.gameMode==='computer')return player===1?m.you:m.computerPlayer;return player===state.localPlayer?m.you:m.opponent;}
function outcomeText(outcome,m){if(!outcome)return'';if(outcome.code==='miss')return`${m.miss} · −1`;if(outcome.code==='faceMismatch')return`${m.faceMismatch} · 0`;if(outcome.code==='thirdTouched')return`${m.thirdTouched} · 0`;if(outcome.code==='correct')return`${m.correct} · +3`;if(outcome.code==='wrong')return`${m.wrong} · −1`;if(outcome.code==='timeout')return`${m.timeout} · ${m.noPenalty}`;if(outcome.code==='noPenalty')return m.noPenalty;if(outcome.code==='capture')return outcome.instant?`КЪЫТ × КЪЫТ · ${m.instantWin}`:`${outcome.face||m.capture} · +${outcome.delta||0}`;return outcome.code;}

function ShotIcon({kind,size=22}){const icon=SHOT_ICON_PATHS[kind];return <svg className="ashykShotSvg" width={size} height={size} viewBox={SHOT_ICON_VIEWBOX} aria-hidden="true" fill="none" stroke="currentColor" strokeWidth="1.7" strokeLinecap="round" strokeLinejoin="round">{icon?.circles?.map((circle,index)=><circle key={`c${index}`} {...circle} opacity={index?0.42:1}/>)||null}{icon?.paths?.map((d,index)=><path key={`p${index}`} d={d} strokeDasharray={(kind==='flat'||kind==='hop')&&index===0?'2.2 2.3':undefined}/>)||null}</svg>;}
function DialogShell({open,onClose,title,children,className=''}){if(!open)return null;return <div className="ashykDialogBackdrop" role="presentation" onMouseDown={(event)=>{if(event.target===event.currentTarget)onClose();}}><section className={`ashykDialog ${className}`} role="dialog" aria-modal="true"><header><h2>{title}</h2><button className="ashykCircleButton" type="button" aria-label="Close" onClick={onClose}>×</button></header>{children}</section></div>;}

function Setup({state,store,m,locale,userId,online,engine,audio,onOnlineRoom}){const config=DIFFICULTIES[state.selectedDifficulty],[code,setCode]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const create=async()=>{if(!online||!userId||busy)return;audio.playUiClick();setBusy(true);setError('');try{const initial={field:engine.snapshot(),scores:[0,0],currentPlayer:1,remainingAshyks:engine.getAliveCount(),winner:null,winByKyt:false,difficulty:state.selectedDifficulty},room=await online.createRoom(initial);onOnlineRoom(room);}catch(e){setError(String(e?.message||m.roomError));}finally{setBusy(false);}};
 const join=async()=>{if(!online||!userId||busy||code.length!==6)return;audio.playUiClick();setBusy(true);setError('');try{const room=await online.joinRoom(code);onOnlineRoom(room);}catch(e){setError(String(e?.message||m.roomError));}finally{setBusy(false);}};
 const click=(fn)=>(value)=>{audio.playUiClick();fn(value);};
 return <div className="ashykSetupScroll"><section className="ashykSetup" aria-labelledby="ashyk-setup-title"><div className="ashykPageHead"><span className="ashykEyebrow">{m.title}</span><h1 id="ashyk-setup-title">{m.newGame}</h1></div><div className="ashykSetupSection"><div className="ashykSectionLabel">{m.modeLabel}</div><Segmented value={state.gameMode} label={m.modeLabel} items={[["computer",m.computer],["online",m.online]]} onChange={click(store.setMode)}/></div><div className="ashykSetupSection"><div className="ashykSectionLabel">{m.difficultyLabel}</div><Segmented value={state.selectedDifficulty} label={m.difficultyLabel} items={DIFFICULTY_ORDER.map((id)=>[id,difficultyLabel(id,locale)])} onChange={click(store.setDifficulty)}/></div><div className="ashykFacts"><div><span>{m.shotTime}</span><b>{config.humanShotSeconds} {m.seconds}</b></div><div><span>{m.answerTime}</span><b>{config.humanQuestionSeconds} {m.seconds}</b></div>{state.gameMode==='computer'?<><div><span>{m.computerAccuracy}</span><b>{Math.round(config.computerShotAccuracy*100)}%</b></div><div><span>{m.computerAnswers}</span><b>{Math.round(config.computerAnswerAccuracy*100)}%</b></div></>:null}</div><p className="ashykScopeNote">{m.mediumWords}</p>{state.gameMode==='computer'?<button className="ashykPrimary" type="button" onClick={()=>{audio.playUiClick();store.startComputer(state.selectedDifficulty);}}>{m.start}</button>:<div className="ashykOnlineSetup">{!userId?<p className="ashykInlineNotice">{m.loginOnline}</p>:<><button className="ashykPrimary" type="button" disabled={busy} onClick={create}>{busy?m.connect:m.createRoom}</button><div className="ashykJoin"><input value={code} maxLength={6} placeholder={m.roomCode} aria-label={m.roomCode} onChange={(event)=>setCode(event.target.value.toUpperCase().replace(/[^A-F0-9]/g,''))}/><button type="button" disabled={busy||code.length!==6} onClick={join}>{m.join}</button></div></>}{error?<p className="ashykInlineError" role="alert">{error}</p>:null}</div>}</section></div>;
}

function Help({open,onClose,m,audio}){const close=()=>{audio.playUiClick();onClose();};return <DialogShell open={open} onClose={close} title={m.rules} className="ashykHelp"><div className="ashykHelpSection"><h3>{m.helpGoalTitle}</h3><p>{m.helpGoalText}</p></div><div className="ashykHelpSection"><h3>{m.helpControlsTitle}</h3><p>{m.helpControlsText}</p><div className="ashykHelpControls"><div><span className="ashykHelpIcon"><ShotIcon kind="tap"/></span><p><b>{m.tapAction}</b><small>{m.tapActionHelp}</small></p></div><div><span className="ashykHelpIcon"><ShotIcon kind="flat"/></span><p><b>{m.flatAction}</b><small>{m.flatActionHelp}</small></p></div><div><span className="ashykHelpIcon"><ShotIcon kind="hop"/></span><p><b>{m.hopAction}</b><small>{m.hopActionHelp}</small></p></div></div></div><div className="ashykHelpSection"><h3>{m.helpFacesTitle}</h3><p>{m.helpFacesText}</p><div className="ashykFacesGrid">{FACE_HELP.map(([face,key,score])=><div className={face==='kyt'?'ashykFaceRule kyt':'ashykFaceRule'} key={face}><strong>{m[key]}</strong><span>{score} {m.points}</span>{face==='kyt'?<small>{m.instantWin}</small>:null}</div>)}</div></div><div className="ashykHelpSection"><h3>{m.helpQuestionsTitle}</h3><p>{m.helpQuestionsText}</p></div><div className="ashykHelpSection ashykHelpKyt"><h3>{m.helpKytTitle}</h3><p>{m.helpKytText}</p></div><button className="ashykSecondary" type="button" onClick={close}>{m.close}</button></DialogShell>;}
function Menu({open,onClose,onHelp,onAppearance,m,audio}){const action=(fn)=>()=>{audio.playUiClick();onClose();fn();};return <DialogShell open={open} onClose={onClose} title={m.menu} className="ashykMenu"><div className="ashykMenuActions"><button className="ashykSecondary" type="button" onClick={action(onHelp)}>{m.help}</button><button className="ashykSecondary" type="button" onClick={action(onAppearance)}>{m.appearance}</button></div></DialogShell>;}
function Appearance({open,onClose,m,cameraMode,setCameraMode,audio}){return <DialogShell open={open} onClose={onClose} title={m.appearance} className="ashykAppearance"><div className="ashykAppearanceRow"><span>{m.cameraLabel}</span><Segmented value={cameraMode} label={m.cameraLabel} items={[["orbit",m.orbit],["top",m.top]]} onChange={(value)=>{audio.playUiClick();setCameraMode(value);}}/></div></DialogShell>;}

function Question({state,store,m,audio}){const question=state.question;if(state.status!=='playing'||state.phase!=='bonus-question'||!question)return null;const local=store.isLocalTurn(),computer=store.isComputerTurn();return <div className="ashykDialogBackdrop" role="presentation"><section className="ashykDialog ashykQuestion" role="dialog" aria-modal="true"><header><div><span className="ashykEyebrow">{m.bonusQuestion}</span><h2>{m.translate}</h2></div><div className={state.questionSeconds<=3&&local?'ashykTimer danger':'ashykTimer'}>{computer||!local?'…':state.questionSeconds}</div></header><div className="ashykPrompt">{question.prompt}</div><div className="ashykOptions">{question.options.map((option)=><button key={option.id} type="button" disabled={state.questionLocked||computer||!local} className={String(state.wrongAnswerId)===String(option.id)?'wrong':''} onClick={()=>{audio.playUiClick();store.submitAnswer(option.id);}}>{option.text}</button>)}</div><button className="ashykSecondary" type="button" disabled={state.questionLocked||computer||!local} onClick={()=>{audio.playUiClick();store.skipQuestion();}}>{computer?m.computerAnswersNow:!local?m.opponentAnswersNow:m.skip}</button><p className="ashykRuleNote">{m.questionRule}</p></section></div>;}
function Finish({state,m,audio,onExit}){if(state.status!=='finished')return null;const title=state.winner==='draw'?m.draw:state.winner===state.localPlayer?m.youWon:m.youLost;return <div className="ashykDialogBackdrop" role="presentation"><section className="ashykDialog ashykFinish" role="dialog" aria-modal="true"><span className="ashykEyebrow">{m.gameOver}</span><h2>{title}</h2><div className="ashykFinalScore"><strong>{state.scores[0]}</strong><span>:</span><strong>{state.scores[1]}</strong></div>{state.winByKyt?<p className="ashykKytResult">КЪЫТ × КЪЫТ · {m.instantWin}</p>:<p>{m.finalField}</p>}<button className="ashykPrimary" type="button" onClick={()=>{audio.playUiClick();onExit?.();}}>{m.backToPractice}</button></section></div>;}

function Hud({state,store,m,shotMode,setShotMode,onMenu,audio}){const local=store.isLocalTurn(),shotDisabled=state.status!=='playing'||!local||!state.ready||state.phase==='bonus-question',showStatus=Boolean(state.statusCode&&state.statusCode!=='statusChoosePiece');return <><div className="ashykScore"><div className={state.player===1?'active':''}><span><PlayerName player={1} state={state} m={m}/></span><strong>{state.scores[0]}</strong></div><b>:</b><div className={state.player===2?'active':''}><strong>{state.scores[1]}</strong><span><PlayerName player={2} state={state} m={m}/></span></div></div><div className={state.shotSeconds<=5&&local?'ashykTurnTimer danger':'ashykTurnTimer'} aria-label={m.shotTime}>{state.status==='playing'&&local&&state.phase!=='bonus-question'?`${state.shotSeconds} ${m.seconds}`:'—'}</div><button className="ashykMenuButton" type="button" aria-label={m.menu} onClick={()=>{audio.playUiClick();onMenu();}}>•••</button><div className="ashykShotIcons" role="group" aria-label={m.shotType}><span className="ashykShotInfo" aria-label={m.tapAction} title={m.tapAction}><ShotIcon kind="tap" size={20}/></span><button type="button" className={shotMode==='flat'?'active':''} disabled={shotDisabled} aria-pressed={shotMode==='flat'} aria-label={m.flatAction} title={m.flatAction} onClick={()=>{audio.playUiClick();setShotMode('flat');}}><ShotIcon kind="flat" size={21}/></button><button type="button" className={shotMode==='hop'?'active':''} disabled={shotDisabled} aria-pressed={shotMode==='hop'} aria-label={m.hopAction} title={m.hopAction} onClick={()=>{audio.playUiClick();setShotMode('hop');}}><ShotIcon kind="hop" size={21}/></button></div>{state.selectedFace?<div className="ashykFace"><span>{m.position}</span><strong>{state.selectedFace}</strong><b>{state.selectedFace==='КЪЫТ'?m.kytWin:`${faceValue(state.selectedFace)}`}</b></div>:null}{showStatus?<div className="ashykStatus"><i className={state.ready?'ready':''}/><strong>{m[state.statusCode]||m.statusChoosePiece}</strong></div>:null}</>;}

export function AshykGame({words=[],locale='ru',supabaseClient=null,userId='',onSessionActiveChange=null,onExit=null}){const m=ashykMessages(locale),audioRef=useRef(null),storeRef=useRef(null);if(!audioRef.current)audioRef.current=createWebAshykAudio();if(!storeRef.current){let store=null;const engine=createAshykEngine({onEvent:(event)=>{if(event.type==='impact')audioRef.current?.playImpact(event.kind,event.strength,event.key,event.pan);if(event.type==='rolling')audioRef.current?.updateRolling(event.key,event.linearSpeed,event.angularSpeed,event.grounded,event.pan);store?.handleEngineEvent(event);}});store=createAshykGameStore({engine,words});storeRef.current={engine,store};}
 const {engine,store}=storeRef.current,state=useStore(store),[cameraMode,setCameraMode]=useState('orbit'),[shotMode,setShotMode]=useState('flat'),[help,setHelp]=useState(false),[menu,setMenu]=useState(false),[appearance,setAppearance]=useState(false),[onlineRoom,setOnlineRoom]=useState(null);const online=useMemo(()=>supabaseClient?createAshykOnlineAdapter(supabaseClient):null,[supabaseClient]),syncing=useRef(false),unsubscribeRoom=useRef(null),onlineRoomRef=useRef(null);
 useEffect(()=>{store.setWords(words);},[store,words]);
 useEffect(()=>{onSessionActiveChange?.(state.status==='playing');return()=>onSessionActiveChange?.(false);},[state.status,onSessionActiveChange]);
 useEffect(()=>{const unlock=()=>audioRef.current?.unlock();window.addEventListener('pointerdown',unlock,{capture:true});window.addEventListener('keydown',unlock,{capture:true});return()=>{window.removeEventListener('pointerdown',unlock,{capture:true});window.removeEventListener('keydown',unlock,{capture:true});audioRef.current?.dispose();store.destroy();engine.destroy();unsubscribeRoom.current?.();const room=onlineRoomRef.current;if(room&&online)void online.leaveRoom(room.id).catch(()=>{});};},[]);
 const hydrate=(room)=>{if(!room)return;onlineRoomRef.current=room;setOnlineRoom(room);store.hydrateOnline(room,userId);};
 const onOnlineRoom=(room)=>{unsubscribeRoom.current?.();hydrate(room);if(online)unsubscribeRoom.current=online.subscribeRoom(room.id,hydrate);};
 useEffect(()=>{if(!online||!onlineRoom||!userId||syncing.current||state.gameMode!=='online')return;const localPlayer=onlineRoom.host_user_id===userId?1:onlineRoom.guest_user_id===userId?2:null;if(!localPlayer||onlineRoom.active_user_id!==userId)return;const desired=state.player===1?onlineRoom.host_user_id:onlineRoom.guest_user_id,finished=state.status==='finished';if(!finished&&state.player===localPlayer)return;if(!desired&&!finished)return;syncing.current=true;void online.submitRoomState(onlineRoom,store.onlineGameState(),finished?userId:desired,finished?'finished':'playing').then(hydrate).catch(()=>{}).finally(()=>{syncing.current=false;});},[online,onlineRoom,userId,state.gameMode,state.player,state.status,state.scores,state.remainingAshyks,state.winner]);
 if(state.status==='setup')return <Setup state={state} store={store} m={m} locale={locale} userId={userId} online={online} engine={engine} audio={audioRef.current} onOnlineRoom={onOnlineRoom}/>;
 const blocked=help||menu||appearance;
 return <div className="ashykGame"><AshykWebScene engine={engine} interactionUnlocked={state.status==='playing'&&store.isLocalTurn()&&state.phase!=='bonus-question'&&!blocked} cameraMode={cameraMode} shotMode={shotMode}/><Hud state={state} store={store} m={m} shotMode={shotMode} setShotMode={setShotMode} onMenu={()=>setMenu(true)} audio={audioRef.current}/>{state.gameMode==='online'&&onlineRoom?.status==='waiting'?<div className="ashykWaiting"><span>{m.roomCode}</span><strong>{onlineRoom.code}</strong><small>{m.shareCode}</small></div>:null}{state.outcome?<div className="ashykOutcome">{outcomeText(state.outcome,m)}</div>:null}<Menu open={menu} onClose={()=>setMenu(false)} onHelp={()=>setHelp(true)} onAppearance={()=>setAppearance(true)} m={m} audio={audioRef.current}/><Help open={help} onClose={()=>setHelp(false)} m={m} audio={audioRef.current}/><Appearance open={appearance} onClose={()=>setAppearance(false)} m={m} cameraMode={cameraMode} setCameraMode={setCameraMode} audio={audioRef.current}/><Question state={state} store={store} m={m} audio={audioRef.current}/><Finish state={state} m={m} audio={audioRef.current} onExit={onExit}/></div>;}
