import React,{useEffect,useMemo,useRef,useState} from 'react';
import {createAshykEngine} from '../engine.js';
import {createAshykGameStore} from '../store.js';
import {createAshykOnlineAdapter} from '../online.js';
import {DIFFICULTIES,DIFFICULTY_ORDER} from '../constants.js';
import {ashykMessages,difficultyLabel} from '../i18n.js';
import {faceValue} from '../faces.js';
import {AshykWebScene} from './scene.jsx';
import {createWebAshykAudio} from './audio.js';

function useStore(store){const [state,setState]=useState(()=>store.getState());useEffect(()=>store.subscribe(setState),[store]);return state;}
function Segmented({value,items,onChange,disabled=false,label}){return <div className="settingsSegments ashykSegmented" role="radiogroup" aria-label={label}>{items.map(([id,text])=><label className="settingsChoice" key={id}><input type="radio" name={`ashyk-${label||'choice'}`} value={id} checked={value===id} disabled={disabled} onChange={()=>onChange(id)}/><span>{text}</span></label>)}</div>;}
function PlayerName({player,state,m}){if(state.gameMode==='computer')return player===1?m.you:m.computerPlayer;return player===state.localPlayer?m.you:m.opponent;}
function outcomeText(outcome,m){if(!outcome)return'';if(outcome.code==='miss')return`${m.miss} · −1`;if(outcome.code==='faceMismatch')return`${m.faceMismatch} · 0`;if(outcome.code==='thirdTouched')return`${m.thirdTouched} · 0`;if(outcome.code==='correct')return`${m.correct} · +3`;if(outcome.code==='wrong')return`${m.wrong} · −1`;if(outcome.code==='timeout')return`${m.timeout} · ${m.noPenalty}`;if(outcome.code==='noPenalty')return m.noPenalty;if(outcome.code==='capture')return outcome.instant?`КЪЫТ × КЪЫТ · ${m.won}`:`${outcome.face||m.capture} · +${outcome.delta||0}`;return outcome.code;}
function Setup({state,store,m,locale,userId,online,engine,audio,onOnlineRoom}){const config=DIFFICULTIES[state.selectedDifficulty], [code,setCode]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const create=async()=>{if(!online||!userId||busy)return;audio.playUiClick();setBusy(true);setError('');try{const initial={field:engine.snapshot(),scores:[0,0],currentPlayer:1,remainingAshyks:engine.getAliveCount(),winner:null,winByKyt:false,difficulty:state.selectedDifficulty},room=await online.createRoom(initial);onOnlineRoom(room);}catch(e){setError(String(e?.message||m.roomError));}finally{setBusy(false);}};
 const join=async()=>{if(!online||!userId||busy||code.length!==6)return;audio.playUiClick();setBusy(true);setError('');try{const room=await online.joinRoom(code);onOnlineRoom(room);}catch(e){setError(String(e?.message||m.roomError));}finally{setBusy(false);}};
 const click=(fn)=>(value)=>{audio.playUiClick();fn(value);};
 return <div className="ashykSetupScroll"><section className="ashykSetup" aria-labelledby="ashyk-setup-title"><div className="ashykPageHead"><span className="ashykEyebrow">{m.title}</span><h1 id="ashyk-setup-title">{m.newGame}</h1></div><div className="ashykSetupSection"><div className="ashykSectionLabel">{m.modeLabel}</div><Segmented value={state.gameMode} label={m.modeLabel} items={[["computer",m.computer],["online",m.online]]} onChange={click(store.setMode)}/></div><div className="ashykSetupSection"><div className="ashykSectionLabel">{m.difficultyLabel}</div><Segmented value={state.selectedDifficulty} label={m.difficultyLabel} items={DIFFICULTY_ORDER.map((id)=>[id,difficultyLabel(id,locale)])} onChange={click(store.setDifficulty)}/></div><div className="ashykFacts"><div><span>{m.shotTime}</span><b>{config.humanShotSeconds} {m.seconds}</b></div><div><span>{m.answerTime}</span><b>{config.humanQuestionSeconds} {m.seconds}</b></div>{state.gameMode==='computer'?<><div><span>{m.computerAccuracy}</span><b>{Math.round(config.computerShotAccuracy*100)}%</b></div><div><span>{m.computerAnswers}</span><b>{Math.round(config.computerAnswerAccuracy*100)}%</b></div></>:null}</div><p className="ashykScopeNote">{m.mediumWords}</p>{state.gameMode==='computer'?<button className="ashykPrimary" type="button" disabled={false} onClick={()=>{audio.playUiClick();store.startComputer(state.selectedDifficulty);}}>{m.start}</button>:<div className="ashykOnlineSetup">{!userId?<p className="ashykInlineNotice">{m.loginOnline}</p>:<><button className="ashykPrimary" type="button" disabled={busy} onClick={create}>{busy?m.connect:m.createRoom}</button><div className="ashykJoin"><input value={code} maxLength={6} placeholder={m.roomCode} aria-label={m.roomCode} onChange={(event)=>setCode(event.target.value.toUpperCase().replace(/[^A-F0-9]/g,''))}/><button type="button" disabled={busy||code.length!==6} onClick={join}>{m.join}</button></div></>}{error?<p className="ashykInlineError" role="alert">{error}</p>:null}</div>}</section></div>;
}
function Help({open,onClose,m,audio}){if(!open)return null;return <div className="ashykDialogBackdrop" role="presentation"><section className="ashykDialog ashykHelp" role="dialog" aria-modal="true" aria-labelledby="ashyk-help-title"><header><h2 id="ashyk-help-title">{m.rules}</h2><button className="ashykCircleButton" type="button" aria-label={m.close} onClick={()=>{audio.playUiClick();onClose();}}>×</button></header><p>{m.rulesGoal}</p><div className="ashykRuleRows"><div>{m.sameFace}</div><div>{m.thirdPiece}</div><div><strong>{m.kytWin}</strong></div><div>{m.bonus}</div></div></section></div>}
function Question({state,store,m,audio}){const question=state.question;if(state.status!=='playing'||state.phase!=='bonus-question'||!question)return null;const local=store.isLocalTurn(),computer=store.isComputerTurn();return <div className="ashykDialogBackdrop" role="presentation"><section className="ashykDialog ashykQuestion" role="dialog" aria-modal="true" aria-labelledby="ashyk-question-title"><header><div><span className="ashykEyebrow">{m.bonusQuestion}</span><h2 id="ashyk-question-title">{m.translate}</h2></div><div className={state.questionSeconds<=3&&local?'ashykTimer danger':'ashykTimer'}>{computer||!local?'…':state.questionSeconds}</div></header><div className="ashykPrompt">{question.prompt}</div><div className="ashykOptions">{question.options.map((option)=><button key={option.id} type="button" disabled={state.questionLocked||computer||!local} className={String(state.wrongAnswerId)===String(option.id)?'wrong':''} onClick={()=>{audio.playUiClick();store.submitAnswer(option.id);}}>{option.text}</button>)}</div><button className="ashykSecondary" type="button" disabled={state.questionLocked||computer||!local} onClick={()=>{audio.playUiClick();store.skipQuestion();}}>{computer?m.computerAnswersNow:!local?m.opponentAnswersNow:m.skip}</button><p className="ashykRuleNote">{m.questionRule}</p></section></div>}
function Finish({state,store,m,audio}){if(state.status!=='finished')return null;const name=state.winner==='draw'?m.draw:<><PlayerName player={state.winner||1} state={state} m={m}/> {m.won}</>;return <div className="ashykDialogBackdrop" role="presentation"><section className="ashykDialog ashykFinish" role="dialog" aria-modal="true"><span className="ashykEyebrow">{m.gameOver}</span><h2>{name}</h2><div className="ashykFinalScore"><strong>{state.scores[0]}</strong><span>:</span><strong>{state.scores[1]}</strong></div><p>{state.winByKyt?m.kytWin:m.finalField}</p><button className="ashykPrimary" type="button" onClick={()=>{audio.playUiClick();store.restart();}}>{m.newGame}</button></section></div>}
function Hud({state,store,m,locale,cameraMode,setCameraMode,shotMode,setShotMode,onHelp,audio}){const local=store.isLocalTurn(),shotDisabled=state.status!=='playing'||!local||!state.ready||state.phase==='bonus-question';return <><div className="ashykScore"><div className={state.player===1?'active':''}><span><PlayerName player={1} state={state} m={m}/></span><strong>{state.scores[0]}</strong></div><b>:</b><div className={state.player===2?'active':''}><strong>{state.scores[1]}</strong><span><PlayerName player={2} state={state} m={m}/></span></div></div><div className="ashykTopControls"><button type="button" onClick={()=>{audio.playUiClick();onHelp(true);}}>? {m.help}</button><Segmented value={cameraMode} label={m.cameraLabel} items={[["orbit",m.orbit],["top",m.top]]} onChange={(value)=>{audio.playUiClick();setCameraMode(value);}}/><button type="button" aria-label={m.newGame} onClick={()=>{audio.playUiClick();store.restart();}}>↻</button></div><div className="ashykShotControl"><span>{m.shotType}</span><Segmented value={shotMode} label={m.shotType} items={[["flat",m.flat],["hop",m.hop]]} disabled={shotDisabled} onChange={(value)=>{audio.playUiClick();setShotMode(value);}}/></div><div className={state.shotSeconds<=5&&local?'ashykShotTimer danger':'ashykShotTimer'}><span>{state.phase==='bonus-shot'?m.bonusShotLabel:m.shotLabel}</span><strong>{state.status==='playing'&&local&&state.phase!=='bonus-question'?state.shotSeconds:'—'}</strong></div>{state.selectedFace?<div className="ashykFace"><span>{m.position}</span><strong>{state.selectedFace}</strong><b>{state.selectedFace==='КЪЫТ'?m.kytWin:`${faceValue(state.selectedFace)}`}</b></div>:null}<div className="ashykStatus"><i className={state.ready?'ready':''}/><strong>{m[state.statusCode]||m.statusChoosePiece}</strong></div></>}

export function AshykGame({words=[],locale='ru',supabaseClient=null,userId=''}){const m=ashykMessages(locale),audioRef=useRef(null),storeRef=useRef(null);if(!audioRef.current)audioRef.current=createWebAshykAudio();if(!storeRef.current){let store=null;const engine=createAshykEngine({onEvent:(event)=>{if(event.type==='impact')audioRef.current?.playImpact(event.kind,event.strength,event.key,event.pan);if(event.type==='rolling')audioRef.current?.updateRolling(event.key,event.linearSpeed,event.angularSpeed,event.grounded,event.pan);store?.handleEngineEvent(event);}});store=createAshykGameStore({engine,words});storeRef.current={engine,store};}
 const {engine,store}=storeRef.current,state=useStore(store),[cameraMode,setCameraMode]=useState('orbit'),[shotMode,setShotMode]=useState('flat'),[help,setHelp]=useState(false),[onlineRoom,setOnlineRoom]=useState(null);const online=useMemo(()=>supabaseClient?createAshykOnlineAdapter(supabaseClient):null,[supabaseClient]),syncing=useRef(false),unsubscribeRoom=useRef(null),onlineRoomRef=useRef(null);
 useEffect(()=>{store.setWords(words);},[store,words]);useEffect(()=>{const unlock=()=>audioRef.current?.unlock();window.addEventListener('pointerdown',unlock,{capture:true});window.addEventListener('keydown',unlock,{capture:true});return()=>{window.removeEventListener('pointerdown',unlock,{capture:true});window.removeEventListener('keydown',unlock,{capture:true});audioRef.current?.dispose();store.destroy();engine.destroy();unsubscribeRoom.current?.();const room=onlineRoomRef.current;if(room&&online)void online.leaveRoom(room.id).catch(()=>{});};},[]);
 const hydrate=(room)=>{if(!room)return;onlineRoomRef.current=room;setOnlineRoom(room);store.hydrateOnline(room,userId);};
 const onOnlineRoom=(room)=>{unsubscribeRoom.current?.();hydrate(room);if(online)unsubscribeRoom.current=online.subscribeRoom(room.id,hydrate);};
 useEffect(()=>{if(!online||!onlineRoom||!userId||syncing.current||state.gameMode!=='online')return;const localPlayer=onlineRoom.host_user_id===userId?1:onlineRoom.guest_user_id===userId?2:null;if(!localPlayer||onlineRoom.active_user_id!==userId)return;const desired=state.player===1?onlineRoom.host_user_id:onlineRoom.guest_user_id,finished=state.status==='finished';if(!finished&&state.player===localPlayer)return;if(!desired&&!finished)return;syncing.current=true;void online.submitRoomState(onlineRoom,store.onlineGameState(),finished?userId:desired,finished?'finished':'playing').then(hydrate).catch(()=>{}).finally(()=>{syncing.current=false;});},[online,onlineRoom,userId,state.gameMode,state.player,state.status,state.scores,state.remainingAshyks,state.winner]);
 if(state.status==='setup')return <Setup state={state} store={store} m={m} locale={locale} userId={userId} online={online} engine={engine} audio={audioRef.current} onOnlineRoom={onOnlineRoom}/>;
 return <div className="ashykGame"><AshykWebScene engine={engine} interactionUnlocked={state.status==='playing'&&store.isLocalTurn()&&state.phase!=='bonus-question'&&!help} cameraMode={cameraMode} shotMode={shotMode}/><Hud state={state} store={store} m={m} locale={locale} cameraMode={cameraMode} setCameraMode={setCameraMode} shotMode={shotMode} setShotMode={setShotMode} onHelp={setHelp} audio={audioRef.current}/>{state.gameMode==='online'&&onlineRoom?.status==='waiting'?<div className="ashykWaiting"><span>{m.roomCode}</span><strong>{onlineRoom.code}</strong><small>{m.shareCode}</small></div>:null}{state.outcome?<div className="ashykOutcome">{outcomeText(state.outcome,m)}</div>:null}<Help open={help} onClose={()=>setHelp(false)} m={m} audio={audioRef.current}/><Question state={state} store={store} m={m} audio={audioRef.current}/><Finish state={state} store={store} m={m} audio={audioRef.current}/></div>}
