import React,{useEffect,useRef} from 'react';
import * as THREE from 'three';
import {OrbitControls} from 'three/examples/jsm/controls/OrbitControls.js';
import {ASHYK_COLORS,MAX_PULL,SHOT_CANCEL_RADIUS} from '../constants.js';
import {ASHYK_SCENE_MATERIALS,createAshykBoardVisual,createAshykVisual,disposeAshykBoardVisual} from '../model/index.js';

function pieceFromObject(object,visuals){let current=object;while(current){const id=current.userData?.ashykId;if(typeof id==='number')return visuals.get(id)||null;current=current.parent;}return null;}
export function AshykWebScene({engine,interactionUnlocked=true,cameraMode='orbit',shotMode='flat'}){const host=useRef(null),mode=useRef(cameraMode),strike=useRef(shotMode),enabled=useRef(interactionUnlocked);mode.current=cameraMode;strike.current=shotMode;enabled.current=interactionUnlocked;
 useEffect(()=>{const element=host.current;if(!element||!engine)return;let disposed=false,animation=0,last=performance.now();const renderer=new THREE.WebGLRenderer({antialias:true,alpha:false});renderer.setPixelRatio(Math.min(devicePixelRatio||1,2));renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.04;element.appendChild(renderer.domElement);const scene=new THREE.Scene();scene.background=new THREE.Color(ASHYK_SCENE_MATERIALS.background);const camera=new THREE.PerspectiveCamera(42,1,.5,110);camera.position.set(27,23,28);const controls=new OrbitControls(camera,renderer.domElement);controls.target.set(0,.3,0);controls.enableDamping=true;controls.dampingFactor=.12;controls.rotateSpeed=1.35;controls.zoomSpeed=1.05;controls.enablePan=false;controls.minDistance=20;controls.maxDistance=72;controls.maxPolarAngle=THREE.MathUtils.degToRad(70);controls.minPolarAngle=Math.PI*.13;scene.add(new THREE.HemisphereLight(0xdde9d7,0x20160f,1.7));const sun=new THREE.DirectionalLight(0xffefd0,2.8);sun.position.set(22,30,18);sun.castShadow=true;sun.shadow.mapSize.set(1024,1024);scene.add(sun);
 const board=createAshykBoardVisual(THREE);scene.add(board);
 const visuals=new Map(),selectable=[];const ensureVisual=(id)=>{if(visuals.has(id))return visuals.get(id);const mesh=createAshykVisual(THREE,id);visuals.set(id,mesh);scene.add(mesh);return mesh;};
 const selection=new THREE.Mesh(new THREE.RingGeometry(.92,1.31,64),new THREE.MeshBasicMaterial({color:ASHYK_COLORS.accent,transparent:true,opacity:.78,side:THREE.DoubleSide,depthWrite:false}));selection.rotation.x=-Math.PI/2;selection.position.y=.178;selection.visible=false;scene.add(selection);
 const dotGeometry=new THREE.SphereGeometry(.14,12,8),dots=Array.from({length:16},(_,index)=>{const dot=new THREE.Mesh(dotGeometry,new THREE.MeshBasicMaterial({color:ASHYK_SCENE_MATERIALS.trajectory,transparent:true,opacity:Math.max(.52,.92-index*.035),depthTest:false,depthWrite:false}));dot.visible=false;dot.renderOrder=12;scene.add(dot);return dot;});const hideDots=()=>dots.forEach((dot)=>{dot.visible=false;});
 const sync=()=>{selectable.length=0;for(const piece of engine.getPieces()){const visual=ensureVisual(piece.id);visual.visible=piece.alive;if(!piece.alive)continue;visual.position.set(piece.body.position.x,piece.body.position.y,piece.body.position.z);visual.quaternion.set(piece.body.quaternion.x,piece.body.quaternion.y,piece.body.quaternion.z,piece.body.quaternion.w);selectable.push(visual);}const selectedId=engine.getSelectedId(),piece=selectedId===null?null:engine.getPiece(selectedId);selection.visible=Boolean(piece);if(piece){selection.position.x=piece.body.position.x;selection.position.z=piece.body.position.z;}};
 const raycaster=new THREE.Raycaster(),pointer=new THREE.Vector2(),plane=new THREE.Plane(new THREE.Vector3(0,1,0),0),hit=new THREE.Vector3();const setPointer=(event)=>{const rect=renderer.domElement.getBoundingClientRect();pointer.x=(event.clientX-rect.left)/Math.max(1,rect.width)*2-1;pointer.y=-(event.clientY-rect.top)/Math.max(1,rect.height)*2+1;raycaster.setFromCamera(pointer,camera);};
 let aiming=false,aimPointer=null,startX=0,startY=0,aimCommand=null,lastMode='orbit';
 const updateAim=(event)=>{const selectedId=engine.getSelectedId(),piece=selectedId===null?null:engine.getPiece(selectedId);if(!piece)return;setPointer(event);if(!raycaster.ray.intersectPlane(plane,hit))return;const ox=hit.x-piece.body.position.x,oz=hit.z-piece.body.position.z,pull=Math.min(MAX_PULL,Math.hypot(ox,oz));if(pull<=SHOT_CANCEL_RADIUS){aimCommand=null;hideDots();return;}const inv=1/Math.max(.0001,Math.hypot(ox,oz)),dx=-ox*inv,dz=-oz*inv;aimCommand={mode:strike.current,directionX:dx,directionZ:dz,pullLength:pull};const points=engine.preview({mode:strike.current,originX:piece.body.position.x,originY:piece.body.position.y,originZ:piece.body.position.z,directionX:dx,directionZ:dz,pullLength:pull,steps:16});dots.forEach((dot,index)=>{const point=points[index];dot.visible=Boolean(point);if(point)dot.position.set(...point);});};
 const down=(event)=>{if(!enabled.current||!engine.isReady()||engine.isShotActive())return;setPointer(event);const object=raycaster.intersectObjects(selectable,true)[0]?.object||null,piece=pieceFromObject(object,visuals);if(piece){const current=engine.getSelectedId();if(current!==piece.userData.ashykId){engine.select(piece.userData.ashykId);hideDots();return;}aiming=true;aimPointer=event.pointerId;startX=event.clientX;startY=event.clientY;aimCommand=null;controls.enabled=false;renderer.domElement.setPointerCapture?.(event.pointerId);event.preventDefault();}else engine.clearSelection();};
 const move=(event)=>{if(!aiming||aimPointer!==event.pointerId)return;if(Math.hypot(event.clientX-startX,event.clientY-startY)<5)return;updateAim(event);};
 const up=(event)=>{if(!aiming||aimPointer!==event.pointerId)return;aiming=false;aimPointer=null;controls.enabled=true;renderer.domElement.releasePointerCapture?.(event.pointerId);if(aimCommand&&enabled.current)engine.launch(engine.getSelectedId(),aimCommand);aimCommand=null;hideDots();};
 renderer.domElement.addEventListener('pointerdown',down,true);renderer.domElement.addEventListener('pointermove',move,true);renderer.domElement.addEventListener('pointerup',up,true);renderer.domElement.addEventListener('pointercancel',up,true);
 const resize=()=>{const width=Math.max(1,element.clientWidth),height=Math.max(1,element.clientHeight);camera.aspect=width/height;camera.updateProjectionMatrix();renderer.setSize(width,height,false);};const observer=new ResizeObserver(resize);observer.observe(element);resize();
 const loop=(time)=>{if(disposed)return;animation=requestAnimationFrame(loop);const dt=Math.min((time-last)/1000,1/20);last=time;engine.step(dt,time);if(mode.current!==lastMode){lastMode=mode.current;if(lastMode==='top'){camera.position.set(.01,40,.01);controls.target.set(0,0,0);controls.enableRotate=false;controls.minDistance=20;controls.maxDistance=62;}else{camera.position.set(27,23,28);controls.target.set(0,.3,0);controls.enableRotate=true;controls.minDistance=20;controls.maxDistance=72;}}if(!aiming)controls.enabled=true;controls.update();sync();renderer.render(scene,camera);};animation=requestAnimationFrame(loop);
 return()=>{disposed=true;cancelAnimationFrame(animation);observer.disconnect();renderer.domElement.removeEventListener('pointerdown',down,true);renderer.domElement.removeEventListener('pointermove',move,true);renderer.domElement.removeEventListener('pointerup',up,true);renderer.domElement.removeEventListener('pointercancel',up,true);controls.dispose();dotGeometry.dispose();disposeAshykBoardVisual(board);renderer.dispose();if(renderer.domElement.parentElement===element)element.removeChild(renderer.domElement);};},[engine]);
 return <div className="ashykScene" ref={host} aria-label="Ашыкъ оюн 3D"/>;}
