function dictionaryId(word){return String(word?.dictionary_id||word?.dictionaryId||'').trim();}
function dictionaryName(word){return String(word?.dictionary_name||word?.dictionaryName||dictionaryId(word)).trim();}
function sectionId(word){return String(word?.section_id||word?.sectionId||'').trim();}
function sectionName(word){return String(word?.section_name||word?.sectionName||sectionId(word)).trim();}
export function practiceScopeKey(dictionary,section){return `${String(dictionary||'').trim()}||${String(section||'').trim()}`;}
export function practiceWordScopeKey(word){return practiceScopeKey(dictionaryId(word),sectionId(word));}
export function buildPracticeScope(words=[]){const dictionaries=new Map();for(const word of Array.isArray(words)?words:[]){const dictId=dictionaryId(word),wordSectionId=sectionId(word);if(!dictId||!wordSectionId)continue;if(!dictionaries.has(dictId))dictionaries.set(dictId,{id:dictId,name:dictionaryName(word),count:0,sections:new Map()});const dictionary=dictionaries.get(dictId);dictionary.count+=1;if(!dictionary.sections.has(wordSectionId))dictionary.sections.set(wordSectionId,{id:wordSectionId,name:sectionName(word),count:0});dictionary.sections.get(wordSectionId).count+=1;}return Array.from(dictionaries.values()).map((dictionary)=>({...dictionary,sections:Array.from(dictionary.sections.values())}));}
export function practiceSelectedPool(words=[],selectedKeys=new Set()){const keys=selectedKeys instanceof Set?selectedKeys:new Set(selectedKeys||[]);return (Array.isArray(words)?words:[]).filter((word)=>keys.has(practiceWordScopeKey(word)));}
export function scopeSelectionState(dictionary,selectedKeys=new Set()){const keys=selectedKeys instanceof Set?selectedKeys:new Set(selectedKeys||[]);const sectionKeys=(dictionary?.sections||[]).map((section)=>practiceScopeKey(dictionary?.id,section?.id));if(!sectionKeys.length)return 'none';const selected=sectionKeys.reduce((count,key)=>count+(keys.has(key)?1:0),0);if(selected===0)return 'none';if(selected===sectionKeys.length)return 'all';return 'partial';}
export function scopeSelectionCounts(scope=[],selectedKeys=new Set()){const keys=selectedKeys instanceof Set?selectedKeys:new Set(selectedKeys||[]);const dictionaries=(Array.isArray(scope)?scope:[]).filter((dictionary)=>scopeSelectionState(dictionary,keys)!=='none');let sections=0;for(const dictionary of Array.isArray(scope)?scope:[])for(const section of dictionary.sections||[])if(keys.has(practiceScopeKey(dictionary.id,section.id)))sections+=1;return{dictionaryCount:dictionaries.length,sectionCount:sections};}
export function selectedScopeSources(scope=[],selectedKeys=new Set()){const keys=selectedKeys instanceof Set?selectedKeys:new Set(selectedKeys||[]);return (Array.isArray(scope)?scope:[]).flatMap((dictionary)=>(dictionary.sections||[]).flatMap((section)=>{const key=practiceScopeKey(dictionary.id,section.id);return keys.has(key)?[{dictionaryId:String(dictionary.id),sectionId:String(section.id),scopeKey:key}]:[];}));}
