import { normalizePos } from './word-normalizer.js';
import { buildWordsByPOSRounds, hasWordConflict, shuffle } from './word-selection.js';

export function normalizeTestMode(mode){return mode==='ru'?'ru':'kb';}
export function normalizeTestLimit(limit){return[20,40,80].includes(Number(limit))?Number(limit):40;}
export function initializeTestState(state,pool,mode,limit,metadata={},optionPool=pool){state.mode=normalizeTestMode(mode);state.limit=normalizeTestLimit(limit);const sourceOptions=Array.isArray(optionPool)&&optionPool.length?optionPool:pool;state.optionPool=sourceOptions.slice();state.items=buildWordsByPOSRounds(pool,state.limit).items;state.index=0;state.correct=0;state.selectedAnswer=null;state.results=[];state.session.inProgress=true;state.session.completed=false;state.session.wordsPool=pool.slice();state.session.progressData={index:0,total:state.items.length,correct:0};state.session.metadata={...metadata};return state;}
export function testSessionWords(state){return state.results.map((result)=>({word_id:result.id,result:result.isCorrect?'correct':'wrong',wrong_word_id:result.isCorrect?null:result.wrongWordId||null}));}
export function testSessionPayload(state){const words=testSessionWords(state);return{questions_planned:state.items.length,questions_answered:words.length,correct_total:words.filter((word)=>word.result==='correct').length,wrong_total:words.filter((word)=>word.result==='wrong').length,words};}
export function testAbandonSummary(state){return{questions_total:state.items.length,questions_answered:state.index,items_total:state.items.length,items_completed:state.index,progress_percent:Math.round((state.index/Math.max(1,state.items.length))*100),correct_count:state.correct,wrong_count:Math.max(0,state.index-state.correct)};}
function optionText(state,candidate){return String(state.mode==='kb'?candidate?.trans:candidate?.word||'').trim();}
function addOptionsFrom(state,item,candidates,options,selectedWords,usedTexts){for(const candidate of shuffle(candidates.slice())){if(options.length>=4)break;if(String(candidate?.id)===String(item.id))continue;if(hasWordConflict(candidate,[item,...selectedWords]))continue;const text=optionText(state,candidate);if(!text||usedTexts.has(text))continue;usedTexts.add(text);selectedWords.push(candidate);options.push({id:candidate.id,text});}}
export function buildTestOptions(state,item){const correctText=optionText(state,item),targetPOS=normalizePos(item.pos),samePOS=(Array.isArray(state.optionPool)?state.optionPool:[]).filter((candidate)=>String(candidate?.id)!==String(item.id)&&normalizePos(candidate.pos)===targetPOS),options=[{id:item.id,text:correctText}],selectedWords=[],usedTexts=new Set([correctText]);addOptionsFrom(state,item,samePOS,options,selectedWords,usedTexts);return shuffle(options);}
export function applyTestAnswer(state,answer){if(state.index>=state.items.length||!answer?.id||!answer?.text)return null;const item=state.items[state.index],questionText=state.mode==='kb'?item.word:item.trans,correctAnswer=state.mode==='kb'?item.trans:item.word,isCorrect=String(answer.id)===String(item.id);if(isCorrect)state.correct+=1;const result={id:item.id,questionText,word:item.word,trans:item.trans,correctAnswer,userAnswer:answer.text,wrongWordId:isCorrect?null:String(answer.id),isCorrect};state.results.push(result);state.index+=1;state.selectedAnswer=null;state.session.progressData.index=state.index;state.session.progressData.correct=state.correct;return{item,result,isCorrect};}
export function testCompletionSummary(state){const total=state.items.length,wrong=Math.max(0,total-state.correct);return{items_total:total,items_completed:total,questions_total:total,questions_answered:total,correct_count:state.correct,wrong_count:wrong,accuracy_percent:Math.round((state.correct/Math.max(1,total))*100),dictionary_count:state.session.metadata.dictionaryCount||0,section_count:state.session.metadata.sectionCount||0};}
export function testStateSnapshot(state){if(!state?.session?.id)return null;return{id:state.session.id,startedAt:state.session.startedAt,mode:state.mode,limit:state.limit,metadata:{...(state.session.metadata||{})},poolIds:(state.session.wordsPool||[]).map((word)=>String(word.id)),itemIds:(state.items||[]).map((word)=>String(word.id)),index:Math.max(0,Number(state.index)||0),correct:Math.max(0,Number(state.correct)||0),results:Array.isArray(state.results)?state.results:[]};}
export function restoreTestStateSnapshot(snapshot,words,optionWords=words){if(!snapshot?.id)return null;const source=Array.isArray(words)?words:[],byId=new Map(source.map((word)=>[String(word.id),word])),pool=(snapshot.poolIds||[]).map((id)=>byId.get(String(id))).filter(Boolean);if(!pool.length)return null;const metadata=snapshot.metadata&&typeof snapshot.metadata==='object'?snapshot.metadata:{};const state={mode:snapshot.mode,limit:snapshot.limit,items:[],optionPool:[],index:0,correct:0,selectedAnswer:null,results:[],session:{id:snapshot.id,startedAt:snapshot.startedAt}};initializeTestState(state,pool,snapshot.mode,snapshot.limit,metadata,Array.isArray(optionWords)&&optionWords.length?optionWords:source);const ordered=(snapshot.itemIds||[]).map((id)=>byId.get(String(id))).filter(Boolean);if(ordered.length)state.items=ordered;state.index=Math.min(Math.max(0,Number(snapshot.index)||0),state.items.length);state.correct=Math.min(state.index,Math.max(0,Number(snapshot.correct)||0));state.results=Array.isArray(snapshot.results)?snapshot.results.slice(0,state.index):[];state.session.id=snapshot.id;state.session.startedAt=snapshot.startedAt;state.session.progressData={index:state.index,total:state.items.length,correct:state.correct};return state;}
