import { trackEvent } from "../../shared/analytics/analytics.js?v=16.8.0.1";
import { ACTIVITY_TYPES, CANCEL_REASONS, DIRECTIONS, EVENTS, WORD_RESULTS, WORD_SOURCES } from "../../shared/analytics/events.js?v=16.8.0.1";
import { createActivityTracker } from "../../shared/analytics/session-tracker.js?v=16.8.0.1";
import { createSessionRuntime, finalizeSessionRuntime, persistSessionRuntime, suspendSessionRuntime } from "../../shared/progress/session-builders.js?v=16.8.0.1";
import { clearPracticeSnapshot, loadPracticeSnapshot, savePracticeSnapshot } from "../../shared/state/practice-snapshot-store.js?v=16.8.0.1";
import { recordMatchWordResults } from "../../shared/progress/word-progress-store.js?v=16.8.0.1";
import { matchState } from "./state.js?v=16.8.0.1";
import { initializeMatchState, markMatchSolved, matchAbandonSummary, matchCompletionSummary, matchSessionPayload, matchStateSnapshot, matchWordById, recordMatchMismatch, restoreMatchStateSnapshot, takeNextMatchRound } from "../../../packages/alantil-core/match.js";

function persistMatchSession(){persistSessionRuntime(matchState.session.runtime,matchSessionPayload(matchState));const snapshot=matchStateSnapshot(matchState);if(snapshot)savePracticeSnapshot("match",snapshot);}
function attachRuntime(metadata={},startedAt=null){matchState.session.runtime=matchState.total?createSessionRuntime("match",{selected_sources:Array.isArray(metadata.selectedSources)?metadata.selectedSources:[]}):null;matchState.session.id=matchState.session.runtime?.id||null;matchState.session.startedAt=startedAt||new Date().toISOString();matchState.session.tracker=matchState.total?createActivityTracker(ACTIVITY_TYPES.MATCH):null;matchState.session.tracker?.start({direction:DIRECTIONS.NONE,limit:matchState.limit,items_total:matchState.total,items_completed:matchState.solvedCount,pairs_total:matchState.total,pairs_completed:matchState.solvedCount,dictionary_count:metadata.dictionaryCount||0,section_count:metadata.sectionCount||0});}
export function resumeMatchSession(words){const snapshot=loadPracticeSnapshot("match");if(!snapshot)return false;const restored=restoreMatchStateSnapshot(snapshot,words);if(!restored){clearPracticeSnapshot("match");return false;}Object.assign(matchState,restored);attachRuntime(matchState.session.metadata||{},snapshot.startedAt||null);persistMatchSession();return true;}
export function finalizeMatchSession(status="interrupted",exitReason="route_change"){const session=matchState.session;if(!session.runtime||session.runtime.finalized)return false;const payload=matchSessionPayload(matchState),result=finalizeSessionRuntime(session.runtime,{status,exitReason,payload});if(result?.id&&payload.words.length)recordMatchWordResults(result.id,payload.words,result.ended_at||new Date().toISOString());session.inProgress=false;session.completed=status==="completed";if(status==="completed"||exitReason===CANCEL_REASONS.NEW_SESSION)clearPracticeSnapshot("match");return result;}
function trackWord(id,result){const word=matchWordById(matchState,id);if(!word)return;trackEvent(EVENTS.WORD_RESULT,{word_id:word.id,source:WORD_SOURCES.MATCH,result,dictionary_id:word.dictionary_id,section_id:word.section_id,set_id:String(word.set_id),direction:DIRECTIONS.NONE});}
function abandonPreviousSession(){if(matchState.session.runtime&&!matchState.session.runtime.finalized)finalizeMatchSession("interrupted",CANCEL_REASONS.NEW_SESSION);const tracker=matchState.session.tracker;if(tracker?.getStatus()==="active")tracker.abandon(CANCEL_REASONS.NEW_SESSION,matchAbandonSummary(matchState));clearPracticeSnapshot("match");}
export function startMatch(pool,limit,metadata={}){abandonPreviousSession();initializeMatchState(matchState,pool,limit,metadata);attachRuntime(metadata);persistMatchSession();}
export function nextRound(){const round=takeNextMatchRound(matchState);if(round.length)persistMatchSession();return round;}
export function markSolved(id){const normalized=markMatchSolved(matchState,id);if(!normalized)return;trackWord(normalized,WORD_RESULTS.CORRECT);persistMatchSession();}
export function recordMismatch(firstId,secondId){const ids=recordMatchMismatch(matchState,firstId,secondId);ids.forEach((id)=>trackWord(id,WORD_RESULTS.WRONG));persistMatchSession();}
export function completeMatch(){if(!matchState.session.inProgress||matchState.session.completed)return false;finalizeMatchSession("completed",null);return matchState.session.tracker?.complete(matchCompletionSummary(matchState))||false;}
export function suspendMatchForResume(){if(!matchState.session.inProgress)return false;persistMatchSession();suspendSessionRuntime(matchState.session.runtime);matchState.session.inProgress=false;return true;}