import test from 'node:test';
import assert from 'node:assert/strict';
import { readdir, readFile } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
async function collectJs(dir){const entries=await readdir(dir,{withFileTypes:true}),files=[];for(const entry of entries){const full=path.join(dir,entry.name);if(entry.isDirectory()){if(entry.name==='node_modules')continue;files.push(...await collectJs(full));}else if(entry.name.endsWith('.js'))files.push(full);}return files;}
const files=await collectJs(root);const sourceEntries=await Promise.all(files.map(async(file)=>[path.relative(root,file).replaceAll('\\','/'),await readFile(file,'utf8')]));const source=sourceEntries.map(([,value])=>value).join('\n');const app=await readFile(path.join(root,'AppRoot.js'),'utf8');

test('Mobile 16.1 is a thin UI/platform layer over alantil-core',()=>{for(const module of ['test','match','favorites','learning-route','word-normalizer','settings','station-test','learning','profile','songs','word-progress','route-progress','sync-policy'])assert.match(source,new RegExp(`packages/alantil-core/${module}\\.js`));});
test('Mobile 16.1 consumes the Web starter dictionary instead of copying a dictionary',()=>{assert.match(app,/\.\.\/src\/data\/starter-dictionary\.js/);for(const [file,content] of sourceEntries){if(file==='AppRoot.js')continue;assert.doesNotMatch(content,/const\s+ROWS\s*=|STARTER_DICTIONARY\s*=\s*\[/,`copied dictionary in ${file}`);}});
test('Game and progress business algorithms are not reimplemented inside mobile',()=>{const forbidden=[/function\s+buildTestOptions\s*\(/,/function\s+initializeTestState\s*\(/,/function\s+initializeMatchState\s*\(/,/function\s+recordMatchMismatch\s*\(/,/function\s+buildStationTestSessionState\s*\(/,/function\s+initializeLearnState\s*\(/,/function\s+buildLearningRoute\s*\(/,/function\s+normalizeLegacyWordEntry\s*\(/,/function\s+applyLearnWordResults\s*\(/,/function\s+applyTestWordResults\s*\(/,/function\s+applyMatchWordResults\s*\(/,/function\s+mergeCloudWordProgressState\s*\(/];for(const [file,content] of sourceEntries)for(const pattern of forbidden)assert.doesNotMatch(content,pattern,`business algorithm duplicated in ${file}`);});
test('Mobile 16.1 has all native adapters and Web-parity screen modules',()=>{const names=new Set(sourceEntries.map(([file])=>file));for(const expected of ['platform/storage.js','platform/auth.js','platform/profile-api.js','platform/progress.js','platform/cloud-sync.js','platform/session-store.js','platform/hidden-words.js','platform/songs.js','screens/onboarding.js','screens/station.js','screens/learn.js','screens/station-test.js','screens/practice-games.js','screens/profile.js','screens/songs.js','ui/theme.js','ui/components.js','ui/icons.js'])assert.ok(names.has(expected),`missing ${expected}`);});
test('Mobile screens do not access Supabase REST directly',()=>{for(const [file,content] of sourceEntries){if(!file.startsWith('screens/'))continue;assert.doesNotMatch(content,/supabase\.co|\/rest\/v1|\/auth\/v1/,`platform access leaked into ${file}`);}});
