import React, { useEffect, useMemo, useRef, useState } from 'react';
import { Pressable, StyleSheet, Text, View } from 'react-native';
import { SafeAreaProvider, SafeAreaView } from 'react-native-safe-area-context';
import { StatusBar } from 'expo-status-bar';
import { EVENTS } from '../packages/alantil-core/analytics.js';
import { buildLearningRoute } from '../packages/alantil-core/learning-route.js';
import { getDisplayedWordCollection } from '../packages/alantil-core/alan-display.js';
import { toggleFavorite } from '../packages/alantil-core/favorites.js';
import { socialMessage } from '../packages/alantil-core/social-i18n.js';
import { createAshykOnlineAdapter } from '../packages/ashyk-game/online.js';
import { DEFAULT_USER_SETTINGS, hasCompletedLearningSetup } from '../packages/alantil-core/settings.js';
import { msg } from './i18n.js';
import { RuntimeSettingsProvider } from './ui/runtime-settings.js';
import { SocialBottomNav } from './ui/social-bottom-nav.js';
import { theme } from './ui/theme.js';
import { AccountScreen } from './screens/profile.js';
import { ProfileGate } from './screens/profile-gate.js';
import { StationScreen } from './screens/station.js';
import { LearnScreen } from './screens/learn.js';
import { StationTestScreen } from './screens/station-test.js';
import { SongsScreen } from './screens/songs.js';
import { OnboardingScreen } from './screens/onboarding.js';
import { AuthChoiceScreen } from './screens/auth-choice.js';
import { PathScreen } from './screens/path.js';
import { StoryWordListScreen } from './screens/story-word-list.js';
import { PracticeScreen } from './screens/practice.js';
import { AshykScreen } from './screens/ashyk.js';
import { FavoritesScreen } from './screens/favorites.js';
import { FriendsScreen } from './screens/friends.js';
import { AdminUserDetailScreen } from './screens/admin-users.js';
import { GeneralMatchFlow, GeneralTestFlow } from './screens/practice-games.js';
import { bootstrapNativeAuth, subscribeNativeAuth } from './platform/auth.js';
import { trackNativeEvent, trackNativeScreen } from './platform/analytics.js';
import { synchronizeNativeAccount } from './platform/cloud-sync.js';
import { bootstrapNativeDictionary } from './platform/dictionary.js';
import { nativeSupabase } from './platform/supabase.js';
import { loadNativeFriendsSnapshot, loadNativeSocialInboxCounts } from './platform/social.js';
import { saveNativeActiveStory } from './platform/path-state.js';
import { setNativeSessionNamespace } from './platform/session-store.js';
import { hasCompletedNativeAuthChoice, loadNativeFavorites, loadNativeSettings, loadNativeSongFavorites, markNativeAuthChoiceComplete, saveNativeFavorites, saveNativeSettings, saveNativeSongFavorites } from './platform/storage.js';

const C=theme.colors;
function BootScreen(){return <View style={styles.boot}><Text style={styles.bootBrand}>Alan Til</Text><View style={styles.bootDot}/></View>;}
function AshykGlobalPrompt({language,invite,resumeRoom,busy,onAccept,onDecline,onResume}){if(!invite&&!resumeRoom)return null;const t=(key,p)=>socialMessage(language,key,p),message=invite?t('challengeFrom',{name:invite.nickname||'—'}):t('unfinishedGame');return <View style={styles.ashykPromptBackdrop}><View style={styles.ashykPromptCard}><Text style={styles.ashykPromptTitle}>Ашыкъ оюн</Text><Text style={styles.ashykPromptText}>{message}</Text><View style={styles.ashykPromptActions}>{invite?<Pressable disabled={busy} onPress={onDecline} style={({pressed})=>[styles.ashykPromptButton,pressed&&styles.ashykPromptPressed,busy&&styles.ashykPromptDisabled]}><Text style={styles.ashykPromptButtonText}>{t('decline')}</Text></Pressable>:null}<Pressable disabled={busy} onPress={invite?onAccept:onResume} style={({pressed})=>[styles.ashykPromptButton,styles.ashykPromptPrimary,pressed&&styles.ashykPromptPressed,busy&&styles.ashykPromptDisabled]}><Text style={[styles.ashykPromptButtonText,styles.ashykPromptPrimaryText]}>{invite?t('accept'):t('returnToGame')}</Text></Pressable></View></View></View>;}
function settledValue(result,fallback){return result?.status==='fulfilled'?result.value:fallback;}
export default function AppRoot(){
  const [bootstrapped,setBootstrapped]=useState(false),[setupRequired,setSetupRequired]=useState(false),[authChoiceRequired,setAuthChoiceRequired]=useState(false),[words,setWords]=useState([]),[tab,setTab]=useState('path'),[screen,setScreen]=useState('home'),[favorites,setFavoritesState]=useState(()=>new Set()),[songFavorites,setSongFavoritesState]=useState(()=>new Set()),[settings,setSettingsState]=useState(()=>({...DEFAULT_USER_SETTINGS})),[station,setStation]=useState(null),[storyWordListType,setStoryWordListType]=useState(''),[learnContext,setLearnContext]=useState(null),[testContext,setTestContext]=useState(null),[practiceGameContext,setPracticeGameContext]=useState(null),[profileBottomNavVisible,setProfileBottomNavVisible]=useState(true),[dataEpoch,setDataEpoch]=useState(0),[authUserKey,setAuthUserKey]=useState(''),[socialBadge,setSocialBadge]=useState(0),[incomingAshykRoom,setIncomingAshykRoom]=useState(null),[communityMode,setCommunityMode]=useState('rating'),[communityUser,setCommunityUser]=useState(null),[globalAshykInvite,setGlobalAshykInvite]=useState(null),[resumeAshykRoom,setResumeAshykRoom]=useState(null),[ashykPromptBusy,setAshykPromptBusy]=useState(false);const displayWords=useMemo(()=>getDisplayedWordCollection(words,settings),[words,settings]),route=useMemo(()=>buildLearningRoute(displayWords),[displayWords]),authTransition=useRef(0),authUserId=useRef('');
  const hydrateScopedState=async()=>{const results=await Promise.allSettled([loadNativeSettings(),loadNativeFavorites(),loadNativeSongFavorites()]),savedSettings=settledValue(results[0],{...DEFAULT_USER_SETTINGS}),savedFavorites=settledValue(results[1],new Set()),savedSongFavorites=settledValue(results[2],new Set());setSettingsState(savedSettings||{...DEFAULT_USER_SETTINGS});setFavoritesState(savedFavorites instanceof Set?new Set(savedFavorites):new Set(savedFavorites||[]));setSongFavoritesState(savedSongFavorites instanceof Set?new Set(savedSongFavorites):new Set(savedSongFavorites||[]));setDataEpoch(value=>value+1);return savedSettings||{...DEFAULT_USER_SETTINGS};};
  const applyAuthTransition=async(session)=>{const nextUserId=String(session?.user?.id||'');if(nextUserId===authUserId.current)return;authUserId.current=nextUserId;setAuthUserKey(nextUserId);setSocialBadge(0);setIncomingAshykRoom(null);setCommunityMode('rating');setCommunityUser(null);const transition=++authTransition.current;if(session?.user){await synchronizeNativeAccount().catch(()=>false);}const scopedSettings=await hydrateScopedState();if(transition!==authTransition.current)return;const needsSetup=!session?.user&&!hasCompletedLearningSetup(scopedSettings),authChoiceDone=session?.user?true:Boolean(await hasCompletedNativeAuthChoice().catch(()=>false));if(session?.user)await markNativeAuthChoiceComplete().catch(()=>{});setSetupRequired(needsSetup);setAuthChoiceRequired(!session?.user&&!needsSetup&&!authChoiceDone);setTab('path');setScreen('home');setStation(null);setStoryWordListType('');setPracticeGameContext(null);};
  useEffect(()=>{let alive=true,unsubscribe=()=>{};(async()=>{try{const session=await bootstrapNativeAuth().catch(()=>null);authUserId.current=String(session?.user?.id||'');setAuthUserKey(authUserId.current);if(session?.user)await synchronizeNativeAccount().catch(()=>false);const bootstrapResults=await Promise.allSettled([Promise.allSettled([loadNativeSettings(),loadNativeFavorites(),loadNativeSongFavorites()]),bootstrapNativeDictionary(),hasCompletedNativeAuthChoice()]);const scopedResults=settledValue(bootstrapResults[0],[]),dictionaryResult=settledValue(bootstrapResults[1],null),authChoiceResult=Boolean(settledValue(bootstrapResults[2],false));if(!alive)return;const savedSettings=settledValue(scopedResults[0],{...DEFAULT_USER_SETTINGS}),savedFavorites=settledValue(scopedResults[1],new Set()),savedSongFavorites=settledValue(scopedResults[2],new Set()),needsSetup=!session?.user&&!hasCompletedLearningSetup(savedSettings||DEFAULT_USER_SETTINGS);setSettingsState(savedSettings||{...DEFAULT_USER_SETTINGS});setFavoritesState(savedFavorites instanceof Set?new Set(savedFavorites):new Set(savedFavorites||[]));setSongFavoritesState(savedSongFavorites instanceof Set?new Set(savedSongFavorites):new Set(savedSongFavorites||[]));setWords(Array.isArray(dictionaryResult?.words)?dictionaryResult.words:[]);setSetupRequired(needsSetup);setAuthChoiceRequired(!session?.user&&!needsSetup&&!authChoiceResult);setDataEpoch(1);setBootstrapped(true);void trackNativeEvent(EVENTS.APP_OPEN,{surface:'mobile'});}catch{if(!alive)return;setSettingsState({...DEFAULT_USER_SETTINGS});setFavoritesState(new Set());setSongFavoritesState(new Set());setWords([]);setSetupRequired(true);setAuthChoiceRequired(false);setBootstrapped(true);}unsubscribe=subscribeNativeAuth((session)=>{if(!alive)return;void applyAuthTransition(session||null);});})();return()=>{alive=false;authTransition.current+=1;unsubscribe();};},[]);
  useEffect(()=>{if(!bootstrapped||!authUserKey){setSocialBadge(0);return undefined;}let dead=false,timer=null;const refresh=async()=>{try{const counts=await loadNativeSocialInboxCounts();if(!dead)setSocialBadge(counts.total);}catch{if(!dead)setSocialBadge(0);}};const schedule=()=>{clearTimeout(timer);timer=setTimeout(()=>void refresh(),120);};const channel=nativeSupabase.channel(`social-root:${authUserKey}:${Date.now()}`).on('postgres_changes',{event:'*',schema:'public',table:'friendships'},schedule).on('postgres_changes',{event:'*',schema:'public',table:'ashyk_invites'},schedule).subscribe();void refresh();return()=>{dead=true;clearTimeout(timer);try{channel.unsubscribe();}catch{}try{void nativeSupabase.removeChannel(channel);}catch{}};},[bootstrapped,authUserKey]);
  useEffect(()=>{if(!bootstrapped||!authUserKey){setGlobalAshykInvite(null);setResumeAshykRoom(null);return undefined;}const online=createAshykOnlineAdapter(nativeSupabase);let dead=false,timer=null;const inGame=tab==='practice'&&screen==='ashyk';const refresh=async()=>{if(dead)return;try{const [snapshot,activeRoom]=await Promise.all([loadNativeFriendsSnapshot(),online.getActiveRoom()]);if(dead)return;if(inGame){setGlobalAshykInvite(null);setResumeAshykRoom(null);return;}const invite=Array.isArray(snapshot?.ashyk_invites)?snapshot.ashyk_invites[0]||null:null;setGlobalAshykInvite(invite);setResumeAshykRoom(!invite&&activeRoom&&['waiting','preparing','playing'].includes(activeRoom.status)?activeRoom:null);}catch{if(!dead&&!inGame){setGlobalAshykInvite(null);setResumeAshykRoom(null);}}};const schedule=()=>{clearTimeout(timer);timer=setTimeout(()=>void refresh(),120);};const channel=nativeSupabase.channel(`ashyk-root:${authUserKey}:${Date.now()}`).on('postgres_changes',{event:'*',schema:'public',table:'ashyk_invites'},schedule).on('postgres_changes',{event:'*',schema:'public',table:'ashyk_rooms'},schedule).subscribe(status=>{if(status==='SUBSCRIBED')void refresh();});void refresh();const poll=globalThis.setInterval(()=>void refresh(),12000);return()=>{dead=true;clearTimeout(timer);globalThis.clearInterval(poll);try{channel.unsubscribe();}catch{}try{void nativeSupabase.removeChannel(channel);}catch{}};},[bootstrapped,authUserKey,tab,screen]);
  useEffect(()=>{if(!bootstrapped)return;const name=setupRequired?'onboarding':authChoiceRequired?'auth_choice':tab==='path'?(screen==='home'?'path':screen):tab==='practice'?(screen==='home'?'practice':screen):tab==='friends'?'friends':screen==='home'?'profile':`profile_${screen}`;void trackNativeScreen(name,{tab,screen,interface_language:settings?.interface_language_code||'ru'});},[bootstrapped,setupRequired,authChoiceRequired,tab,screen]);
  const setFavorites=(next)=>{const value=next instanceof Set?next:new Set(next||[]);setFavoritesState(new Set(value));saveNativeFavorites(value).catch(()=>{});};const setSongFavorites=(next)=>{const value=next instanceof Set?next:new Set(next||[]);setSongFavoritesState(new Set(value));saveNativeSongFavorites(value).catch(()=>{});};const setSettings=async(next)=>{const saved=await saveNativeSettings(next);setSettingsState(saved);return saved;};
  const changeTab=(next)=>{setTab(next);setScreen('home');setStation(null);setStoryWordListType('');setPracticeGameContext(null);setProfileBottomNavVisible(true);if(next!=='practice')setIncomingAshykRoom(null);};const openStation=(nextStation)=>{setStation(nextStation);setScreen('station');};const backToPath=()=>{setScreen('home');setStation(null);};const openStoryWordList=(storyType)=>{setStoryWordListType(storyType);setScreen('storyWords');};const closeStoryWordList=()=>{setScreen('home');setStoryWordListType('');};const continueAsGuest=()=>{setTab('path');setScreen('home');setStation(null);};const completeAuthChoiceAsGuest=async()=>{await markNativeAuthChoiceComplete();setAuthChoiceRequired(false);continueAsGuest();};const completeAuthChoiceAsAccount=async()=>{await markNativeAuthChoiceComplete().catch(()=>{});};const openProfileStory=async(storyType)=>{if(!route.stories?.[storyType])return;await saveNativeActiveStory(storyType);setTab('path');setScreen('home');setStation(null);setStoryWordListType('');};
  const openPracticeGame=(type,sourceWords=displayWords,returnTo='home',scopeId='all')=>{setNativeSessionNamespace(type,scopeId);setPracticeGameContext({words:Array.isArray(sourceWords)?sourceWords:[],returnTo,scopeId});setScreen(type);};const closePracticeGame=()=>{const returnTo=practiceGameContext?.returnTo||'home';setPracticeGameContext(null);setScreen(returnTo);};
  const openAshykRoom=(room)=>{if(!room)return;setGlobalAshykInvite(null);setResumeAshykRoom(null);setIncomingAshykRoom(room);setTab('practice');setScreen('ashyk');};const acceptGlobalAshyk=async()=>{const invite=globalAshykInvite;if(!invite?.invite_id||ashykPromptBusy)return;setAshykPromptBusy(true);try{const online=createAshykOnlineAdapter(nativeSupabase),result=await online.acceptInvite(invite.invite_id);if(result?.room)openAshykRoom(result.room);}finally{setAshykPromptBusy(false);}};const declineGlobalAshyk=async()=>{const invite=globalAshykInvite;if(!invite?.invite_id||ashykPromptBusy)return;setAshykPromptBusy(true);try{const online=createAshykOnlineAdapter(nativeSupabase);await online.declineInvite(invite.invite_id);setGlobalAshykInvite(null);}finally{setAshykPromptBusy(false);}};const resumeGlobalAshyk=()=>openAshykRoom(resumeAshykRoom);
  const language=settings?.interface_language_code||'ru',navLabels={practice:msg(settings,'nav.praktika'),path:msg(settings,'nav.put'),friends:socialMessage(language,'community'),profile:msg(settings,'nav.profil')};
  const shell=(content,showNav=true)=><RuntimeSettingsProvider settings={settings}><SafeAreaProvider><StatusBar style="dark"/><SafeAreaView style={styles.safe} edges={theme.safeArea.shellEdges}><View style={styles.app}>{content}{showNav?<SocialBottomNav tab={tab} onChange={changeTab} labels={navLabels} badge={socialBadge}/>:null}<AshykGlobalPrompt language={language} invite={globalAshykInvite} resumeRoom={resumeAshykRoom} busy={ashykPromptBusy} onAccept={()=>void acceptGlobalAshyk()} onDecline={()=>void declineGlobalAshyk()} onResume={resumeGlobalAshyk}/></View></SafeAreaView></SafeAreaProvider></RuntimeSettingsProvider>;
  if(!bootstrapped)return shell(<BootScreen/>,false);
  if(setupRequired)return shell(<OnboardingScreen initialSettings={settings} onComplete={async(nextSettings)=>{const saved=await setSettings(nextSettings);if(!hasCompletedLearningSetup(saved))throw new Error('Learning setup was not persisted');setSetupRequired(false);setAuthChoiceRequired(true);}}/>,false);
  if(authChoiceRequired)return shell(<AuthChoiceScreen settings={settings} onAuthenticated={completeAuthChoiceAsAccount} onGuest={completeAuthChoiceAsGuest}/>,false);
  let content;let showNav=true;
  if(screen==='learn'&&learnContext){content=<LearnScreen words={learnContext.words} mode={learnContext.mode} station={learnContext.station} settings={settings} favorites={favorites} setFavorites={setFavorites} onBack={()=>setScreen(learnContext.returnTo||'station')}/>;showNav=false;}
  else if(screen==='stationTest'&&testContext){content=<StationTestScreen station={testContext.station} allWords={displayWords} mode={testContext.mode} settings={settings} favorites={favorites} setFavorites={setFavorites} onBack={()=>setScreen('station')}/>;showNav=false;}
  else if(tab==='path'&&screen==='storyWords'&&route.stories?.[storyWordListType]){content=<StoryWordListScreen story={route.stories[storyWordListType]} settings={settings} favorites={favorites} setFavorites={setFavorites} onBack={closeStoryWordList}/>;showNav=false;}
  else if(tab==='path'&&screen==='station'&&station){content=<StationScreen station={station} settings={settings} favorites={favorites} setFavorites={setFavorites} onBack={backToPath} onLearn={(rows,mode)=>{setLearnContext({words:rows,mode,station,returnTo:'station'});setScreen('learn');}} onTest={(target,mode)=>{setTestContext({station:target,mode});setScreen('stationTest');}}/>;showNav=false;}
  else if(tab==='practice'&&screen==='test'){const context=practiceGameContext||{words:displayWords,scopeId:'all'};content=<GeneralTestFlow words={context.words} settings={settings} favorites={favorites} setFavorites={setFavorites} onBack={closePracticeGame}/>;showNav=false;}
  else if(tab==='practice'&&screen==='match'){const context=practiceGameContext||{words:displayWords,scopeId:'all'};content=<GeneralMatchFlow words={context.words} settings={settings} favorites={favorites} setFavorites={setFavorites} onBack={closePracticeGame}/>;showNav=false;}
  else if(tab==='practice'&&screen==='favorites'){content=<FavoritesScreen words={displayWords} settings={settings} favorites={favorites} setFavorites={setFavorites} onBack={()=>setScreen('home')} onLearn={(rows,mode)=>{setLearnContext({words:rows,mode,station:null,returnTo:'favorites'});setScreen('learn');}}/>;showNav=false;}
  else if(tab==='practice'&&screen==='songs'){content=<SongsScreen words={displayWords} settings={settings} onBack={()=>setScreen('home')} favoriteIds={songFavorites} onFavorite={(id)=>setSongFavorites(toggleFavorite(songFavorites,id).ids)}/>;showNav=false;}
  else if(tab==='practice'&&screen==='ashyk'){content=<AshykScreen locale={settings.interface_language_code} words={words} userId={authUserKey} supabaseClient={nativeSupabase} initialRoom={incomingAshykRoom} onBack={()=>{setIncomingAshykRoom(null);setScreen('home');}} onSignIn={()=>{setIncomingAshykRoom(null);setTab('profile');setScreen('account');}}/>;showNav=false;}
  else if(tab==='practice'){content=<PracticeScreen settings={settings} openTest={()=>openPracticeGame('test',displayWords,'home','all')} openMatch={()=>openPracticeGame('match',displayWords,'home','all')} openFavorites={()=>setScreen('favorites')} openSongs={()=>setScreen('songs')} openAshyk={()=>{setIncomingAshykRoom(null);setScreen('ashyk');}}/>;}
  else if(tab==='friends'&&screen==='adminUser'&&communityUser){content=<AdminUserDetailScreen settings={settings} actorId={authUserKey} user={communityUser} onBack={()=>setScreen('home')}/>;showNav=false;}
  else if(tab==='friends'){content=<FriendsScreen settings={settings} userId={authUserKey} mode={communityMode} onModeChange={setCommunityMode} onSignIn={()=>{setTab('profile');setScreen('account');}} onOpenAshyk={openAshykRoom} onOpenStatsUser={(user)=>{setCommunityMode('stats');setCommunityUser(user);setScreen('adminUser');}}/>;}
  else if(tab==='profile'&&screen==='account'){content=<AccountScreen settings={settings} onGuest={continueAsGuest} onBack={()=>setScreen('home')}/>;showNav=false;}
  else if(tab==='profile'){content=<ProfileGate key={`profile-${dataEpoch}`} words={displayWords} settings={settings} onSettingsChange={setSettings} onGuest={continueAsGuest} onOpenStory={openProfileStory} onBottomNavVisibilityChange={setProfileBottomNavVisible} onAccount={(action)=>{if(action==='open')setScreen('account');}}/>;showNav=profileBottomNavVisible;}
  else{content=<PathScreen key={`path-${dataEpoch}`} route={route} settings={settings} onOpenStation={openStation} onOpenWordList={openStoryWordList}/>;}
  return shell(content,showNav);
}
const styles=StyleSheet.create({safe:{flex:1,backgroundColor:C.appBg},app:{flex:1,backgroundColor:C.appBg,overflow:'hidden'},boot:{flex:1,alignItems:'center',justifyContent:'center',backgroundColor:C.appBg},bootBrand:{fontSize:30,fontWeight:'900',color:C.text1},bootDot:{width:7,height:7,borderRadius:4,backgroundColor:C.accent,marginTop:18},ashykPromptBackdrop:{...StyleSheet.absoluteFillObject,zIndex:100,elevation:100,backgroundColor:'rgba(31,30,26,.48)',alignItems:'center',justifyContent:'center',paddingHorizontal:18},ashykPromptCard:{width:'100%',maxWidth:380,padding:18,borderWidth:1,borderColor:C.lineStrong,borderRadius:16,backgroundColor:C.surface0,gap:12},ashykPromptTitle:{fontSize:20,lineHeight:24,fontWeight:'900',color:C.text1,textAlign:'center'},ashykPromptText:{fontSize:14,lineHeight:20,color:C.text2,textAlign:'center'},ashykPromptActions:{flexDirection:'row',gap:8},ashykPromptButton:{flex:1,minHeight:44,borderWidth:1,borderColor:C.lineStrong,borderRadius:12,alignItems:'center',justifyContent:'center',paddingHorizontal:10,backgroundColor:C.surface0},ashykPromptPrimary:{backgroundColor:C.accent,borderColor:C.accentStrong},ashykPromptButtonText:{fontSize:13,fontWeight:'800',color:C.text1},ashykPromptPrimaryText:{color:C.inverse},ashykPromptPressed:{opacity:.78,transform:[{scale:.98}]},ashykPromptDisabled:{opacity:.55}});
