import test from'node:test';
import assert from'node:assert/strict';
import fs from'node:fs';
import path from'node:path';
import{fileURLToPath}from'node:url';
const ROOT=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
const read=p=>fs.readFileSync(path.join(ROOT,p),'utf8');

test('Ashyk setup mirrors Web ordering buttons and room-code contract',()=>{const screen=read('mobile/screens/ashyk.js');const shot=screen.indexOf('<FactRow label={m.shotTime}'),answer=screen.indexOf('<FactRow label={m.answerTime}'),accuracy=screen.indexOf('<FactRow label={m.computerAccuracy}'),computerAnswers=screen.indexOf('<FactRow label={m.computerAnswers}');assert.ok(shot>=0&&shot<answer&&answer<accuracy&&accuracy<computerAnswers);assert.match(screen,/state\.gameMode==='computer'\?<><FactRow label=\{m\.computerAccuracy\}/);assert.match(screen,/maxLength=\{6\}/);assert.match(screen,/replace\(\/\[\^A-F0-9\]\/g,''\)/);assert.match(screen,/roomCode\.length!==6/);assert.match(screen,/borderRadius:14/);assert.doesNotMatch(screen,/CutCornerFrame/);assert.match(screen,/m\.newGame/);});

test('Ashyk HUD question result and waiting room follow Web presentation',()=>{const screen=read('mobile/screens/ashyk.js');assert.match(screen,/scoreSideActive/);assert.match(screen,/faceValue\(state\.selectedFace\)/);assert.match(screen,/function outcomeText/);for(const token of['miss','faceMismatch','thirdTouched','correct','wrong','timeout','capture'])assert.match(screen,new RegExp(`outcome\\.code==='${token}'`));assert.match(screen,/m\.bonusQuestion/);assert.match(screen,/m\.translate/);assert.match(screen,/blocked\?'…':state\.questionSeconds/);assert.match(screen,/state\.onlineRoom\?\.status==='waiting'/);assert.match(screen,/styles\.waitingWrap/);assert.doesNotMatch(screen,/if\(state\.gameMode==='online'.*status==='waiting'\)return/s);});

test('Ashyk dialogs and UI actions retain audible feedback',()=>{const screen=read('mobile/screens/ashyk.js');assert.match(screen,/function DialogHeader/);assert.match(screen,/function MenuDialog/);assert.match(screen,/function AppearanceDialog/);assert.match(screen,/RulesDialog visible=\{help\}.*audio=\{audio\}/s);assert.match(screen,/createRoom=async\(\)=>\{[^}]*audio\.playUiClick\(\)/);assert.match(screen,/joinRoom=async\(\)=>\{[^}]*audio\.playUiClick\(\)/);assert.match(screen,/store\.submitAnswer\(option\.id\)/);assert.match(screen,/store\.skipQuestion\(\)/);assert.ok((screen.match(/audio\.playUiClick\(\)/g)||[]).length>=12);});

test('Native 3D board geometry camera and gestures mirror Web scene',()=>{const scene=read('mobile/game/ashyk-scene.js');assert.match(scene,/CylinderGeometry\(HALF,HALF,\.5,96\)/);assert.match(scene,/CircleGeometry\(HALF-\.95\*BOARD_SCALE,96\)/);assert.match(scene,/RingGeometry\(10\.7\*BOARD_SCALE,11\.2\*BOARD_SCALE,120\)/);assert.match(scene,/LatheGeometry\(rimProfile,144\)/);assert.match(scene,/RingGeometry\(\.92,1\.31,64\)/);assert.match(scene,/SphereGeometry\(\.14,12,8\)/);assert.match(scene,/shadow\.mapSize\.set\(1024,1024\)/);assert.match(scene,/renderOrder=12/);assert.match(scene,/touchDistance/);assert.match(scene,/startCameraDistance/);assert.match(scene,/stepX=x-touch\.lastX/);assert.doesNotMatch(scene,/gesture\.dx|gesture\.dy/);assert.match(scene,/clamp\(rt\.pinch\.startCameraDistance\*rt\.pinch\.startDistance\/current,20,max\)/);});

test('Native Ashyk audio uses the Web mix profile and expanded voice pools',()=>{const audio=read('mobile/game/ashyk-audio.js');assert.match(audio,/MASTER_GAIN=\.9/);assert.match(audio,/cooldownMs:32,gain:\.98/);assert.match(audio,/cooldownMs:36,gain:\.84/);assert.match(audio,/cooldownMs:40,gain:\.88/);assert.match(audio,/horn:createPool\(SOURCES\.horn,10\)/);assert.match(audio,/clack:createPool\(SOURCES\.clack,6\)/);assert.match(audio,/wood:createPool\(SOURCES\.wood,6\)/);assert.match(audio,/clamp\(172-motion\*22,52,155\)/);assert.match(audio,/\.9,1\.12/);});

test('Practice icon branding and release metadata are aligned with Alan Til',()=>{const practice=read('mobile/screens/practice.js'),app=read('mobile/AppRoot.js'),config=JSON.parse(read('mobile/app.json')),pkg=JSON.parse(read('mobile/package.json'));assert.doesNotMatch(practice,/PracticeIcon/);assert.match(practice,/title=\{ashyk\.title\} leading=\{<PuzzleIcon/);assert.match(app,/>Alan Til<\/Text>/);assert.equal(config.expo.name,'Alan Til');assert.equal(config.expo.version,'16.6.13');assert.equal(config.expo.extra.releaseVersion,'16.6.13');assert.equal(pkg.version,'16.6.13');});

test('Shared engine and store remain the sole game mechanics',()=>{const screen=read('mobile/screens/ashyk.js'),scene=read('mobile/game/ashyk-scene.js'),engine=read('packages/ashyk-game/engine.js'),store=read('packages/ashyk-game/store.js');assert.match(screen,/createAshykEngine/);assert.match(screen,/createAshykGameStore/);assert.match(scene,/engine\.preview/);assert.match(scene,/engine\.launch/);assert.match(engine,/evaluateCapture/);assert.match(engine,/planComputerShot/);assert.match(store,/DIFFICULTIES/);assert.doesNotMatch(screen,/function evaluateCapture|function planComputerShot|FACE_DEFS\s*=/);});
