import test from 'node:test';
import assert from 'node:assert/strict';
import {createAshykOnlineAdapter} from '../packages/ashyk-game/online.js';
import {createAshykOnlineSessionController} from '../packages/ashyk-game/session.js';
import {createAshykGameStore} from '../packages/ashyk-game/store.js';
const room=(extra={})=>({id:'r',status:'waiting',revision:1,phase_seq:0,host_user_id:'h',guest_user_id:'g',active_user_id:'h',game_state:{scores:[0,0]},...extra});
function clock(){let id=0;const jobs=new Map();return{setTimer(fn){jobs.set(++id,fn);return id;},clearTimer(id){jobs.delete(id);},async next(){const entry=jobs.entries().next().value;assert.ok(entry,'scheduled retry');jobs.delete(entry[0]);await entry[1]();await Promise.resolve();},get size(){return jobs.size;}};}
function client(){const channels=[];return{channels,rpc:async()=>({data:room()}),realtime:{async setAuth(){}},channel(name){const ch={name,on(){return this;},subscribe(fn){this.status=fn;return this;},unsubscribe(){this.status?.('CLOSED');},send:async()=> 'ok'};channels.push(ch);return ch;},async removeChannel(ch){ch.unsubscribe();}};}
test('waiting is not a locally playing game',()=>{const store=createAshykGameStore({setRepeater:null});store.hydrateOnline(room(),'h');assert.equal(store.getState().status,'waiting');assert.equal(store.getState().shotSeconds,0);store.destroy();});
test('visual channel is never opened in waiting and attaches on playing',()=>{let current=room(),opens=0,closes=0;const session=createAshykOnlineSessionController({online:{openVisualStream(){opens++;return{close(){closes++;}};}},engine:{},getRoom:()=>current});assert.equal(session.attachVisual('r'),false);assert.equal(opens,0);current=room({status:'playing'});session.attachVisual('r');assert.equal(opens,1);session.attachVisual('r');assert.equal(opens,1);session.destroy();assert.equal(closes,1);});
test('room subscription recreates failed channel and disposal prevents resurrection',async()=>{const c=client(),timer=clock(),adapter=createAshykOnlineAdapter(c,timer);const stop=adapter.subscribeRoom('r',()=>{});c.channels[0].status('CHANNEL_ERROR');await timer.next();assert.equal(c.channels.length,2);c.channels[1].status('TIMED_OUT');stop();assert.equal(timer.size,0);});
test('private Broadcast reconnects after failure and preserves queued trajectory',async()=>{const c=client(),timer=clock(),adapter=createAshykOnlineAdapter(c,timer),stream=adapter.openVisualStream('r',()=>{});await stream.ready;c.channels[0].status('CHANNEL_ERROR');stream.send('shot-trajectory',{shotId:'s'});await timer.next();await Promise.resolve();assert.equal(c.channels.length,2);let delivered;c.channels[1].send=async packet=>{delivered=packet;return 'ok';};c.channels[1].status('SUBSCRIBED');assert.equal(delivered.payload.shotId,'s');stream.close();assert.equal(timer.size,0);});
test('two clients converge after lost first ready RPC and all Realtime events',async()=>{const {startRoomReconciliation}=await import('../packages/ashyk-game/reconciliation.js');let server=room(),lost=true;const ready=new Set(),clients=[];for(const user of ['h','g']){let local=room();const timer=clock(),stop=startRoomReconciliation({online:{async markReady(){if(user==='h'&&lost){lost=false;throw Error('lost');}ready.add(user);if(ready.size===2)server=room({status:'playing',revision:2,phase_seq:1});return structuredClone(server);},async pingRoom(){return structuredClone(server);},async getRoom(){return structuredClone(server);}},roomId:'r',getRoom:()=>local,applyRoom:r=>{local=r;},...timer});clients.push({timer,stop,get:()=>local});}await new Promise(resolve=>setImmediate(resolve));for(let n=0;n<3;n++)for(const c of clients)await c.timer.next();assert.ok(clients.every(c=>c.get().status==='playing'));clients.forEach(c=>c.stop());});
test('late responses cannot regress a room or re-open a disposed room',async()=>{const {shouldAcceptRoom,startRoomReconciliation}=await import('../packages/ashyk-game/reconciliation.js');assert.equal(shouldAcceptRoom(room({revision:3,status:'playing'}),room()),false);let resolve,applied=0;const timer=clock(),stop=startRoomReconciliation({online:{markReady:()=>new Promise(r=>{resolve=r;})},roomId:'r',getRoom:()=>room(),applyRoom:()=>applied++,...timer});stop();resolve(room());await new Promise(r=>setImmediate(r));assert.equal(applied,0);assert.equal(timer.size,0);});
test('ready waits for vocabulary but heartbeat still exposes the room',async()=>{const {startRoomReconciliation}=await import('../packages/ashyk-game/reconciliation.js');let readyCalls=0,pings=0,loaded=false;const timer=clock(),stop=startRoomReconciliation({online:{async markReady(){readyCalls++;return room();},async markNotReady(){pings++;return room();}},roomId:'r',getRoom:()=>room(),applyRoom:()=>{},canReady:()=>loaded,...timer});await new Promise(r=>setImmediate(r));assert.equal(readyCalls,0);assert.equal(pings,1);loaded=true;await timer.next();assert.equal(readyCalls,1);stop();});
test('operation lock blocks two clicks before the first await resolves',async()=>{const {createOperationLock}=await import('../packages/ashyk-game/reconciliation.js');const lock=createOperationLock();assert.equal(lock.acquire(),true);assert.equal(lock.acquire(),false);lock.release();assert.equal(lock.acquire(),true);});
test('lost invite creation response restores the room without a second invitation',async()=>{let creates=0;const c=client();c.rpc=async name=>{if(name==='ashyk_invite_create'){creates++;throw Error('response lost');}if(name==='ashyk_active_room')return{data:room()};throw Error(name);};const result=await createAshykOnlineAdapter(c).createFriendInvite('g',{});assert.equal(result.room.id,'r');assert.equal(creates,1);});
test('lost accept response restores the accepted room',async()=>{const c=client();c.rpc=async name=>{if(name==='ashyk_invite_accept')throw Error('response lost');return{data:room()};};assert.equal((await createAshykOnlineAdapter(c).acceptInvite('invite')).room.id,'r');});
test('build check never blocks action on the index request and reuses the response',async()=>{let resolve,calls=0,reloads=0;globalThis.window={location:{reload(){reloads++;}}};globalThis.document={querySelector:()=>({content:'old'})};const original=globalThis.fetch;globalThis.fetch=()=>{calls++;return new Promise(r=>resolve=r);};try{const {ensureCurrentAshykBuild}=await import('../src/shared/social/ashyk-handoff.js?recovery-test');const immediate=await Promise.race([ensureCurrentAshykBuild(),new Promise(r=>setTimeout(()=>r('blocked'),25))]);assert.equal(immediate,true);resolve({ok:true,text:async()=>'<meta name="alantil-build" content="new" />'});await new Promise(r=>setImmediate(r));assert.equal(await ensureCurrentAshykBuild({kind:'room',roomId:'r'}),false);assert.equal(calls,1);assert.equal(reloads,1);}finally{globalThis.fetch=original;delete globalThis.window;delete globalThis.document;}});
test('room screen mounts while full dictionary download is still pending',async()=>{const fs=await import('node:fs');let release,mounted=null;const pending=new Promise(r=>release=r);const source=fs.readFileSync(new URL('../src/features/ashyk/index.js',import.meta.url),'utf8').replace(/^import .*;\n/gm,'').replace(/export /g,'');const mocks={getCompleteDictionaryWords:()=>pending,refreshDictionary:async()=>({words:[]}),getCurrentAuthState:()=>({session:{user:{id:'h'}}}),getSupabaseClient:async()=>({}),getUserSettings:()=>({interface_language_code:'ru'}),msg:x=>x,primeAshykBuildCheck(){},takePendingAshykInvite:()=>null,takePendingAshykIntent:()=>null,createAshykOnlineAdapter:()=>({getActiveRoom:async()=>room()}),ashykAccessForUser:()=>({locked:false}),socialMessage:()=>'',createAshykQuestionDeck:()=>({size:1,next:()=>({})}),mountAshykGame:(host,options)=>{mounted=options;return()=>{};},ensureCurrentAshykBuild:async()=>true};const feature=Function(...Object.keys(mocks),source+'\nreturn {mount,unmount};')(...Object.values(mocks));const host={};await feature.mount({shell:{},root:{innerHTML:'',querySelector:()=>host}});assert.equal(mounted.initialRoom.id,'r');assert.ok(mounted.vocabularyTask);release([{id:'word'}]);assert.equal((await mounted.vocabularyTask).words.length,1);feature.unmount();});
test('initial field preparation yields in small batches and can be cancelled',async()=>{const {prepareInitialField}=await import('../packages/ashyk-game/reconciliation.js');let steps=0,ready=false,field=null;const stop=prepareInitialField({settleInitial(count){assert.ok(count<=20);steps++;ready=steps===2;},isReady:()=>ready,snapshot:()=>({pieces:[]})},value=>field=value);assert.equal(steps,0);await new Promise(r=>setTimeout(r,40));assert.deepEqual(field,{pieces:[]});stop();});
test('session recovery cannot resurrect room after destruction',async()=>{let resolve,applied=0;const session=createAshykOnlineSessionController({online:{getRoom:()=>new Promise(r=>resolve=r)},getRoom:()=>room(),applyRoom:()=>applied++});const recovery=session.recover('r');session.destroy();resolve(room());await recovery;assert.equal(applied,0);});
test('late timeout response cannot mutate a destroyed session',async()=>{let resolve,applied=0;let current=room({status:'playing',phase_deadline_at:'2000-01-01'});const session=createAshykOnlineSessionController({online:{resolveTimeout:()=>new Promise(r=>resolve=r)},getRoom:()=>current,applyRoom:()=>applied++});const pending=session.resolveTimeoutIfDue();session.destroy();current=null;resolve(room({status:'playing'}));await pending;assert.equal(applied,0);});
test('late action response cannot mutate a destroyed session',async()=>{let resolve,applied=0;let current=room({status:'playing'});const session=createAshykOnlineSessionController({online:{submitAction:()=>new Promise(r=>resolve=r)},store:{getState:()=>({status:'playing'}),onlineGameState:()=>({currentPlayer:2})},userId:'h',getRoom:()=>current,applyRoom:()=>applied++});session.enqueue({id:'a',type:'skip'});session.destroy();current=null;resolve(room({status:'playing',last_action_id:'a'}));await new Promise(r=>setImmediate(r));assert.equal(applied,0);});
