import test from'node:test';
import assert from'node:assert/strict';
import fs from'node:fs';
import path from'node:path';
import{fileURLToPath}from'node:url';
const ROOT=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
const read=p=>fs.readFileSync(path.join(ROOT,p),'utf8');

test('Ashyk friend setup mirrors Web player table and fixed online timing',()=>{const screen=read('mobile/screens/ashyk.js');const shot=screen.indexOf('<FactRow label={m.shotTime}'),answer=screen.indexOf('<FactRow label={m.answerTime}');assert.ok(shot>=0&&shot<answer);assert.match(screen,/ONLINE_RULES\.humanShotSeconds/);assert.match(screen,/ONLINE_RULES\.humanQuestionSeconds/);assert.match(screen,/state\.gameMode!=='online'/);assert.match(screen,/playerTable/);assert.match(screen,/matchScore/);assert.match(screen,/incomingChallenge/);assert.match(screen,/outgoingChallenge/);assert.match(screen,/waitingForYou/);assert.match(screen,/gameRunning/);assert.match(screen,/playerBusy/);assert.doesNotMatch(screen,/m\.mediumWords/);assert.doesNotMatch(screen,/roomCode|maxLength=\{6\}/);});
test('Ashyk HUD question result and waiting room follow Web presentation',()=>{const screen=read('mobile/screens/ashyk.js');assert.match(screen,/scoreSideActive/);assert.match(screen,/faceValue\(state\.selectedFace\)/);assert.match(screen,/function outcomeText/);for(const token of['miss','faceMismatch','thirdTouched','correct','wrong','timeout','capture'])assert.match(screen,new RegExp(`outcome\\.code==='${token}'`));assert.match(screen,/m\.bonusQuestion/);assert.match(screen,/m\.translate/);assert.match(screen,/blocked\?'…':state\.questionSeconds/);assert.match(screen,/roomMeta\?\.status==='waiting'/);assert.match(screen,/styles\.waitingWrap/);assert.doesNotMatch(screen,/if\(state\.gameMode==='online'.*status==='waiting'\)return/s);});

test('Ashyk dialogs and player actions retain audible feedback',()=>{const screen=read('mobile/screens/ashyk.js');assert.match(screen,/function DialogHeader/);assert.match(screen,/function MenuDialog/);assert.match(screen,/function AppearanceDialog/);assert.match(screen,/RulesDialog visible=\{help\}.*audio=\{audio\}/s);for(const action of['challenge','accept','decline','cancel','resume'])assert.match(screen,new RegExp(`const ${action}=async`));assert.match(screen,/store\.submitAnswer\(selectedId\)/);assert.match(screen,/store\.skipQuestion\(\)/);assert.ok((screen.match(/audio\.playUiClick\(\)/g)||[]).length>=12);});
test('Native 3D wooden board camera and gestures mirror Web scene',()=>{const scene=read('mobile/game/ashyk-scene.js'),wood=read('packages/ashyk-game/model/wood-board.js');assert.ok(scene.includes('createAshykBoardVisual(THREE,{textures:woodTextures})'));assert.match(scene,/disposeAshykBoardVisual/);assert.doesNotMatch(scene,/#c8c9c5|rimProfile/);assert.match(scene,/Asset\.fromModule/);assert.match(scene,/Image\.getSize/);assert.match(scene,/new THREE\.DataTexture/);assert.match(scene,/loadNativeWoodPbrTextures/);assert.match(wood,/ASHYK_WOOD_PBR_ASSETS/);assert.match(wood,/TextureLoader/);assert.match(wood,/roughnessMap/);assert.match(wood,/normalMap/);assert.match(wood,/aoMap/);assert.doesNotMatch(wood,/createAshykWoodPbrTextures|woodHeight|function fbm/);assert.match(wood,/addGrooveRing/);assert.match(wood,/addRadialGrooves/);assert.ok(scene.includes('new THREE.RingGeometry(.92,1.31,64)'));assert.ok(scene.includes('new THREE.SphereGeometry(.14,12,8)'));assert.ok(scene.includes('sun.shadow.mapSize.set(1024,1024)'));assert.match(scene,/ACESFilmicToneMapping/);assert.match(scene,/renderOrder=12/);assert.match(scene,/touchDistance/);assert.match(scene,/startCameraDistance/);assert.ok(scene.includes('stepX=x-touch.lastX'));assert.doesNotMatch(scene,/gesture\.dx|gesture\.dy/);assert.ok(scene.includes('clamp(rt.pinch.startCameraDistance*rt.pinch.startDistance/current,20,max)'));});

test('Native Ashyk audio uses the Web mix profile and expanded voice pools',()=>{const audio=read('mobile/game/ashyk-audio.js');assert.match(audio,/MASTER_GAIN=\.9/);assert.match(audio,/cooldownMs:30,gain:\.98/);assert.match(audio,/cooldownMs:34,gain:\.84/);assert.match(audio,/cooldownMs:38,gain:\.88/);assert.match(audio,/horn:createPool\(SOURCES\.horn,10\)/);assert.match(audio,/clack:createPool\(SOURCES\.clack,6\)/);assert.match(audio,/wood:createPool\(SOURCES\.wood,6\)/);assert.match(audio,/clamp\(172-motion\*22,52,155\)/);assert.match(audio,/\.9,1\.12/);});

test('Practice icon branding and release metadata are aligned with Alan Til',()=>{const practice=read('mobile/screens/practice.js'),app=read('mobile/AppRoot.js'),config=JSON.parse(read('mobile/app.json')),pkg=JSON.parse(read('mobile/package.json'));assert.doesNotMatch(practice,/PracticeIcon/);assert.match(practice,/title=\{ashyk\.title\} leading=\{<PuzzleIcon/);assert.match(app,/>Alan Til<\/Text>/);assert.equal(config.expo.name,'Alan Til');assert.equal(config.expo.version,'16.8.0');assert.equal(config.expo.extra.releaseVersion,'16.8.0');assert.equal(pkg.version,'16.8.0');});

test('Shared engine and store remain the sole game mechanics',()=>{const screen=read('mobile/screens/ashyk.js'),scene=read('mobile/game/ashyk-scene.js'),engine=read('packages/ashyk-game/engine.js'),store=read('packages/ashyk-game/store.js');assert.match(screen,/createAshykEngine/);assert.match(screen,/createAshykGameStore/);assert.match(scene,/engine\.preview/);assert.match(scene,/engine\.launch/);assert.match(engine,/evaluateCapture/);assert.match(engine,/planComputerShot/);assert.match(store,/DIFFICULTIES/);assert.doesNotMatch(screen,/function evaluateCapture|function planComputerShot|FACE_DEFS\s*=/);});
