import React, { useEffect, useMemo, useRef, useState } from 'react';
import { Animated, Dimensions, Easing, Modal, Pressable, StyleSheet, Text, View } from 'react-native';
import { msg } from '../i18n.js';
import { theme } from './theme.js';
const C=theme.colors;

const WINDOW=Dimensions.get('window');
function clamp(value,min,max){return Math.max(min,Math.min(max,value));}
function normalizeRect(rect,padding=8){if(!rect)return null;return {x:Math.max(0,rect.x-padding),y:Math.max(0,rect.y-padding),width:Math.max(0,rect.width+padding*2),height:Math.max(0,rect.height+padding*2)};}
function measureTarget(targetRef){return new Promise((resolve)=>{const node=targetRef?.current;if(!node||typeof node.measureInWindow!=='function'){resolve(null);return;}requestAnimationFrame(()=>node.measureInWindow((x,y,width,height)=>resolve({x,y,width,height})));});}
function SpotlightMask({rect}){if(!rect)return <View pointerEvents="none" style={styles.fullShade}/>;const w=WINDOW.width,h=WINDOW.height,left=clamp(rect.x,0,w),top=clamp(rect.y,0,h),right=clamp(left+rect.width,0,w),bottom=clamp(top+rect.height,0,h);return <View pointerEvents="none" style={StyleSheet.absoluteFill}>{top>0?<View style={[styles.maskPiece,{left:0,top:0,right:0,height:top}]}/>:null}{bottom<h?<View style={[styles.maskPiece,{left:0,top:bottom,right:0,bottom:0}]}/>:null}{left>0?<View style={[styles.maskPiece,{left:0,top,width:left,height:Math.max(0,bottom-top)}]}/>:null}{right<w?<View style={[styles.maskPiece,{left:right,top,right:0,height:Math.max(0,bottom-top)}]}/>:null}</View>;}

export function GuideOverlay({visible,settings,step,onNext,onSkip,nextLabel='',showSkip=true,targetRef,targetRect,scrollToTarget,spotlightPadding=8}){
  const [rect,setRect]=useState(null);const halo=useRef(new Animated.Value(0)).current;
  useEffect(()=>{let alive=true;if(!visible||!step){setRect(null);return()=>{alive=false;};}(async()=>{try{if(typeof scrollToTarget==='function')await scrollToTarget(step);const measured=targetRect||await measureTarget(targetRef);if(alive)setRect(normalizeRect(measured,spotlightPadding));}catch{if(alive)setRect(null);}})();return()=>{alive=false;};},[visible,step,targetRef,targetRect,scrollToTarget,spotlightPadding]);
  useEffect(()=>{if(!visible||!rect){halo.stopAnimation();halo.setValue(0);return;}const loop=Animated.loop(Animated.sequence([Animated.timing(halo,{toValue:1,duration:780,easing:Easing.inOut(Easing.quad),useNativeDriver:true}),Animated.timing(halo,{toValue:0,duration:780,easing:Easing.inOut(Easing.quad),useNativeDriver:true})]));loop.start();return()=>loop.stop();},[visible,rect,halo]);
  const cardStyle=useMemo(()=>{if(!rect)return styles.panelCentered;const cardHeight=188,spaceBelow=WINDOW.height-(rect.y+rect.height),placeBelow=spaceBelow>=cardHeight+22;const top=placeBelow?Math.min(WINDOW.height-cardHeight-18,rect.y+rect.height+14):Math.max(18,rect.y-cardHeight-14);return {top,left:14,right:14};},[rect]);
  if(!visible||!step)return null;
  const haloScale=halo.interpolate({inputRange:[0,1],outputRange:[1,1.07]}),haloOpacity=halo.interpolate({inputRange:[0,1],outputRange:[.72,.28]});
  return <Modal visible transparent animationType="fade" onRequestClose={onSkip} statusBarTranslucent><View style={styles.root}><SpotlightMask rect={rect}/><Pressable accessibilityRole="none" style={StyleSheet.absoluteFill} onPress={()=>{}}>{null}</Pressable>{rect?<Animated.View pointerEvents="none" style={[styles.halo,{left:rect.x,top:rect.y,width:rect.width,height:rect.height,opacity:haloOpacity,transform:[{scale:haloScale}]}]}/>:null}<View accessibilityRole="alert" style={[styles.panel,cardStyle]}><Text style={styles.title}>{msg(settings,step.titleKey)}</Text><Text style={styles.body}>{msg(settings,step.bodyKey,{required:80})}</Text><View style={styles.nav}>{showSkip?<Pressable accessibilityRole="button" onPress={onSkip} style={styles.action}><Text style={styles.secondary}>{msg(settings,'guide.skip')}</Text></Pressable>:<View/>}<Pressable accessibilityRole="button" onPress={onNext} style={[styles.action,styles.primary]}><Text style={styles.primaryText}>{nextLabel||msg(settings,'guide.next')}</Text></Pressable></View></View></View></Modal>;
}
export function GuideHelpButton({onPress,label='?'}){return <Pressable accessibilityRole="button" accessibilityLabel="Guide" onPress={onPress} style={({pressed})=>[styles.help,pressed&&styles.pressed]}><Text style={styles.helpText}>{label}</Text></Pressable>;}
const styles=StyleSheet.create({root:{flex:1},fullShade:{...StyleSheet.absoluteFillObject,backgroundColor:'rgba(25,25,25,.60)'},maskPiece:{position:'absolute',backgroundColor:'rgba(25,25,25,.60)'},halo:{position:'absolute',zIndex:2,borderWidth:2,borderColor:C.accent,borderRadius:16,shadowColor:C.accent,shadowOpacity:.42,shadowRadius:18,shadowOffset:{width:0,height:0},elevation:8},panel:{position:'absolute',zIndex:3,maxWidth:380,alignSelf:'center',paddingHorizontal:16,paddingTop:15,paddingBottom:13,borderWidth:1,borderColor:C.line,borderRadius:theme.radius.lg,backgroundColor:C.surface0,shadowColor:C.modalShadow,shadowOpacity:.18,shadowRadius:26,shadowOffset:{width:0,height:10},elevation:12},panelCentered:{left:14,right:14,top:'34%'},title:{fontFamily:theme.font.terminal,fontSize:17,fontWeight:'900',lineHeight:21,color:C.text1},body:{marginTop:9,fontSize:13,lineHeight:19,color:C.text2},nav:{marginTop:13,flexDirection:'row',alignItems:'center',justifyContent:'space-between',gap:10},action:{minWidth:104,minHeight:36,alignItems:'center',justifyContent:'center',paddingHorizontal:12},primary:{borderWidth:1,borderColor:C.text1,backgroundColor:C.text1},secondary:{fontFamily:theme.font.terminal,fontSize:11,fontWeight:'800',color:C.text2},primaryText:{fontFamily:theme.font.terminal,fontSize:11,fontWeight:'800',color:C.inverse},help:{position:'absolute',zIndex:70,left:10,top:'80%',width:36,height:36,borderRadius:18,borderWidth:1,borderColor:C.line,alignItems:'center',justifyContent:'center',backgroundColor:C.glassStrong},helpText:{fontFamily:theme.font.terminal,fontSize:17,fontWeight:'850',color:C.text1},pressed:{opacity:.7,transform:[{scale:.97}]}});