import React,{useEffect,useMemo,useRef,useState}from'react';
import{Animated,Easing,Modal,Pressable,StyleSheet,Text,useWindowDimensions,View}from'react-native';
import Svg,{Defs,Mask,Rect}from'react-native-svg';
import{msg}from'../i18n.js';
import{theme}from'./theme.js';
const C=theme.colors;
function normalizeRect(rect,padding=8){if(!rect)return null;return{x:Math.max(0,rect.x-padding),y:Math.max(0,rect.y-padding),width:Math.max(0,rect.width+padding*2),height:Math.max(0,rect.height+padding*2)}}
function measureTarget(targetRef){return new Promise(resolve=>{const node=targetRef?.current;if(!node||typeof node.measureInWindow!=='function'){resolve(null);return}requestAnimationFrame(()=>node.measureInWindow((x,y,width,height)=>resolve({x,y,width,height})))})}
function cleanMarkup(value){return String(value||'').replace(/<br\s*\/?\s*>/gi,'\n').replace(/<\/p\s*>/gi,'\n\n').replace(/<p(?:\s[^>]*)?>/gi,'').replace(/<[^>]+>/g,'').replace(/&nbsp;/g,' ').replace(/&amp;/g,'&').replace(/&lt;/g,'<').replace(/&gt;/g,'>').replace(/&quot;/g,'"').replace(/&#39;/g,"'").replace(/\n{3,}/g,'\n\n').trim()}
function targetRadius(step,rect){const shape=step?.shape||step?.spotlightShape||'auto';if(shape==='pill')return Math.min(rect?.height||0,rect?.width||0)/2;if(shape==='rounded')return 16;return Math.min(18,Math.max(8,Math.min(rect?.height||0,rect?.width||0)*.18))}
function SpotlightMask({rect,radius,width,height}){if(!rect)return <View pointerEvents="none" style={styles.fullShade}/>;return <Svg pointerEvents="none" width={width} height={height} style={StyleSheet.absoluteFill}><Defs><Mask id="guideSpot"><Rect x="0" y="0" width={width} height={height} fill="white"/><Rect x={rect.x} y={rect.y} width={rect.width} height={rect.height} rx={radius} ry={radius} fill="black"/></Mask></Defs><Rect x="0" y="0" width={width} height={height} fill="rgba(25,25,25,.60)" mask="url(#guideSpot)"/></Svg>}
export function GuideOverlay({visible,settings,step,onNext,onSkip,nextLabel='',showSkip=true,targetRef,targetRect,scrollToTarget,spotlightPadding=8}){const{width,height}=useWindowDimensions(),[rect,setRect]=useState(null),[panelHeight,setPanelHeight]=useState(188),halo=useRef(new Animated.Value(0)).current;useEffect(()=>{let alive=true;if(!visible||!step){setRect(null);return()=>{alive=false}};(async()=>{try{if(typeof scrollToTarget==='function')await scrollToTarget(step);const measured=targetRect||await measureTarget(targetRef);if(alive)setRect(normalizeRect(measured,spotlightPadding))}catch{if(alive)setRect(null)}})();return()=>{alive=false}},[visible,step,targetRef,targetRect,scrollToTarget,spotlightPadding,width,height]);useEffect(()=>{if(!visible||!rect){halo.stopAnimation();halo.setValue(0);return}const loop=Animated.loop(Animated.sequence([Animated.timing(halo,{toValue:1,duration:780,easing:Easing.inOut(Easing.quad),useNativeDriver:true}),Animated.timing(halo,{toValue:0,duration:780,easing:Easing.inOut(Easing.quad),useNativeDriver:true})]));loop.start();return()=>loop.stop()},[visible,rect,halo]);const radius=targetRadius(step,rect),cardStyle=useMemo(()=>{if(!rect)return styles.panelCentered;const cardHeight=Math.max(120,panelHeight),spaceBelow=height-(rect.y+rect.height),below=spaceBelow>=cardHeight+22,top=below?Math.min(height-cardHeight-18,rect.y+rect.height+14):Math.max(18,rect.y-cardHeight-14);return{top,left:14,right:14}},[rect,panelHeight,height]);if(!visible||!step)return null;const haloScale=halo.interpolate({inputRange:[0,1],outputRange:[1,1.07]}),haloOpacity=halo.interpolate({inputRange:[0,1],outputRange:[.72,.28]});return <Modal visible transparent animationType="fade" onRequestClose={onSkip} statusBarTranslucent><View style={styles.root}><SpotlightMask rect={rect} radius={radius} width={width} height={height}/><Pressable accessibilityRole="none" style={StyleSheet.absoluteFill} onPress={()=>{}}/>{rect?<Animated.View pointerEvents="none" style={[styles.halo,{left:rect.x,top:rect.y,width:rect.width,height:rect.height,borderRadius:radius,opacity:haloOpacity,transform:[{scale:haloScale}]}]}/>:null}<View onLayout={event=>setPanelHeight(event.nativeEvent.layout.height||188)} accessibilityRole="alert" style={[styles.panel,cardStyle]}><Text style={styles.title}>{cleanMarkup(msg(settings,step.titleKey))}</Text><Text style={styles.body}>{cleanMarkup(msg(settings,step.bodyKey,{required:80}))}</Text><View style={styles.nav}>{showSkip?<Pressable accessibilityRole="button" onPress={onSkip} style={styles.action}><Text style={styles.secondary}>{msg(settings,'guide.skip')}</Text></Pressable>:<View/>}<Pressable accessibilityRole="button" onPress={onNext} style={[styles.action,styles.primary]}><Text style={styles.primaryText}>{nextLabel||msg(settings,'guide.next')}</Text></Pressable></View></View></View></Modal>}
export function GuideHelpButton({onPress,label='?'}){return <Pressable accessibilityRole="button" accessibilityLabel="Guide" onPress={onPress} style={({pressed})=>[styles.help,pressed&&styles.pressed]}><Text style={styles.helpText}>{label}</Text></Pressable>}
const styles=StyleSheet.create({root:{flex:1},fullShade:{...StyleSheet.absoluteFillObject,backgroundColor:'rgba(25,25,25,.60)'},halo:{position:'absolute',zIndex:2,borderWidth:2,borderColor:C.accent,shadowColor:C.accent,shadowOpacity:.42,shadowRadius:18,shadowOffset:{width:0,height:0},elevation:8},panel:{position:'absolute',zIndex:3,maxWidth:380,alignSelf:'center',paddingHorizontal:16,paddingTop:15,paddingBottom:13,borderWidth:1,borderColor:C.line,borderRadius:theme.radius.lg,backgroundColor:C.surface0,shadowColor:C.modalShadow,shadowOpacity:.18,shadowRadius:26,shadowOffset:{width:0,height:10},elevation:12},panelCentered:{left:14,right:14,top:'34%'},title:{fontFamily:theme.font.terminal,fontSize:17,fontWeight:'900',lineHeight:21,color:C.text1},body:{marginTop:9,fontSize:13,lineHeight:19,color:C.text2},nav:{marginTop:13,flexDirection:'row',alignItems:'center',justifyContent:'space-between',gap:10},action:{minWidth:104,minHeight:36,alignItems:'center',justifyContent:'center',paddingHorizontal:12},primary:{borderWidth:1,borderColor:C.text1,backgroundColor:C.text1},secondary:{fontFamily:theme.font.terminal,fontSize:11,fontWeight:'800',color:C.text2},primaryText:{fontFamily:theme.font.terminal,fontSize:11,fontWeight:'800',color:C.inverse},help:{position:'absolute',zIndex:70,left:10,top:'80%',width:36,height:36,borderRadius:18,borderWidth:1,borderColor:C.line,alignItems:'center',justifyContent:'center',backgroundColor:C.glassStrong},helpText:{fontFamily:theme.font.terminal,fontSize:17,fontWeight:'850',color:C.text1},pressed:{opacity:.7,transform:[{scale:.97}]}});