import React,{useEffect,useMemo,useRef,useState}from'react';
import{Animated,Easing,Modal,Pressable,StyleSheet,Text,useWindowDimensions,View}from'react-native';
import{useSafeAreaInsets}from'react-native-safe-area-context';
import Svg,{Defs,Mask,Rect}from'react-native-svg';
import{msg}from'../i18n.js';
import{GlassBackdrop}from'./components.js';
import{theme}from'./theme.js';

const C=theme.colors;
const GUIDE_SHADE='rgba(25,25,25,.54)';
const GUIDE_PANEL='rgba(246,242,233,.94)';
const GUIDE_HALO='rgba(255,255,255,.26)';
const GUIDE_HALO_SOFT='rgba(255,255,255,.10)';

function cleanMarkup(value){return String(value||'').replace(/<br\s*\/?\s*>/gi,'\n').replace(/<\/p\s*>/gi,'\n\n').replace(/<p(?:\s[^>]*)?>/gi,'').replace(/<[^>]+>/g,'').replace(/&nbsp;/g,' ').replace(/&amp;/g,'&').replace(/&lt;/g,'<').replace(/&gt;/g,'>').replace(/&quot;/g,'"').replace(/&#39;/g,"'").replace(/\n{3,}/g,'\n\n').trim();}
function measureTarget(targetRef){return new Promise(resolve=>{const node=targetRef?.current;if(!node||typeof node.measureInWindow!=='function'){resolve(null);return;}requestAnimationFrame(()=>node.measureInWindow((x,y,width,height)=>resolve(width>0&&height>0?{x,y,width,height}:null)));});}
function expandRect(rect,padding=8,minWidth=0,minHeight=0,shape='rounded'){if(!rect)return null;let width=Math.max(Number(minWidth)||0,rect.width+padding*2),height=Math.max(Number(minHeight)||0,rect.height+padding*2),x=rect.x-padding,y=rect.y-padding;if(shape==='circle'){const side=Math.max(width,height),cx=x+width/2,cy=y+height/2;width=side;height=side;x=cx-side/2;y=cy-side/2;}return{x:Math.max(0,x),y:Math.max(0,y),width:Math.max(0,width),height:Math.max(0,height),shape};}
function radiusFor(hole){if(!hole)return 0;if(hole.shape==='circle'||hole.shape==='pill')return Math.min(hole.width,hole.height)/2;if(hole.shape==='rounded')return Math.min(16,Math.min(hole.width,hole.height)/2);return Math.min(18,Math.max(8,Math.min(hole.width,hole.height)*.18));}
function unionRect(rects){if(!rects.length)return null;const left=Math.min(...rects.map(r=>r.x)),top=Math.min(...rects.map(r=>r.y)),right=Math.max(...rects.map(r=>r.x+r.width)),bottom=Math.max(...rects.map(r=>r.y+r.height));return{x:left,y:top,width:right-left,height:bottom-top};}
function rectIntersects(a,b,pad=8){if(!a||!b)return false;return!(a.x+a.width+pad<b.x||b.x+b.width+pad<a.x||a.y+a.height+pad<b.y||b.y+b.height+pad<a.y);}
function clamp(value,min,max){return Math.min(max,Math.max(min,value));}
function intersectionArea(a,b){if(!a||!b)return 0;const width=Math.max(0,Math.min(a.x+a.width,b.x+b.width)-Math.max(a.x,b.x)),height=Math.max(0,Math.min(a.y+a.height,b.y+b.height)-Math.max(a.y,b.y));return width*height;}
function uniqueNumbers(values){const result=[];for(const value of values){if(!Number.isFinite(value))continue;const rounded=Math.round(value*10)/10;if(!result.some(item=>Math.abs(item-rounded)<1))result.push(rounded);}return result;}
function sameHoles(current,next){return current.length===next.length&&current.every((hole,index)=>{const target=next[index];return hole.x===target.x&&hole.y===target.y&&hole.width===target.width&&hole.height===target.height&&hole.shape===target.shape&&hole.interactive===target.interactive&&hole.onPress===target.onPress&&hole.accessibilityLabel===target.accessibilityLabel;});}
function SpotlightMask({holes,width,height}){if(!holes.length)return <View pointerEvents="none" style={styles.fullShade}/>;return <Svg pointerEvents="none" width={width} height={height} style={StyleSheet.absoluteFill}><Defs><Mask id="guideSpot"><Rect x="0" y="0" width={width} height={height} fill="white"/>{holes.map((hole,index)=><Rect key={index} x={hole.x} y={hole.y} width={hole.width} height={hole.height} rx={radiusFor(hole)} ry={radiusFor(hole)} fill="black"/>)}</Mask></Defs><Rect x="0" y="0" width={width} height={height} fill={GUIDE_SHADE} mask="url(#guideSpot)"/></Svg>;}
function normalizeTargets({targetRef,targetRect,targets,spotlightPadding,spotlightShape,minSpotlightWidth,minSpotlightHeight,interactiveTarget,onTargetPress,targetAccessibilityLabel}){if(Array.isArray(targets)&&targets.length)return targets.map(item=>({ref:item?.ref||item?.targetRef||null,rect:item?.rect||null,shape:item?.shape||spotlightShape||'auto',padding:item?.padding??spotlightPadding,minWidth:item?.minWidth??minSpotlightWidth,minHeight:item?.minHeight??minSpotlightHeight,interactive:Boolean(item?.interactive),onPress:item?.onPress||null,accessibilityLabel:item?.accessibilityLabel||''}));return[{ref:targetRef||null,rect:targetRect||null,shape:spotlightShape||'auto',padding:spotlightPadding,minWidth:minSpotlightWidth,minHeight:minSpotlightHeight,interactive:Boolean(interactiveTarget),onPress:onTargetPress||null,accessibilityLabel:targetAccessibilityLabel||''}];}

export function GuideOverlay({visible,settings,step,onNext,onSkip,nextLabel='',showSkip=true,targetRef,targetRect,targets,spotlightPadding=8,spotlightShape='auto',minSpotlightWidth=0,minSpotlightHeight=0,contentPreference='auto',avoidHeader=true,avoidBottomNav=true,avoidElements=[],interactiveTarget=false,onTargetPress=null,targetAccessibilityLabel=''}){
  const{width,height}=useWindowDimensions(),insets=useSafeAreaInsets(),[holes,setHoles]=useState([]),[avoidRects,setAvoidRects]=useState([]),[panelHeight,setPanelHeight]=useState(188),halo=useRef(new Animated.Value(0)).current;
  const targetDefs=useMemo(()=>normalizeTargets({targetRef,targetRect,targets,spotlightPadding,spotlightShape,minSpotlightWidth,minSpotlightHeight,interactiveTarget,onTargetPress,targetAccessibilityLabel}),[targetRef,targetRect,targets,spotlightPadding,spotlightShape,minSpotlightWidth,minSpotlightHeight,interactiveTarget,onTargetPress,targetAccessibilityLabel,step]);
  useEffect(()=>{let alive=true,timers=[],interval=null;if(!visible||!step){setHoles([]);setAvoidRects([]);return()=>{alive=false;};}const measure=async()=>{const next=[];for(const item of targetDefs){const measured=item.rect||await measureTarget(item.ref),normalized=expandRect(measured,item.padding,item.minWidth,item.minHeight,item.shape);if(normalized)next.push({...normalized,interactive:item.interactive,onPress:item.onPress,accessibilityLabel:item.accessibilityLabel});}const avoided=[];for(const item of avoidElements||[]){const ref=item?.current!==undefined?item:item?.ref,rect=item?.x!==undefined?item:item?.rect||await measureTarget(ref);if(rect)avoided.push(rect);}if(alive){setHoles(current=>sameHoles(current,next)?current:next);setAvoidRects(current=>JSON.stringify(current)===JSON.stringify(avoided)?current:avoided);}};void measure();timers=[80,220,520].map(delay=>setTimeout(measure,delay));interval=setInterval(measure,140);return()=>{alive=false;timers.forEach(clearTimeout);if(interval)clearInterval(interval);};},[visible,step,targetDefs,width,height,avoidElements]);
  useEffect(()=>{if(!visible||!holes.length){halo.stopAnimation();halo.setValue(0);return;}const loop=Animated.loop(Animated.sequence([Animated.timing(halo,{toValue:1,duration:1075,easing:Easing.inOut(Easing.quad),useNativeDriver:true}),Animated.timing(halo,{toValue:0,duration:1075,easing:Easing.inOut(Easing.quad),useNativeDriver:true})]));loop.start();return()=>loop.stop();},[visible,holes.length,halo]);
  const panelStyle=useMemo(()=>{const panelWidth=Math.min(360,Math.max(0,width-28)),left=Math.max(14,(width-panelWidth)/2),cardHeight=Math.max(120,panelHeight),target=unionRect(holes),edge=width<=390?14:18,gap=edge,topLimit=avoidHeader?insets.top+theme.control.header+edge:edge,bottomLimit=avoidBottomNav?height-(insets.bottom+theme.control.nav+theme.chrome.contentRestGap):height-edge;if(!target)return{left,width:panelWidth,top:Math.max(topLimit,Math.min(bottomLimit-cardHeight,(height-cardHeight)/2))};if(contentPreference==='inside-bottom'){const maxTop=Math.max(edge,height-cardHeight-edge),minCandidateTop=Math.max(edge,target.y+gap),maxCandidateTop=Math.max(minCandidateTop,Math.min(maxTop,target.y+target.height-gap-cardHeight)),targetBottom=target.y+target.height-gap-cardHeight,protectedRects=avoidRects.map(rect=>({x:rect.x-gap,y:rect.y-gap,width:rect.width+gap*2,height:rect.height+gap*2})),aboveAvoided=protectedRects.length?Math.min(...protectedRects.map(rect=>rect.y))-cardHeight:targetBottom,candidates=[aboveAvoided,targetBottom,height*.72-cardHeight/2,(height-cardHeight)/2,height*.24-cardHeight/2],tops=uniqueNumbers(candidates.map(top=>clamp(top,minCandidateTop,maxCandidateTop)));let best=null;for(let index=0;index<tops.length;index+=1){const panelRect={x:left,y:tops[index],width:panelWidth,height:cardHeight},overlap=protectedRects.reduce((sum,rect)=>sum+intersectionArea(panelRect,rect),0),candidate={top:tops[index],penalty:overlap*100000+index};if(!best||candidate.penalty<best.penalty)best=candidate;if(overlap===0){best=candidate;break;}}return{left,width:panelWidth,top:best?.top??clamp((height-cardHeight)/2,minCandidateTop,maxCandidateTop)};}const topCandidate=Math.max(topLimit,target.y-cardHeight-14),bottomCandidate=Math.min(bottomLimit-cardHeight,target.y+target.height+14),topFits=topCandidate+cardHeight<=target.y-8,bottomFits=bottomCandidate>=target.y+target.height+8;let top;if(contentPreference==='top')top=topFits?topCandidate:bottomCandidate;else if(contentPreference==='bottom')top=bottomFits?bottomCandidate:topCandidate;else{const spaceAbove=target.y-topLimit,spaceBelow=bottomLimit-(target.y+target.height);top=spaceBelow>=spaceAbove&&bottomFits?bottomCandidate:topCandidate;}let panelRect={x:left,y:top,width:panelWidth,height:cardHeight};for(const avoid of avoidRects){if(!rectIntersects(panelRect,avoid))continue;const above=Math.max(topLimit,avoid.y-cardHeight-12),below=Math.min(bottomLimit-cardHeight,avoid.y+avoid.height+12);if(above+cardHeight<=avoid.y-6)top=above;else if(below>=avoid.y+avoid.height+6)top=below;panelRect={...panelRect,y:top};}return{left,width:panelWidth,top:Math.max(topLimit,Math.min(bottomLimit-cardHeight,top))};},[holes,avoidRects,panelHeight,height,width,insets.top,insets.bottom,avoidHeader,avoidBottomNav,contentPreference]);
  const targetExpected=targetDefs.some(item=>Boolean(item?.ref||item?.rect));if(!visible||!step||(targetExpected&&!holes.length))return null;const haloOpacity=halo.interpolate({inputRange:[0,1],outputRange:[.78,.42]});
  return <Modal visible transparent animationType="fade" onRequestClose={onSkip} statusBarTranslucent><View style={styles.root}><SpotlightMask holes={holes} width={width} height={height}/><Pressable accessibilityRole="none" style={StyleSheet.absoluteFill} onPress={()=>{}}/>{holes.map((hole,index)=><Animated.View key={`halo-${index}`} pointerEvents="none" style={[styles.halo,{left:hole.x,top:hole.y,width:hole.width,height:hole.height,borderRadius:radiusFor(hole),opacity:index===0?haloOpacity:.52}]}/>)}{holes.map((hole,index)=>hole.interactive&&hole.onPress?<Pressable key={`target-${index}`} accessibilityRole="button" accessibilityLabel={hole.accessibilityLabel||undefined} onPress={hole.onPress} style={[styles.targetProxy,{left:hole.x,top:hole.y,width:hole.width,height:hole.height,borderRadius:radiusFor(hole)}]}/>:null)}<View onLayout={event=>setPanelHeight(event.nativeEvent.layout.height||188)} accessibilityRole="alert" style={[styles.panel,panelStyle]}><GlassBackdrop blur={14} backgroundColor={GUIDE_PANEL}/><Text style={styles.title}>{cleanMarkup(msg(settings,step.titleKey))}</Text><Text style={styles.body}>{cleanMarkup(msg(settings,step.bodyKey,{required:80}))}</Text><View style={styles.nav}>{showSkip?<Pressable accessibilityRole="button" onPress={onSkip} style={styles.action}><Text style={styles.secondary}>{msg(settings,'guide.skip')}</Text></Pressable>:<View/>}<Pressable accessibilityRole="button" onPress={onNext} style={[styles.action,styles.primary]}><Text style={styles.primaryText}>{nextLabel||msg(settings,'guide.next')}</Text></Pressable></View></View></View></Modal>;
}
export function GuideHelpButton({onPress,label='?',accessibilityLabel='Guide',placement='leftCenter'}){const{width}=useWindowDimensions(),insets=useSafeAreaInsets(),compact=width<=390,size=compact?34:36,placementStyle=placement==='bottomRight'?{left:'auto',right:theme.chrome.guide.edge,top:'auto',bottom:Math.max(12,insets.bottom+theme.chrome.guide.bottomGap),marginTop:0}:{left:compact?9:10,right:'auto',top:'80%',bottom:'auto',marginTop:-size/2};return <Pressable accessibilityRole="button" accessibilityLabel={accessibilityLabel} onPress={onPress} style={({pressed})=>[styles.help,placementStyle,{width:size,height:size,borderRadius:size/2},pressed&&styles.pressed]}><GlassBackdrop blur={12} backgroundColor="rgba(246,242,233,.72)"/><Text style={[styles.helpText,compact&&styles.helpTextCompact]}>{label}</Text></Pressable>;}
const styles=StyleSheet.create({root:{flex:1},fullShade:{...StyleSheet.absoluteFillObject,backgroundColor:GUIDE_SHADE},halo:{position:'absolute',zIndex:2,borderWidth:1,borderColor:GUIDE_HALO,shadowColor:'#fff',shadowOpacity:.12,shadowRadius:14,shadowOffset:{width:0,height:0},elevation:8,backgroundColor:GUIDE_HALO_SOFT},targetProxy:{position:'absolute',zIndex:3,backgroundColor:'transparent'},panel:{position:'absolute',zIndex:4,maxWidth:360,paddingHorizontal:16,paddingTop:15,paddingBottom:13,borderWidth:1,borderColor:'rgba(54,50,43,.194)',borderRadius:theme.radius.lg,backgroundColor:'transparent',shadowColor:'#292721',shadowOpacity:.07,shadowRadius:14,shadowOffset:{width:0,height:5},elevation:12,overflow:'hidden'},title:{fontFamily:theme.font.terminal,fontSize:17,fontWeight:'900',lineHeight:21,color:C.text1},body:{marginTop:9,fontSize:13,lineHeight:19,color:C.text2},nav:{marginTop:13,flexDirection:'row',alignItems:'center',justifyContent:'space-between',gap:10},action:{minWidth:104,minHeight:36,alignItems:'center',justifyContent:'center',paddingHorizontal:12},primary:{borderWidth:1,borderColor:C.text1,backgroundColor:C.text1},secondary:{fontFamily:theme.font.terminal,fontSize:11,fontWeight:'800',color:C.text2},primaryText:{fontFamily:theme.font.terminal,fontSize:11,fontWeight:'800',color:C.inverse},help:{position:'absolute',zIndex:70,top:'80%',borderWidth:1,borderColor:'rgba(41,39,34,.22)',alignItems:'center',justifyContent:'center',backgroundColor:'transparent',shadowColor:'#292722',shadowOpacity:.07,shadowRadius:14,shadowOffset:{width:0,height:5},elevation:5,overflow:'hidden'},helpText:{fontFamily:theme.font.terminal,fontSize:17,fontWeight:'850',lineHeight:19,color:C.text1},helpTextCompact:{fontSize:16},pressed:{opacity:.78,transform:[{scale:.97},{translateY:1}]}});
