import * as CANNON from 'cannon-es';
import {BOUNDARY_RADIUS,BOUNDARY_RESTITUTION,BOUNDARY_TANGENT_RETENTION,DEFAULT_PIECE_COUNT,FLAT_MAX_SPEED,FLOOR_Y,GRAVITY,HOP_LAUNCH_CLEARANCE,HOP_MAX_SPEED,HOP_MAX_VERTICAL_SPEED,HOP_MIN_SPEED,HOP_MIN_VERTICAL_SPEED,MAX_PULL,PHYSICS_STEP,SHOT_CANCEL_RADIUS,TURN_READY_ANGULAR_SPEED,TURN_READY_LINEAR_SPEED,TURN_READY_STABLE_MS} from './constants.js';
import {topFace} from './faces.js';
import {evaluateCapture} from './rules.js';
import {planComputerShot} from './ai.js';
import {TRAJECTORY_FRAME_MS,TRAJECTORY_MAX_DURATION_MS,TRAJECTORY_MAX_FRAMES,interpolateTrajectoryFrames,makeTrajectoryFrame,normalizeTrajectoryImpacts,normalizeTrajectoryState,validateTrajectoryPacket} from './trajectory.js';

const clamp=(value,min,max)=>Math.max(min,Math.min(max,value));
const nowMs=()=>globalThis.performance?.now?.()??Date.now();
const normalizedPull=(pullLength)=>clamp(pullLength/MAX_PULL,0,1);
const effectiveHopPull=(pullLength)=>clamp((pullLength-SHOT_CANCEL_RADIUS)/(MAX_PULL-SHOT_CANCEL_RADIUS),0,1);
const flatSpeedForPull=(pullRatio)=>FLAT_MAX_SPEED*Math.pow(pullRatio,1.3);
function hopVelocity(pullLength,directionX,directionZ){const effective=effectiveHopPull(pullLength),horizontal=HOP_MIN_SPEED+(HOP_MAX_SPEED-HOP_MIN_SPEED)*Math.pow(effective,1.22),vertical=HOP_MIN_VERTICAL_SPEED+(HOP_MAX_VERTICAL_SPEED-HOP_MIN_VERTICAL_SPEED)*Math.pow(effective,1.02);return{x:directionX*horizontal,y:vertical,z:directionZ*horizontal};}
function resolveCircularBoundary(body){const distance=Math.hypot(body.position.x,body.position.z);if(distance<=BOUNDARY_RADIUS||distance===0)return false;const nx=body.position.x/distance,nz=body.position.z/distance,penetration=distance-BOUNDARY_RADIUS;body.position.x-=nx*penetration;body.position.z-=nz*penetration;body.aabbNeedsUpdate=true;const outward=body.velocity.x*nx+body.velocity.z*nz;if(outward>0){const tx=-nz,tz=nx,tangent=body.velocity.x*tx+body.velocity.z*tz,radial=-outward*BOUNDARY_RESTITUTION;body.velocity.x=nx*radial+tx*tangent*BOUNDARY_TANGENT_RETENTION;body.velocity.z=nz*radial+tz*tangent*BOUNDARY_TANGENT_RETENTION;if(outward>.03)body.wakeUp();}return true;}
function createBody(id,material){const body=new CANNON.Body({mass:1,material,linearDamping:.22,angularDamping:.38,sleepSpeedLimit:.12,sleepTimeLimit:.72});body.addShape(new CANNON.Box(new CANNON.Vec3(.48,.32,.28)));body.addShape(new CANNON.Sphere(.34),new CANNON.Vec3(-.5,.07,-.01));body.addShape(new CANNON.Sphere(.35),new CANNON.Vec3(.51,-.05,.015));body.addShape(new CANNON.Box(new CANNON.Vec3(.12,.23,.2)),new CANNON.Vec3(-.78,.03,0));body.addShape(new CANNON.Box(new CANNON.Vec3(.12,.22,.2)),new CANNON.Vec3(.79,-.02,0));body.allowSleep=true;body.userData={ashykId:id};return body;}
function clearedHopY(body){body.aabbNeedsUpdate=true;body.updateAABB();return body.position.y+Math.max(0,FLOOR_Y+HOP_LAUNCH_CLEARANCE-body.aabb.lowerBound.y);}
export function createAshykEngine({random=Math.random,onEvent=()=>{}}={}){
  let eventsSuppressed=0;
  const emit=(type,payload={})=>{if(!eventsSuppressed)onEvent({type,...payload});};
  const world=new CANNON.World({gravity:new CANNON.Vec3(0,-GRAVITY,0)});world.allowSleep=true;world.broadphase=new CANNON.SAPBroadphase(world);world.solver.iterations=20;
  const boardMaterial=new CANNON.Material('board'),boneMaterial=new CANNON.Material('ashyk'),slideMaterial=new CANNON.Material('ashyk-slide');
  world.addContactMaterial(new CANNON.ContactMaterial(boardMaterial,boneMaterial,{friction:.12,restitution:.035,contactEquationStiffness:1e8}));
  world.addContactMaterial(new CANNON.ContactMaterial(boneMaterial,boneMaterial,{friction:.18,restitution:.42,contactEquationStiffness:1e8}));
  world.addContactMaterial(new CANNON.ContactMaterial(boardMaterial,slideMaterial,{friction:.045,restitution:.005,contactEquationStiffness:1e8}));
  world.addContactMaterial(new CANNON.ContactMaterial(slideMaterial,boneMaterial,{friction:.14,restitution:.45,contactEquationStiffness:1e8}));
  const floor=new CANNON.Body({mass:0,material:boardMaterial});floor.addShape(new CANNON.Plane());floor.position.y=FLOOR_Y;floor.quaternion.setFromEuler(-Math.PI/2,0,0);world.addBody(floor);
  const pieces=[];
  let selectedId=null,remoteSelectedId=null,remoteAim=null,shotActive=false,shotStartedAt=0,activeShotMode=null,targetId=null,attackerStartFace=null,targetStartFace=null,touchedIds=new Set(),contactPairs=new Set(),preShotFaces=new Map(),ready=false,readySince=null,lastRollEmit=0,remotePlayback=null,pendingAuthoritative=null;
  let previousFlat={linear:.22,angular:.38};

  const alive=()=>pieces.filter((piece)=>piece.alive);
  const pieceById=(id)=>pieces.find((piece)=>piece.id===id&&piece.alive)||null;
  const serializePiece=(piece,motion=false)=>{const row={id:piece.id,alive:piece.alive,position:[piece.body.position.x,piece.body.position.y,piece.body.position.z],quaternion:[piece.body.quaternion.x,piece.body.quaternion.y,piece.body.quaternion.z,piece.body.quaternion.w]};if(motion){row.velocity=[piece.body.velocity.x,piece.body.velocity.y,piece.body.velocity.z];row.angularVelocity=[piece.body.angularVelocity.x,piece.body.angularVelocity.y,piece.body.angularVelocity.z];}return row;};
  function snapshot(){return{pieces:pieces.map((piece)=>serializePiece(piece,false))};}
  function motionSnapshot(){return{pieces:pieces.map((piece)=>serializePiece(piece,true))};}
  function physicsSnapshot(){return{pieces:pieces.map((piece)=>({...serializePiece(piece,true),sleeping:piece.body.sleepState===CANNON.Body.SLEEPING}))};}
  function setReady(value){if(ready===value)return;ready=value;emit('ready',{ready:value,state:value?snapshot():null});}
  function allBelowMotion(){const rows=alive();if(!rows.length)return false;const linearSq=TURN_READY_LINEAR_SPEED*TURN_READY_LINEAR_SPEED,angularSq=TURN_READY_ANGULAR_SPEED*TURN_READY_ANGULAR_SPEED;return rows.every((piece)=>piece.body.sleepState===CANNON.Body.SLEEPING||(piece.body.velocity.lengthSquared()<=linearSq&&piece.body.angularVelocity.lengthSquared()<=angularSq));}
  function updateReady(time){if(!allBelowMotion()){readySince=null;setReady(false);return false;}if(readySince===null)readySince=time;const stable=time-readySince>=TURN_READY_STABLE_MS;setReady(!shotActive&&!remotePlayback&&stable);return stable;}
  function collisionStrength(source,event){const contact=event.contact?Math.abs(event.contact.getImpactVelocityAlongNormal()):0;if(contact>0)return contact;return Math.hypot(source.velocity.x-event.body.velocity.x,source.velocity.y-event.body.velocity.y,source.velocity.z-event.body.velocity.z);}
  function recordCollision(sourceId,otherId){if(!shotActive||selectedId===null||otherId===sourceId)return;const low=Math.min(sourceId,otherId),high=Math.max(sourceId,otherId);contactPairs.add(`${low}:${high}`);if(sourceId!==selectedId&&otherId!==selectedId)return;const contacted=sourceId===selectedId?otherId:sourceId;if(contacted===selectedId)return;touchedIds.add(contacted);if(targetId===null){targetId=contacted;const target=pieceById(contacted);targetStartFace=preShotFaces.get(contacted)??(target?topFace(target.body):null);}}
  function onCollision(id,body,event){const strength=collisionStrength(body,event),pan=clamp(body.position.x/14,-.78,.78);if(event.body===floor){emit('impact',{kind:'board',strength,key:`board:${id}`,pan});return;}const otherId=event.body?.userData?.ashykId;if(typeof otherId!=='number'||otherId===id)return;const low=Math.min(id,otherId),high=Math.max(id,otherId);emit('impact',{kind:'ashyk',strength,key:`ashyk:${low}:${high}`,pan});recordCollision(id,otherId);}
  function addPiece(id){const body=createBody(id,boneMaterial);body.addEventListener('collide',(event)=>onCollision(id,body,event));world.addBody(body);const piece={id,body,alive:true};pieces.push(piece);return piece;}
  function ensurePiece(item){let piece=pieces.find((candidate)=>candidate.id===item.id);if(!piece)piece=addPiece(item.id);if(item.alive&&!piece.alive){piece.alive=true;world.addBody(piece.body);}else if(!item.alive&&piece.alive){piece.alive=false;world.removeBody(piece.body);}return piece;}
  function clearSelection(){selectedId=null;emit('selection',{selectedId:null,face:null});}
  function resetRemoteVisual(){remoteSelectedId=null;remoteAim=null;}
  function reset(){for(const piece of pieces)world.removeBody(piece.body);pieces.length=0;shotActive=false;remotePlayback=null;pendingAuthoritative=null;activeShotMode=null;targetId=null;attackerStartFace=null;targetStartFace=null;touchedIds=new Set();contactPairs=new Set();preShotFaces=new Map();selectedId=null;resetRemoteVisual();readySince=null;setReady(false);for(let id=0;id<DEFAULT_PIECE_COUNT;id+=1){const piece=addPiece(id),angle=id/DEFAULT_PIECE_COUNT*Math.PI*2+random()*.55,radius=3.2+random()*6;piece.body.position.set(Math.cos(angle)*radius,5.2+random()*3.3,Math.sin(angle)*radius);piece.body.quaternion.setFromEuler(random()*Math.PI*2,random()*Math.PI*2,random()*Math.PI*2);piece.body.velocity.set((random()-.5)*3.2,-.9-random()*1.2,(random()-.5)*3.2);piece.body.angularVelocity.set((random()-.5)*9,(random()-.5)*9,(random()-.5)*9);}emit('reset',{state:snapshot()});}
  function removePiece(piece){if(!piece?.alive)return;piece.alive=false;world.removeBody(piece.body);emit('removed',{id:piece.id});}
  function restoreShotPhysics(){const selected=pieceById(selectedId);if(!selected||activeShotMode!=='flat')return;selected.body.material=boneMaterial;selected.body.linearDamping=previousFlat.linear;selected.body.angularDamping=previousFlat.angular;}
  function finishShot(stable){const selected=pieceById(selectedId);if(!selected)return;let result;if(targetId===null||!attackerStartFace||!targetStartFace){result={success:false,hitAny:touchedIds.size>0,reasonCode:'miss',remainingPieces:alive().length};}else{const primary=new Set([selected.id,targetId]),third=[...contactPairs].some((pair)=>{const[a,b]=pair.split(':').map(Number),involves=primary.has(a)||primary.has(b),primaryPair=primary.has(a)&&primary.has(b);return involves&&!primaryPair;});const evaluation=evaluateCapture(attackerStartFace,targetStartFace,third),target=pieceById(targetId);if(evaluation.success&&target)removePiece(target);result={...evaluation,hitAny:touchedIds.size>0,capturedId:evaluation.success?targetId:undefined,remainingPieces:alive().length};}restoreShotPhysics();shotActive=false;activeShotMode=null;targetId=null;attackerStartFace=null;targetStartFace=null;touchedIds=new Set();contactPairs=new Set();preShotFaces=new Map();clearSelection();setReady(Boolean(stable));emit('shotSettled',{result,state:snapshot()});}
  function prepareShot(piece,mode){preShotFaces=new Map(alive().map((entry)=>[entry.id,topFace(entry.body)]));selectedId=piece.id;attackerStartFace=preShotFaces.get(piece.id)??topFace(piece.body);targetStartFace=null;targetId=null;touchedIds=new Set();contactPairs=new Set();activeShotMode=mode;shotActive=true;shotStartedAt=nowMs();readySince=null;setReady(false);}
  function launch(id,{mode='flat',directionX=0,directionZ=0,pullLength=0,pullRatio=null}={}){if(shotActive||remotePlayback||!ready)return false;const piece=pieceById(id);if(!piece)return false;const length=Math.hypot(directionX,directionZ);if(length<.0001)return false;directionX/=length;directionZ/=length;const ratio=pullRatio??normalizedPull(pullLength),effectivePull=pullLength||ratio*MAX_PULL;if(effectivePull<=SHOT_CANCEL_RADIUS)return false;const preShotState=physicsSnapshot();prepareShot(piece,mode);if(mode==='flat'){previousFlat={linear:piece.body.linearDamping,angular:piece.body.angularDamping};piece.body.material=slideMaterial;piece.body.linearDamping=.018;piece.body.angularDamping=.3;const speed=flatSpeedForPull(ratio);piece.body.velocity.x=directionX*speed;piece.body.velocity.z=directionZ*speed;piece.body.velocity.y=Math.min(piece.body.velocity.y,0);piece.body.angularVelocity.setZero();}else{const velocity=hopVelocity(effectivePull,directionX,directionZ);piece.body.position.y=clearedHopY(piece.body);piece.body.aabbNeedsUpdate=true;piece.body.material=boneMaterial;piece.body.velocity.set(velocity.x,velocity.y,velocity.z);const horizontal=Math.hypot(velocity.x,velocity.z);piece.body.angularVelocity.x+=directionZ*horizontal*.16;piece.body.angularVelocity.z-=directionX*horizontal*.16;}piece.body.wakeUp();remoteAim=null;emit('shot',{id:piece.id,mode,directionX,directionZ,pullLength:effectivePull,pullRatio:ratio,preShotState,state:motionSnapshot()});return true;}
  function launchComputer(accuracy){if(shotActive||remotePlayback||!ready)return false;const plan=planComputerShot(alive().map((piece)=>({id:piece.id,x:piece.body.position.x,z:piece.body.position.z,face:topFace(piece.body)})),accuracy,random);if(!plan)return false;return launch(plan.sourceId,{mode:'flat',directionX:plan.directionX,directionZ:plan.directionZ,pullRatio:plan.pullRatio,pullLength:plan.pullRatio*MAX_PULL});}
  function select(id){if(shotActive||remotePlayback||!ready)return false;const piece=pieceById(id);if(!piece)return false;selectedId=id;emit('selection',{selectedId:id,face:topFace(piece.body)});return true;}
  function applyStateInstant(state,{authoritative=false}={}){if(!state?.pieces)return false;shotActive=false;activeShotMode=null;targetId=null;selectedId=null;if(authoritative){remotePlayback=null;pendingAuthoritative=null;resetRemoteVisual();}for(const item of state.pieces){const piece=ensurePiece(item);if(!item.alive)continue;piece.body.position.set(...item.position);piece.body.quaternion.set(...item.quaternion);piece.body.velocity.setZero();piece.body.angularVelocity.setZero();piece.body.aabbNeedsUpdate=true;piece.body.sleep();}readySince=nowMs();setReady(false);if(authoritative)emit('snapshotApplied',{state:snapshot()});return true;}
  function applySnapshot(state){return applyStateInstant(state,{authoritative:true});}
  function applyAuthoritativeSnapshot(state){if(!state?.pieces)return false;if(remotePlayback){pendingAuthoritative=state;return true;}return applySnapshot(state);}
  function applyPlaybackState(state){if(!state?.pieces)return false;for(const item of state.pieces){const piece=ensurePiece(item);if(!item.alive)continue;piece.body.position.set(...item.position);piece.body.quaternion.set(...item.quaternion);piece.body.velocity.setZero();piece.body.angularVelocity.setZero();piece.body.aabbNeedsUpdate=true;piece.body.sleep();}return true;}
  function playRemoteTrajectory(trajectory,{startedAt=nowMs()}={}){if(!validateTrajectoryPacket(trajectory))return false;shotActive=false;selectedId=null;resetRemoteVisual();pendingAuthoritative=null;applyStateInstant({pieces:trajectory.frames[0].pieces});remotePlayback={trajectory,startedAt:Number(startedAt)||nowMs(),frameIndex:0,impactIndex:0};setReady(false);return true;}
  function finishRemotePlayback(state=null){const playback=remotePlayback,finalState=state||pendingAuthoritative||playback?.trajectory?.finalState||null;remotePlayback=null;resetRemoteVisual();if(pendingAuthoritative){const authoritative=pendingAuthoritative;pendingAuthoritative=null;return applySnapshot(authoritative);}pendingAuthoritative=null;if(finalState)return applyStateInstant(finalState,{authoritative:true});return true;}
  function stepRemotePlayback(time){if(!remotePlayback)return false;const playback=remotePlayback,trajectory=playback.trajectory,elapsed=clamp(time-playback.startedAt,0,trajectory.durationMs),frames=trajectory.frames;while(playback.impactIndex<trajectory.impacts.length&&trajectory.impacts[playback.impactIndex].t<=elapsed){const impact=trajectory.impacts[playback.impactIndex++];emit('impact',{kind:impact.kind,strength:impact.strength,key:`remote:${trajectory.shotId}:${impact.key}:${playback.impactIndex}`,pan:impact.pan,remote:true});}while(playback.frameIndex<frames.length-2&&frames[playback.frameIndex+1].t<=elapsed)playback.frameIndex+=1;const a=frames[playback.frameIndex],b=frames[Math.min(playback.frameIndex+1,frames.length-1)],state=a===b?{pieces:a.pieces}:interpolateTrajectoryFrames(a,b,elapsed);if(state)applyPlaybackState(state);if(elapsed>=trajectory.durationMs){finishRemotePlayback(trajectory.finalState);return true;}return true;}
  function loadPhysicsState(state){if(!state?.pieces)return false;eventsSuppressed+=1;try{shotActive=false;remotePlayback=null;pendingAuthoritative=null;activeShotMode=null;targetId=null;selectedId=null;resetRemoteVisual();for(const item of state.pieces){const piece=ensurePiece(item);if(!item.alive)continue;piece.body.material=boneMaterial;piece.body.linearDamping=.22;piece.body.angularDamping=.38;piece.body.position.set(...item.position);piece.body.quaternion.set(...item.quaternion);piece.body.velocity.set(...(Array.isArray(item.velocity)?item.velocity:[0,0,0]));piece.body.angularVelocity.set(...(Array.isArray(item.angularVelocity)?item.angularVelocity:[0,0,0]));piece.body.aabbNeedsUpdate=true;if(item.sleeping)piece.body.sleep();else piece.body.wakeUp();}readySince=nowMs();ready=true;return true;}finally{eventsSuppressed=Math.max(0,eventsSuppressed-1);}}
  function setRemoteSelection(id){remoteSelectedId=Number.isInteger(id)&&pieceById(id)?id:null;if(remoteSelectedId===null)remoteAim=null;return remoteSelectedId;}
  function setRemoteAim(value){if(!value){remoteAim=null;return null;}const pieceId=Number(value.pieceId);if(!Number.isInteger(pieceId)||!pieceById(pieceId))return null;remoteSelectedId=pieceId;remoteAim={pieceId,mode:value.mode==='hop'?'hop':'flat',directionX:Number(value.directionX)||0,directionZ:Number(value.directionZ)||0,pullLength:clamp(Number(value.pullLength)||0,0,MAX_PULL)};return remoteAim;}
  function reportAim(value){if(!value){emit('aimClear');return;}emit('aim',{...value});}
  function preview({mode='flat',originX=0,originY=FLOOR_Y+.1,originZ=0,directionX=0,directionZ=0,pullLength=0,steps=16}={}){const length=Math.hypot(directionX,directionZ)||1,dx=directionX/length,dz=directionZ/length,ratio=normalizedPull(pullLength);if(mode==='flat'){const distance=2.4+(12.4-2.4)*Math.pow(ratio,1.3);return Array.from({length:Math.min(steps,7)},(_,i)=>{const p=i/Math.max(1,Math.min(steps,7)-1);return[originX+dx*(.8+distance*p),.205,originZ+dz*(.8+distance*p)];});}const v=hopVelocity(pullLength,dx,dz),count=Math.min(steps,16),duration=Math.max(.32,Math.min(1.9,(v.y+Math.sqrt(v.y*v.y+2*GRAVITY*Math.max(0,originY-FLOOR_Y)))/GRAVITY));return Array.from({length:count},(_,i)=>{const t=duration*(i/Math.max(1,count-1));return[originX+v.x*t,Math.max(FLOOR_Y+.1,originY+v.y*t-.5*GRAVITY*t*t),originZ+v.z*t];});}
  function step(dt,time=nowMs()){if(remotePlayback){stepRemotePlayback(time);return snapshot();}world.step(PHYSICS_STEP,Math.min(Math.max(dt,0),1/20),5);const grounded=new Set();for(const contact of world.contacts){const other=contact.bi===floor?contact.bj:contact.bj===floor?contact.bi:null;const id=other?.userData?.ashykId;if(typeof id==='number')grounded.add(id);}for(const piece of alive()){const distance=Math.hypot(piece.body.position.x,piece.body.position.z),nx=distance?piece.body.position.x/distance:0,nz=distance?piece.body.position.z/distance:0,boundaryImpact=distance>BOUNDARY_RADIUS?Math.max(0,piece.body.velocity.x*nx+piece.body.velocity.z*nz):0;if(resolveCircularBoundary(piece.body)&&boundaryImpact>0)emit('impact',{kind:'rim',strength:boundaryImpact,key:`rim:${piece.id}`,pan:clamp(piece.body.position.x/14,-.78,.78)});if(time-lastRollEmit>45){emit('rolling',{key:`roll:${piece.id}`,linearSpeed:Math.hypot(piece.body.velocity.x,piece.body.velocity.z),angularSpeed:piece.body.angularVelocity.length(),grounded:grounded.has(piece.id),pan:clamp(piece.body.position.x/14,-.78,.78)});}}
    if(time-lastRollEmit>45)lastRollEmit=time;const stable=updateReady(time);if(shotActive&&selectedId!==null){if(stable)finishShot(true);else if(time-shotStartedAt>TRAJECTORY_MAX_DURATION_MS){for(const piece of alive()){piece.body.velocity.setZero();piece.body.angularVelocity.setZero();piece.body.sleep();}readySince=time;setReady(true);finishShot(true);}}return snapshot();}
  function settleInitial(maxSteps=900){if(ready)return snapshot();eventsSuppressed+=1;try{const base=nowMs();for(let i=0;i<maxSteps&&!ready;i+=1)step(PHYSICS_STEP,base+(i+1)*PHYSICS_STEP*1000);return snapshot();}finally{eventsSuppressed=Math.max(0,eventsSuppressed-1);}}
  function destroy(){remotePlayback=null;pendingAuthoritative=null;for(const piece of pieces)world.removeBody(piece.body);pieces.length=0;selectedId=null;resetRemoteVisual();}
  reset();
  return{world,reset,step,destroy,snapshot,motionSnapshot,physicsSnapshot,loadPhysicsState,settleInitial,applySnapshot,applyAuthoritativeSnapshot,playRemoteTrajectory,finishRemotePlayback,setRemoteSelection,setRemoteAim,reportAim,select,clearSelection,launch,launchComputer,preview,simulateShotTrajectory,isReady:()=>ready,isShotActive:()=>shotActive||Boolean(remotePlayback),isRemotePlaybackActive:()=>Boolean(remotePlayback),getSelectedId:()=>selectedId,getVisualSelectedId:()=>selectedId??remoteSelectedId,getRemoteAim:()=>remoteAim,getPieces:()=>pieces.map((piece)=>({id:piece.id,alive:piece.alive,body:piece.body})),getPiece:(id)=>pieceById(id),getFace:(id)=>{const piece=pieceById(id);return piece?topFace(piece.body):null;},getAliveCount:()=>alive().length};
}


export function simulateShotTrajectory({initialState,pieceId,mode='flat',directionX=0,directionZ=0,pullLength=0,pullRatio=null}={}){
  let elapsedMs=0,result=null,finalState=null,settled=false;
  const impacts=[];
  const simulation=createAshykEngine({onEvent:(event)=>{if(event.type==='impact')impacts.push({t:Math.min(elapsedMs,TRAJECTORY_MAX_DURATION_MS),kind:event.kind,strength:event.strength,key:event.key,pan:event.pan});else if(event.type==='shotSettled'){settled=true;result=event.result;finalState=event.state;}}});
  try{
    if(!simulation.loadPhysicsState(initialState))throw new Error('Invalid Ashyk pre-shot state');
    const base=nowMs();
    if(!simulation.launch(Number(pieceId),{mode,directionX,directionZ,pullLength,pullRatio}))throw new Error('Ashyk trajectory launch rejected');
    const frames=[makeTrajectoryFrame(0,simulation.snapshot())];
    let nextFrameAt=TRAJECTORY_FRAME_MS;
    const maxSteps=Math.ceil(TRAJECTORY_MAX_DURATION_MS/(PHYSICS_STEP*1000))+2;
    for(let stepIndex=0;stepIndex<maxSteps&&!settled;stepIndex+=1){
      elapsedMs=(stepIndex+1)*PHYSICS_STEP*1000;
      simulation.step(PHYSICS_STEP,base+elapsedMs);
      while(nextFrameAt<=Math.min(elapsedMs,TRAJECTORY_MAX_DURATION_MS)&&frames.length<TRAJECTORY_MAX_FRAMES){
        const frame=makeTrajectoryFrame(nextFrameAt,simulation.snapshot());
        if(frame)frames.push(frame);
        nextFrameAt+=TRAJECTORY_FRAME_MS;
      }
    }
    const durationMs=Math.min(elapsedMs,TRAJECTORY_MAX_DURATION_MS),normalizedFinal=normalizeTrajectoryState(finalState||simulation.snapshot());
    if(!normalizedFinal)throw new Error('Invalid Ashyk trajectory final state');
    const finalFrame=makeTrajectoryFrame(durationMs,normalizedFinal);
    if(!finalFrame)throw new Error('Invalid Ashyk trajectory final frame');
    if(frames.length&&Math.abs(frames.at(-1).t-finalFrame.t)<.01)frames[frames.length-1]=finalFrame;else frames.push(finalFrame);
    return{durationMs:finalFrame.t,frames,impacts:normalizeTrajectoryImpacts(impacts),finalState:normalizedFinal,result};
  }finally{simulation.destroy();}
}
