const M=Object.freeze({
  ru:Object.freeze({
    title:'Ашыкъ оюн',modeLabel:'РЕЖИМ',difficultyLabel:'СЛОЖНОСТЬ',cameraLabel:'КАМЕРА',newGame:'Новая игра',computer:'Против компьютера',online:'По сети',easy:'Лёгкий',normal:'Средний',hard:'Сложный',computerAccuracy:'Точность компьютера',computerAnswers:'Ответы компьютера',shotTime:'На удар',answerTime:'На ответ',seconds:'сек',start:'Начать игру',createRoom:'Создать комнату',connect:'Подключение…',join:'Войти',roomCode:'КОД КОМНАТЫ',shareCode:'Передайте код второму игроку',loginOnline:'Для игры по сети войдите в аккаунт Alan Til.',mediumWords:'Слова: «Возвращение к истокам» · Средний · Alan → RU',
    you:'Вы',computerPlayer:'Компьютер',opponent:'Соперник',startLabel:'СТАРТ',finishLabel:'ФИНИШ',questionLabel:'ВОПРОС',computerLabel:'КОМПЬЮТЕР',bonusShotLabel:'ДОП. УДАР',shotLabel:'УДАР',shotType:'ТИП УДАРА',flat:'По плоскости',hop:'Подброс',help:'Правила',menu:'Меню',appearance:'Оформление',currentGame:'Текущая игра',inviteSent:'Вызов отправлен',preparingGameStatus:'Подключение к игре',gameInProgress:'Игра идёт',cancelCurrentGame:'Отменить вызов',resignGame:'Сдаться',confirmResign:'Сдаться и завершить текущую игру?',top:'Сверху',orbit:'3D',position:'Положение',tapHint:'Тап — выбрать · drag выбранного — удар',
    tapAction:'Выбор ашыка',flatAction:'Прямой удар',hopAction:'Удар с подбросом',tapActionHelp:'Нажмите на ашык, чтобы выбрать его.',flatActionHelp:'Пунктирная прямая стрелка — удар по плоскости.',hopActionHelp:'Пунктирная дуга — удар с подбросом.',
    translate:'Переведи слово',bonusQuestion:'ЗА ДОПОЛНИТЕЛЬНЫЙ УДАР',answer:'Ответить',skip:'Пропуск',computerAnswersNow:'Компьютер отвечает…',opponentAnswersNow:'Соперник отвечает…',opponentSubmitted:'Соперник подтвердил ответ',questionRule:'Верно → +3 очка и ещё 1 удар\nНеверно → −1 балл\nПропуск → без штрафа',
    gameOver:'ПАРТИЯ ОКОНЧЕНА',draw:'Ничья',won:'победил',youWon:'Вы победили',youLost:'Вы проиграли',backToPractice:'Вернуться в практику',finalField:'Победитель определяется по итоговому счёту.',
    rules:'Правила',helpGoalTitle:'Цель игры',helpGoalText:'На поле 10 ашыков. Бейте выбранным ашыком по ашыку с такой же верхней гранью. Совпали грани — взятие засчитано.',helpControlsTitle:'Ход за 3 шага',helpControlsText:'1. Выберите ашык. 2. Выберите удар. 3. Задайте направление и силу до конца таймера.',helpCaptureTitle:'Когда взятие засчитано',helpCaptureText:'Сравниваются верхние грани бьющего и первого задетого ашыка — в положении до удара. Совпали — цель убирается, вы получаете очки. Задели третий ашык — взятия нет.',helpPenaltyTitle:'Если не получилось',helpPenaltyText:'Промах мимо всех — −1. Задели цель, но грани разные, или коснулись третьего ашыка — 0. Затем ход соперника.',helpFacesTitle:'Грани = очки',helpFacesText:'Взятие приносит столько очков, сколько стоит совпавшая верхняя грань:',helpQuestionsTitle:'Взял — ответь',helpQuestionsText:'Взяли ашык основным ударом — получите вопрос. Верно: +3 и дополнительный удар. Неверно: −1. Пропуск или время вышло: без штрафа. После дополнительного удара нового вопроса нет.',helpEndTitle:'Финал',helpEndText:'После взятия остался один ашык — партия окончена. Побеждает тот, у кого больше очков.',helpKytTitle:'Особое правило',helpKytText:'Къыт → Къыт — мгновенная победа при любом счёте.',points:'очк.',instantWin:'мгновенная победа',
    faceChyk:'Чыкъ',faceFok:'Фок',faceTau:'Тау',faceAlchi:'Алчы',faceBiy:'Бий',faceKyt:'Къыт',
    rulesGoal:'На поле 10 ашыков. Набирайте очки успешными взятиями.',sameFace:'Сравниваются верхние грани до удара; целью считается первый ашык, которого коснулся бьющий.',thirdPiece:'Если бьющий или цель задели третий ашык, взятие не засчитывается.',kytWin:'КЪЫТ в КЪЫТ — мгновенная победа.',bonus:'После взятия основным ударом: верно +3 и один дополнительный удар; неверно −1; пропуск без штрафа.',close:'Закрыть',
    statusChoose:'Выберите режим и сложность',statusWaiting:'Ожидание соперника',statusFinished:'Партия окончена',statusSettling:'Ашыкъ успокаиваются',statusComputer:'Компьютер выбирает удар',statusOpponent:'Ход соперника',statusSelected:'Ашыкъ выбран — потяните его ещё раз для удара',statusBonusShot:'Дополнительный удар',statusChoosePiece:'Выберите Ашыкъ',miss:'Мимо всех Ашыкъ',faceMismatch:'Грани не совпали',thirdTouched:'Задет третий Ашыкъ',capture:'Совпадение',correct:'Верно',wrong:'Неверно',timeout:'Время вышло',noPenalty:'без штрафа',opponentResigned:'Соперник сдался',resigned:'Вы сдались',opponentDisconnected:'Соперник отключился · победа',roomError:'Не удалось синхронизировать сетевую игру.',questionPoolError:'Недостаточно слов одной части речи для четырёх вариантов ответа.'
  }),
  en:Object.freeze({
    title:'Ашыкъ оюн',modeLabel:'MODE',difficultyLabel:'DIFFICULTY',cameraLabel:'CAMERA',newGame:'New game',computer:'Vs computer',online:'Online',easy:'Easy',normal:'Medium',hard:'Hard',computerAccuracy:'Computer accuracy',computerAnswers:'Computer answers',shotTime:'Shot time',answerTime:'Answer time',seconds:'sec',start:'Start game',createRoom:'Create room',connect:'Connecting…',join:'Join',roomCode:'ROOM CODE',shareCode:'Send the code to the second player',loginOnline:'Sign in to Alan Til to play online.',mediumWords:'Words: “Return to the roots” · Medium · Alan → Russian',
    you:'You',computerPlayer:'Computer',opponent:'Opponent',startLabel:'START',finishLabel:'FINISH',questionLabel:'QUESTION',computerLabel:'COMPUTER',bonusShotLabel:'BONUS SHOT',shotLabel:'SHOT',shotType:'SHOT TYPE',flat:'Flat',hop:'Hop',help:'Rules',menu:'Menu',appearance:'Appearance',currentGame:'Current game',inviteSent:'Challenge sent',preparingGameStatus:'Connecting to game',gameInProgress:'Game in progress',cancelCurrentGame:'Cancel challenge',resignGame:'Resign',confirmResign:'Resign and end the current game?',top:'Top',orbit:'3D',position:'Face',tapHint:'Tap to select · drag selected Ashyk to shoot',
    tapAction:'Select Ashyk',flatAction:'Direct shot',hopAction:'Lob shot',tapActionHelp:'Tap an Ashyk to select it.',flatActionHelp:'The dotted straight arrow means a direct shot along the board.',hopActionHelp:'The dotted curved arrow means a lob shot.',
    translate:'Translate the word',bonusQuestion:'FOR A BONUS SHOT',answer:'Answer',skip:'Skip',computerAnswersNow:'Computer is answering…',opponentAnswersNow:'Opponent is answering…',opponentSubmitted:'Opponent submitted the answer',questionRule:'Correct → +3 and one bonus shot\nWrong → −1\nSkip → no penalty',
    gameOver:'GAME OVER',draw:'Draw',won:'won',youWon:'You won',youLost:'You lost',backToPractice:'Back to Practice',finalField:'The winner is determined by the final score.',
    rules:'Rules',helpGoalTitle:'Goal',helpGoalText:'There are 10 Ashyks. Hit an Ashyk showing the same top face as your striker. Same face = capture.',helpControlsTitle:'Turn in 3 steps',helpControlsText:'1. Pick an Ashyk. 2. Pick a shot. 3. Set direction and power before time runs out.',helpCaptureTitle:'When a capture counts',helpCaptureText:'Compare the striker with the first Ashyk it touches, using their top faces before the shot. Match = target removed and points scored. Touch a third Ashyk = no capture.',helpPenaltyTitle:'If it does not work',helpPenaltyText:'Miss everything: −1. Hit the target with a different face, or touch a third Ashyk: 0. Then the turn passes.',helpFacesTitle:'Faces = points',helpFacesText:'A capture scores the value of the matching top face:',helpQuestionsTitle:'Capture — then answer',helpQuestionsText:'Capture on the main shot → a word question. Correct: +3 and one bonus shot. Wrong: −1. Skip or timeout: no penalty. A bonus shot never opens another question.',helpEndTitle:'Finish',helpEndText:'If a capture leaves one Ashyk on the board, the game ends. Higher score wins.',helpKytTitle:'Special rule',helpKytText:'Къыт → Къыт = instant win, whatever the score.',points:'pts',instantWin:'instant win',
    faceChyk:'Чыкъ',faceFok:'Фок',faceTau:'Тау',faceAlchi:'Алчы',faceBiy:'Бий',faceKyt:'Къыт',
    rulesGoal:'There are 10 Ashyks. Score points with valid captures.',sameFace:'Top faces are compared before the shot; the target is the first Ashyk touched by the striker.',thirdPiece:'If the striker or target touches a third Ashyk, the capture is void.',kytWin:'КЪЫТ into КЪЫТ is an instant win.',bonus:'After a main-shot capture: correct +3 and one bonus shot; wrong −1; skip has no penalty.',close:'Close',
    statusChoose:'Choose mode and difficulty',statusWaiting:'Waiting for opponent',statusFinished:'Game over',statusSettling:'Ashyks are settling',statusComputer:'Computer is choosing a shot',statusOpponent:'Opponent’s turn',statusSelected:'Ashyk selected — drag it again to shoot',statusBonusShot:'Bonus shot',statusChoosePiece:'Choose an Ashyk',miss:'Missed every Ashyk',faceMismatch:'Faces do not match',thirdTouched:'Third Ashyk touched',capture:'Matched',correct:'Correct',wrong:'Wrong',timeout:'Time expired',noPenalty:'no penalty',opponentResigned:'Opponent resigned',resigned:'You resigned',opponentDisconnected:'Opponent disconnected · win',roomError:'Could not synchronize the online game.',questionPoolError:'Not enough same-part-of-speech words for four answer options.'
  }),
  tr:Object.freeze({
    title:'Ашыкъ оюн',modeLabel:'MOD',difficultyLabel:'ZORLUK',cameraLabel:'KAMERA',newGame:'Yeni oyun',computer:'Bilgisayara karşı',online:'Çevrimiçi',easy:'Kolay',normal:'Orta',hard:'Zor',computerAccuracy:'Bilgisayar isabeti',computerAnswers:'Bilgisayar cevapları',shotTime:'Atış süresi',answerTime:'Cevap süresi',seconds:'sn',start:'Oyuna başla',createRoom:'Oda oluştur',connect:'Bağlanıyor…',join:'Katıl',roomCode:'ODA KODU',shareCode:'Kodu ikinci oyuncuya gönderin',loginOnline:'Çevrimiçi oynamak için Alan Til hesabına giriş yapın.',mediumWords:'Kelimeler: “Köklere dönüş” · Orta · Alan → Rusça',
    you:'Siz',computerPlayer:'Bilgisayar',opponent:'Rakip',startLabel:'BAŞLAT',finishLabel:'BİTİŞ',questionLabel:'SORU',computerLabel:'BİLGİSAYAR',bonusShotLabel:'EK ATIŞ',shotLabel:'ATIŞ',shotType:'ATIŞ TÜRÜ',flat:'Düz',hop:'Sıçratma',help:'Kurallar',menu:'Menü',appearance:'Görünüm',currentGame:'Mevcut oyun',inviteSent:'Davet gönderildi',preparingGameStatus:'Oyuna bağlanılıyor',gameInProgress:'Oyun sürüyor',cancelCurrentGame:'Daveti iptal et',resignGame:'Pes et',confirmResign:'Pes edip mevcut oyunu bitirmek istiyor musunuz?',top:'Üstten',orbit:'3D',position:'Yüz',tapHint:'Seçmek için dokun · seçili aşığı sürükleyerek vur',
    tapAction:'Aşık seçimi',flatAction:'Düz atış',hopAction:'Havadan atış',tapActionHelp:'Seçmek için bir aşığa dokunun.',flatActionHelp:'Noktalı düz ok, tahta boyunca doğrudan atışı gösterir.',hopActionHelp:'Noktalı kavisli ok, havadan atışı gösterir.',
    translate:'Kelimeyi çevir',bonusQuestion:'EK ATIŞ İÇİN',answer:'Cevapla',skip:'Geç',computerAnswersNow:'Bilgisayar cevaplıyor…',opponentAnswersNow:'Rakip cevaplıyor…',opponentSubmitted:'Rakip cevabı onayladı',questionRule:'Doğru → +3 ve ek atış\nYanlış → −1\nGeç → cezasız',
    gameOver:'OYUN BİTTİ',draw:'Berabere',won:'kazandı',youWon:'Kazandınız',youLost:'Kaybettiniz',backToPractice:'Pratiğe dön',finalField:'Kazanan son puana göre belirlenir.',
    rules:'Kurallar',helpGoalTitle:'Oyunun amacı',helpGoalText:'Tahtada 10 aşık var. Vuran aşıkla üst yüzü aynı olan aşığa vurun. Aynı yüz = alma.',helpControlsTitle:'3 adımda hamle',helpControlsText:'1. Aşığı seçin. 2. Atışı seçin. 3. Süre bitmeden yön ve gücü ayarlayın.',helpCaptureTitle:'Alma ne zaman sayılır',helpCaptureText:'Atıştan önceki üst yüzler karşılaştırılır: vuran aşık ve ilk değdiği aşık. Aynıysa hedef çıkar ve puan gelir. Üçüncü aşığa temas = alma yok.',helpPenaltyTitle:'Olmazsa',helpPenaltyText:'Hiçbir şeye değmezseniz: −1. Hedefe değip yüz eşleşmezse veya üçüncü aşığa temas ederseniz: 0. Sonra sıra rakibe geçer.',helpFacesTitle:'Yüz = puan',helpFacesText:'Alma, eşleşen üst yüzün değeri kadar puan verir:',helpQuestionsTitle:'Al — sonra cevapla',helpQuestionsText:'Ana atışta alma → kelime sorusu. Doğru: +3 ve bir ek atış. Yanlış: −1. Geçme veya süre bitimi: ceza yok. Ek atış yeni soru açmaz.',helpEndTitle:'Final',helpEndText:'Almadan sonra tahtada bir aşık kalırsa oyun biter. Yüksek puan kazanır.',helpKytTitle:'Özel kural',helpKytText:'Къыт → Къыт = skor ne olursa olsun anında galibiyet.',points:'puan',instantWin:'anında galibiyet',
    faceChyk:'Чыкъ',faceFok:'Фок',faceTau:'Тау',faceAlchi:'Алчы',faceBiy:'Бий',faceKyt:'Къыт',
    rulesGoal:'Tahtada 10 aşık vardır. Geçerli almalarla puan toplayın.',sameFace:'Üst yüzler atıştan önce karşılaştırılır; hedef, vuran aşığın ilk temas ettiği aşıktır.',thirdPiece:'Vuran veya hedef üçüncü bir aşığa değerse alma geçersizdir.',kytWin:'КЪЫТ ile КЪЫТ — anında galibiyet.',bonus:'Ana atıştaki almadan sonra: doğru +3 ve bir ek atış; yanlış −1; geçme cezasızdır.',close:'Kapat',
    statusChoose:'Mod ve zorluk seçin',statusWaiting:'Rakip bekleniyor',statusFinished:'Oyun bitti',statusSettling:'Aşıklar duruluyor',statusComputer:'Bilgisayar atış seçiyor',statusOpponent:'Rakibin sırası',statusSelected:'Aşık seçildi — vurmak için tekrar sürükleyin',statusBonusShot:'Ek atış',statusChoosePiece:'Bir aşık seçin',miss:'Hiçbir aşığa değmedi',faceMismatch:'Yüzler eşleşmedi',thirdTouched:'Üçüncü aşığa değildi',capture:'Eşleşti',correct:'Doğru',wrong:'Yanlış',timeout:'Süre doldu',noPenalty:'cezasız',opponentResigned:'Rakip pes etti',resigned:'Pes ettiniz',opponentDisconnected:'Rakip bağlantıyı kesti · galibiyet',roomError:'Çevrimiçi oyun eşitlenemedi.',questionPoolError:'Dört seçenek için aynı sözcük türünden yeterli kelime yok.'
  })
});
export function ashykLocale(value){return value==='en'||value==='tr'?value:'ru';}
export function ashykMessages(value){return M[ashykLocale(value)];}
export function difficultyLabel(id,locale){const m=ashykMessages(locale);return id==='easy'?m.easy:id==='hard'?m.hard:m.normal;}
