import {formatRating} from '../../../packages/alantil-core/social.js';
import {socialMessage} from '../../../packages/alantil-core/social-i18n.js';
import {createAshykOnlineAdapter} from '../../../packages/ashyk-game/online.js';
import {getInterfaceLanguage} from '../../shared/i18n/index.js?v=13.15.12';
import {escapeHtml} from '../../shared/ui/html.js?v=13.9.0';
import {setPendingAshykInvite} from '../../shared/social/ashyk-handoff.js';
import {acceptFriendRequest,blockUser,declineFriendRequest,fetchFriendsSnapshot,fetchSocialLeaderboard,getSocialClient,getSocialSession,removeFriend,searchSocialUsers,sendFriendRequest,unblockUser} from '../../shared/social/social-service.js';

let controller=null,refreshTimer=0,realtime=null;
const esc=(v)=>escapeHtml(String(v??''));
function t(key,params){return socialMessage(getInterfaceLanguage(),key,params);}
function action(label,kind,data){return `<button class="btn ${kind==='primary'?'actionPrimary':'actionText'} socialAction" type="button" ${Object.entries(data||{}).map(([k,v])=>`data-${k}="${esc(v)}"`).join(' ')}>${esc(label)}</button>`;}
function avatar(gender){return `<span class="socialAvatar ${gender==='female'?'female':'male'}" aria-hidden="true"></span>`;}
function progressRows(stories={}){const rows=Object.entries(stories||{});if(!rows.length)return'';return `<div class="socialStoryProgress"><small>${esc(t('storyProgress'))}</small>${rows.map(([key,row])=>{const p=Math.max(0,Math.min(100,Number(row?.percent)||0));return `<div class="socialStoryRow"><span>${esc(key)}</span><i><b style="width:${p}%"></b></i><em>${p}%</em></div>`;}).join('')}</div>`;}
function userCard(user,{friend=false,actions=''}={}){return `<article class="socialUserCard" data-social-user="${esc(user.user_id)}"><div class="socialUserHead">${avatar(user.avatar_gender)}<div><strong>${esc(user.nickname||'—')}</strong><span>${esc(t('score',{score:formatRating(user.rating_score)}))}</span>${friend?`<span>${esc(t('streak',{count:Number(user.streak_days)||0}))}</span>`:''}</div></div>${friend?progressRows(user.story_progress):''}${actions?`<div class="socialUserActions">${actions}</div>`:''}</article>`;}
function relationActions(user){if(user.relation==='accepted')return'';if(user.relation==='outgoing')return action(t('requested'),'text',{});if(user.relation==='incoming')return action(t('accept'),'primary',{'social-accept-user':user.user_id});return action(t('add'),'primary',{'social-add':user.user_id});}
function section(title,body){return `<section class="socialSection"><h2>${esc(title)}</h2>${body}</section>`;}
function guest(context){context.root.innerHTML=`<section class="view screen socialView"><div class="socialGuest"><h1>${esc(t('friends'))}</h1><p>${esc(t('signIn'))}</p><button class="btn actionPrimary" type="button" data-route="account.home">${esc(t('friends'))}</button></div></section>`;}
function shellHtml(){return `<section class="view screen socialView"><header class="socialHeader"><h1>${esc(t('friends'))}</h1><div class="settingsSegments socialTabs" role="tablist"><button type="button" data-social-tab="friends" class="active">${esc(t('friends'))}</button><button type="button" data-social-tab="rating">${esc(t('rating'))}</button><button type="button" data-social-tab="search">${esc(t('search'))}</button></div></header><div class="socialBody" data-social-body></div></section>`;}
function setBody(context,html){const body=context.root.querySelector('[data-social-body]');if(body)body.innerHTML=html;}
async function renderFriends(context){setBody(context,`<div class="screenState">${esc(t('loading'))}</div>`);const snapshot=await fetchFriendsSnapshot();let html='';if(snapshot.ashyk_invites.length)html+=section(t('invites'),snapshot.ashyk_invites.map((u)=>userCard(u,{actions:action(t('accept'),'primary',{'ashyk-accept':u.invite_id})+action(t('decline'),'text',{'ashyk-decline':u.invite_id})})).join(''));if(snapshot.incoming.length)html+=section(t('requests'),snapshot.incoming.map((u)=>userCard(u,{actions:action(t('accept'),'primary',{'friend-accept':u.friendship_id})+action(t('decline'),'text',{'friend-decline':u.friendship_id})})).join(''));html+=section(t('friends'),snapshot.friends.length?snapshot.friends.map((u)=>userCard(u,{friend:true,actions:action(t('remove'),'text',{'friend-remove':u.user_id})+action(t('block'),'text',{'friend-block':u.user_id})})).join(''):`<p class="socialEmpty">${esc(t('emptyFriends'))}</p>`);if(snapshot.blocked.length)html+=section(t('block'),snapshot.blocked.map((u)=>userCard(u,{actions:action(t('unblock'),'text',{'friend-unblock':u.user_id})})).join(''));setBody(context,html);}
async function renderRating(context){setBody(context,`<div class="screenState">${esc(t('loading'))}</div>`);const rows=await fetchSocialLeaderboard();setBody(context,section(t('rating'),rows.map((u)=>`<div class="socialRankRow"><b>#${Number(u.rank)||1}</b>${userCard(u,{actions:relationActions(u)})}</div>`).join('')));}
async function renderSearch(context,query=''){setBody(context,`<div class="socialSearch"><input type="search" value="${esc(query)}" placeholder="${esc(t('searchPlaceholder'))}" data-social-search /></div><div data-social-results><div class="screenState">${esc(t('loading'))}</div></div>`);const rows=await searchSocialUsers(query);const target=context.root.querySelector('[data-social-results]');if(target)target.innerHTML=section(t('search'),rows.length?rows.map((u)=>userCard(u,{actions:relationActions(u)})).join(''):`<p class="socialEmpty">${esc(t('emptySearch'))}</p>`);}
async function mutate(context,fn,mode){try{await fn();await renderMode(context,mode);}catch(error){setBody(context,`<div class="errorState">${esc(error?.message||t('error'))}</div>`);}}
async function renderMode(context,mode){context.root.querySelectorAll('[data-social-tab]').forEach((b)=>b.classList.toggle('active',b.dataset.socialTab===mode));context.root.dataset.socialMode=mode;if(mode==='rating')return renderRating(context);if(mode==='search')return renderSearch(context);return renderFriends(context);}
function bind(context){context.root.addEventListener('click',async(event)=>{const tab=event.target.closest('[data-social-tab]');if(tab){await renderMode(context,tab.dataset.socialTab);return;}const node=event.target.closest('button');if(!node)return;const mode=context.root.dataset.socialMode||'friends';if(node.dataset.socialAdd)await mutate(context,()=>sendFriendRequest(node.dataset.socialAdd),mode);else if(node.dataset.friendAccept)await mutate(context,()=>acceptFriendRequest(node.dataset.friendAccept),mode);else if(node.dataset.friendDecline)await mutate(context,()=>declineFriendRequest(node.dataset.friendDecline),mode);else if(node.dataset.friendRemove)await mutate(context,()=>removeFriend(node.dataset.friendRemove),mode);else if(node.dataset.friendBlock)await mutate(context,()=>blockUser(node.dataset.friendBlock),mode);else if(node.dataset.friendUnblock)await mutate(context,()=>unblockUser(node.dataset.friendUnblock),mode);else if(node.dataset.ashykAccept){try{const client=await getSocialClient(),online=createAshykOnlineAdapter(client),result=await online.acceptInvite(node.dataset.ashykAccept);if(result?.room){setPendingAshykInvite(result);await context.router.navigate('practice.ashyk');}}catch(error){setBody(context,`<div class="errorState">${esc(error?.message||t('error'))}</div>`);}}else if(node.dataset.ashykDecline){const client=await getSocialClient(),online=createAshykOnlineAdapter(client);await mutate(context,()=>online.declineInvite(node.dataset.ashykDecline),mode);}}, {signal:controller.signal});context.root.addEventListener('input',(event)=>{const input=event.target.closest('[data-social-search]');if(!input)return;clearTimeout(refreshTimer);refreshTimer=setTimeout(()=>void renderSearch(context,input.value),300);},{signal:controller.signal});}
export async function mount(context){controller=new AbortController();context.shell.setHeaderContent?.({title:'Alan Til!'});const session=await getSocialSession().catch(()=>null);if(!session?.user){guest(context);return;}context.root.innerHTML=shellHtml();context.root.dataset.socialMode='friends';bind(context);await renderFriends(context);const client=await getSocialClient();realtime=client.channel(`friends-view:${session.user.id}:${Date.now()}`).on('postgres_changes',{event:'*',schema:'public',table:'friendships'},()=>{clearTimeout(refreshTimer);refreshTimer=setTimeout(()=>void renderMode(context,context.root.dataset.socialMode||'friends'),100);}).on('postgres_changes',{event:'*',schema:'public',table:'ashyk_invites'},()=>{clearTimeout(refreshTimer);refreshTimer=setTimeout(()=>void renderMode(context,context.root.dataset.socialMode||'friends'),100);}).subscribe();}
export function unmount(){controller?.abort();controller=null;clearTimeout(refreshTimer);refreshTimer=0;if(realtime){try{realtime.unsubscribe();}catch{}realtime=null;}}
