import {formatRating} from '../../../packages/alantil-core/social.js';
import {socialMessage} from '../../../packages/alantil-core/social-i18n.js?v=16.7.0.2';
import {createAshykOnlineAdapter} from '../../../packages/ashyk-game/online.js?v=16.7.0.2';
import {getInterfaceLanguage} from '../../shared/i18n/index.js?v=13.15.12';
import {escapeHtml} from '../../shared/ui/html.js?v=13.9.0';
import {renderBracketTabs} from '../../shared/ui/profile-navigation.js?v=16.7.0';
import {hasActivityAccess,refreshActivityAccessForUser,whenActivityAccessReady} from '../../shared/admin/admin-access.js?v=16.7.0';
import {setPendingAshykInvite} from '../../shared/social/ashyk-handoff.js';
import {acceptFriendRequest,blockUser,declineFriendRequest,fetchFriendsSnapshot,fetchSocialLeaderboard,getSocialClient,getSocialSession,removeFriend,searchSocialUsers,sendFriendRequest,unblockUser} from '../../shared/social/social-service.js';
import {renderAdminUsersEmbedded} from '../admin/index.js?v=16.7.0';

let controller=null,refreshTimer=0,realtime=null,searchTimer=0,statsAccessState='checking';
const esc=(v)=>escapeHtml(String(v??''));
function t(key,params){return socialMessage(getInterfaceLanguage(),key,params);}

function iconButton(label,kind,data,svg){return `<button class="iconAction ${kind}" type="button" aria-label="${esc(label)}" title="${esc(label)}" ${Object.entries(data||{}).map(([k,v])=>`data-${k}="${esc(v)}"`).join(' ')}>${svg}</button>`;}
const ICON={
  add:'<svg viewBox="0 0 24 24" aria-hidden="true"><circle cx="9" cy="9" r="4"/><path d="M2.5 20.5c0-3.6 2.9-6 6.5-6s6.5 2.4 6.5 6"/><path d="M18 8v6M15 11h6"/></svg>',
  accept:'<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M4 12.5 9.5 18 20 6"/></svg>',
  decline:'<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M6 6l12 12M18 6 6 18"/></svg>',
  pending:'<svg viewBox="0 0 24 24" aria-hidden="true"><circle cx="12" cy="12" r="8.5"/><path d="M12 7.5V12l3 2.2"/></svg>',
  friend:'<svg viewBox="0 0 24 24" aria-hidden="true"><circle cx="12" cy="12" r="9"/><path d="M7.5 12.5 10.3 15.5 16.5 9"/></svg>',
  remove:'<svg viewBox="0 0 24 24" aria-hidden="true"><circle cx="9" cy="9" r="4"/><path d="M2.5 20.5c0-3.6 2.9-6 6.5-6s6.5 2.4 6.5 6"/><path d="M15 11h6"/></svg>',
  block:'<svg viewBox="0 0 24 24" aria-hidden="true"><circle cx="12" cy="12" r="9"/><path d="m6 6 12 12"/></svg>',
  unblock:'<svg viewBox="0 0 24 24" aria-hidden="true"><circle cx="12" cy="12" r="9"/><path d="M8 12h8"/></svg>',
  search:'<svg viewBox="0 0 24 24" aria-hidden="true"><circle cx="11" cy="11" r="7"/><path d="m20 20-4-4"/></svg>',
};
function genderIcon(gender){const cls=gender==='female'?'female':'male';return `<span class="genderIcon ${cls}" aria-hidden="true"><svg viewBox="0 0 24 24"><circle cx="12" cy="8" r="4.2"/><path d="M6 20a6 6 0 0 1 12 0"/></svg></span>`;}
function medalIcon(rank){if(rank<1||rank>3)return '';return `<svg class="rankMedal medal${rank}" viewBox="0 0 24 24" aria-hidden="true"><path d="M7 2h4l1 5-4.4 3.1L4 2h3Z"/><path d="M13 2h4l3 8.1L15.6 7 13 2Z"/><circle cx="12" cy="15" r="5.2"/></svg>`;}
function relationActions(user){if(user.relation==='accepted')return iconButton(t('friends'),'neutral disabled',{},ICON.friend);if(user.relation==='outgoing')return iconButton(t('requested'),'neutral disabled',{},ICON.pending);if(user.relation==='incoming')return user.friendship_id?`${iconButton(t('accept'),'primary',{'friend-accept':user.friendship_id},ICON.accept)}${iconButton(t('decline'),'ghost',{'friend-decline':user.friendship_id},ICON.decline)}`:'';return iconButton(t('add'),'primary',{'social-add':user.user_id},ICON.add);}
function compactRow({rank=0,nickname,gender,rightValue='',secondary='',actions=''}){return `<div class="socialRow">${rank?`<span class="socialRank">${medalIcon(rank)||`#${rank}`}</span>`:''}<div class="socialRowBody"><div class="socialRowName">${genderIcon(gender)}<strong>${esc(nickname||'—')}</strong></div>${secondary?`<span class="socialRowMeta">${secondary}</span>`:''}</div>${rightValue?`<span class="socialRowValue">${rightValue}</span>`:''}<div class="socialRowActions">${actions}</div></div>`;}
function section(title,body){return body?`<section class="socialSection"><h2>${esc(title)}</h2>${body}</section>`:'';}
function searchToggleHtml(){return `<button class="iconAction ghost socialSearchToggle" type="button" data-social-search-toggle aria-label="${esc(t('search'))}" title="${esc(t('search'))}">${ICON.search}</button>`;}
function searchFieldHtml(query=''){return `<div class="socialSearchField" data-social-search-field><input type="search" value="${esc(query)}" placeholder="${esc(t('searchPlaceholder'))}" data-social-search autocomplete="off"/></div>`;}

function guest(context){context.root.innerHTML=`<section class="view screen socialView socialGuestView"><div class="socialGuest"><strong class="socialGuestTitle">${esc(t('community'))}</strong><p>${esc(t('signIn'))}</p><button class="btn actionPrimary" type="button" data-route="account.home">${esc(t('signInAction'))}</button></div></section>`;}
function tabsHtml(active='rating'){const items=[{id:'rating',label:t('rating')},{id:'friends',label:t('friends')},{id:'stats',label:t('extendedStats')}];return renderBracketTabs({items,active,ariaLabel:t('community'),dataAttribute:'social-tab'});}
function shellHtml(active='rating'){return `<section class="view screen socialView"><header class="socialHeader" data-social-header>${tabsHtml(active)}</header><div class="socialBody" data-social-body></div></section>`;}
function syncTabs(context){const header=context.root.querySelector('[data-social-header]');if(!header)return;header.innerHTML=tabsHtml(context.root.dataset.socialMode||'rating');}
function setBody(context,html){const body=context.root.querySelector('[data-social-body]');if(body)body.innerHTML=html;}
function setModeVisual(context,mode){context.root.dataset.socialMode=mode;context.root.querySelector('[data-social-body]')?.classList.toggle('isStats',mode==='stats');context.root.querySelectorAll('[data-social-tab]').forEach((b)=>{const active=b.dataset.socialTab===mode;b.classList.toggle('active',active);if(active)b.setAttribute('aria-current','page');else b.removeAttribute('aria-current');});}

async function renderFriends(context){setBody(context,`<div class="screenState">${esc(t('loading'))}</div>`);const snapshot=await fetchFriendsSnapshot();let html='';if(snapshot.ashyk_invites.length)html+=section(t('invites'),snapshot.ashyk_invites.map((u)=>compactRow({nickname:u.nickname,gender:u.avatar_gender,actions:`${iconButton(t('accept'),'primary',{'ashyk-accept':u.invite_id},ICON.accept)}${iconButton(t('decline'),'ghost',{'ashyk-decline':u.invite_id},ICON.decline)}`})).join(''));if(snapshot.incoming.length)html+=section(t('requests'),snapshot.incoming.map((u)=>compactRow({nickname:u.nickname,gender:u.avatar_gender,actions:`${iconButton(t('accept'),'primary',{'friend-accept':u.friendship_id},ICON.accept)}${iconButton(t('decline'),'ghost',{'friend-decline':u.friendship_id},ICON.decline)}`})).join(''));html+=section(t('friends'),snapshot.friends.length?snapshot.friends.map((u)=>compactRow({nickname:u.nickname,gender:u.avatar_gender,secondary:esc(t('streak',{count:Number(u.streak_days)||0})),actions:`${iconButton(t('remove'),'ghost',{'friend-remove':u.user_id},ICON.remove)}${iconButton(t('block'),'ghost',{'friend-block':u.user_id},ICON.block)}`})).join(''):`<p class="socialEmpty">${esc(t('emptyFriends'))}</p>`);if(snapshot.blocked.length)html+=section(t('blocked'),snapshot.blocked.map((u)=>compactRow({nickname:u.nickname,gender:u.avatar_gender,actions:iconButton(t('unblock'),'ghost',{'friend-unblock':u.user_id},ICON.unblock)})).join(''));setBody(context,html);}
function bindSearchInput(context){const input=context.root.querySelector('[data-social-search]');if(!input)return;const caret=input.value.length;input.focus();try{input.setSelectionRange(caret,caret);}catch{}input.addEventListener('input',()=>{const value=input.value;context.root.dataset.socialQuery=value;clearTimeout(searchTimer);searchTimer=setTimeout(()=>void renderRating(context,value),280);},{signal:controller.signal});}
async function renderRating(context,query=''){const activeQuery=String(query||'').trim(),showField=context.root.dataset.socialSearchOpen==='true';setBody(context,`<div class="socialSearchBar">${searchToggleHtml()}${showField?searchFieldHtml(query):''}</div><div data-social-rating-body><div class="screenState">${esc(t('loading'))}</div></div>`);if(showField)bindSearchInput(context);const target=()=>context.root.querySelector('[data-social-rating-body]');if(activeQuery){const rows=await searchSocialUsers(activeQuery);if(target())target().innerHTML=section(t('rating'),rows.length?rows.map((u)=>compactRow({nickname:u.nickname,gender:u.avatar_gender,rightValue:esc(formatRating(u.rating_score)),actions:u.user_id===context.selfId?'':relationActions(u)})).join(''):`<p class="socialEmpty">${esc(t('emptySearch'))}</p>`);return;}const rows=await fetchSocialLeaderboard();if(target())target().innerHTML=section(t('rating'),rows.map((u,index)=>compactRow({rank:Number(u.rank)||index+1,nickname:u.nickname,gender:u.avatar_gender,rightValue:esc(formatRating(u.rating_score)),actions:u.user_id===context.selfId?'':relationActions(u)})).join(''));}
async function renderStats(context){if(statsAccessState==='checking'){setBody(context,`<div class="loadingState">${esc(t('loading'))}</div>`);return;}if(statsAccessState!=='allowed'){context.router.canonicalize('friends.home',{});setModeVisual(context,'rating');return renderRating(context,'');}const body=context.root.querySelector('[data-social-body]');if(!body)return;body.innerHTML='<div class="adminUsersEmbedded" data-admin-users-embedded></div>';const host=body.querySelector('[data-admin-users-embedded]');await renderAdminUsersEmbedded(context,controller.signal,host);}
async function mutate(context,fn,mode){try{await fn();await renderMode(context,mode);}catch(error){setBody(context,`<div class="errorState">${esc(error?.message||t('error'))}</div>`);}}
async function renderMode(context,mode){const safeMode=['rating','friends','stats'].includes(mode)?mode:'rating';setModeVisual(context,safeMode);if(safeMode==='stats')return renderStats(context);if(safeMode==='rating')return renderRating(context,context.root.dataset.socialQuery||'');return renderFriends(context);}
function selectMode(context,mode){context.root.dataset.socialSearchOpen='false';context.root.dataset.socialQuery='';context.router.canonicalize('friends.home',mode==='stats'?{mode:'stats'}:mode==='friends'?{mode:'friends'}:{});return renderMode(context,mode);}
function bind(context){context.root.addEventListener('click',async(event)=>{const tab=event.target.closest('[data-social-tab]');if(tab){await selectMode(context,tab.dataset.socialTab);return;}const searchToggle=event.target.closest('[data-social-search-toggle]');if(searchToggle){const open=context.root.dataset.socialSearchOpen==='true';context.root.dataset.socialSearchOpen=String(!open);if(open)context.root.dataset.socialQuery='';await renderRating(context,context.root.dataset.socialQuery||'');return;}const node=event.target.closest('button');if(!node)return;const mode=context.root.dataset.socialMode||'rating';if(node.dataset.socialAdd)await mutate(context,()=>sendFriendRequest(node.dataset.socialAdd),mode);else if(node.dataset.friendAccept)await mutate(context,()=>acceptFriendRequest(node.dataset.friendAccept),mode);else if(node.dataset.friendDecline)await mutate(context,()=>declineFriendRequest(node.dataset.friendDecline),mode);else if(node.dataset.friendRemove)await mutate(context,()=>removeFriend(node.dataset.friendRemove),mode);else if(node.dataset.friendBlock)await mutate(context,()=>blockUser(node.dataset.friendBlock),mode);else if(node.dataset.friendUnblock)await mutate(context,()=>unblockUser(node.dataset.friendUnblock),mode);else if(node.dataset.ashykAccept){try{const client=await getSocialClient(),online=createAshykOnlineAdapter(client),result=await online.acceptInvite(node.dataset.ashykAccept);if(result?.room){setPendingAshykInvite(result);await context.router.navigate('practice.ashyk');}}catch(error){setBody(context,`<div class="errorState">${esc(error?.message||t('error'))}</div>`);}}else if(node.dataset.ashykDecline){const client=await getSocialClient(),online=createAshykOnlineAdapter(client);await mutate(context,()=>online.declineInvite(node.dataset.ashykDecline),mode);}},{signal:controller.signal});window.addEventListener('alantil:activity-access',(event)=>{statsAccessState=event.detail?.enabled===true?'allowed':'denied';syncTabs(context);if(context.root.dataset.socialMode==='stats'){if(statsAccessState!=='allowed')context.router.canonicalize('friends.home',{});void renderMode(context,statsAccessState==='allowed'?'stats':'rating');}},{signal:controller.signal});}
export async function mount(context,params={}){controller=new AbortController();statsAccessState='checking';context.shell.setHeaderContent?.({title:'Alan Til!'});const session=await getSocialSession().catch(()=>null);if(!session?.user){if(params.mode==='stats')context.router.canonicalize('friends.home',{});guest(context);return;}context.selfId=session.user.id;const initialMode=['friends','stats'].includes(params.mode)?params.mode:'rating';context.root.innerHTML=shellHtml(initialMode);context.root.dataset.socialMode=initialMode;context.root.dataset.socialSearchOpen='false';context.root.dataset.socialQuery='';bind(context);const initialRender=renderMode(context,initialMode);const allowed=await refreshActivityAccessForUser(context.selfId).catch(()=>false);if(controller.signal.aborted)return;statsAccessState=allowed?'allowed':'denied';if(initialMode==='stats'){if(!allowed)context.router.canonicalize('friends.home',{});await renderMode(context,allowed?'stats':'rating');}else await initialRender;const signal=controller.signal;void whenActivityAccessReady().then(()=>{if(signal.aborted)return;statsAccessState=hasActivityAccess()?'allowed':'denied';syncTabs(context);if(context.root.dataset.socialMode==='stats'){if(statsAccessState!=='allowed')context.router.canonicalize('friends.home',{});void renderMode(context,statsAccessState==='allowed'?'stats':'rating');}});const client=await getSocialClient();realtime=client.channel(`friends-view:${session.user.id}:${Date.now()}`).on('postgres_changes',{event:'*',schema:'public',table:'friendships'},()=>{clearTimeout(refreshTimer);refreshTimer=setTimeout(()=>void renderMode(context,context.root.dataset.socialMode||'rating'),100);}).on('postgres_changes',{event:'*',schema:'public',table:'ashyk_invites'},()=>{clearTimeout(refreshTimer);refreshTimer=setTimeout(()=>void renderMode(context,context.root.dataset.socialMode||'rating'),100);}).subscribe();}
export function unmount(){controller?.abort();controller=null;statsAccessState='checking';clearTimeout(refreshTimer);refreshTimer=0;clearTimeout(searchTimer);searchTimer=0;if(realtime){try{realtime.unsubscribe();}catch{}realtime=null;}}
