import { trackEvent } from "../../shared/analytics/analytics.js?v=16.8.0.2";
import { ACTIVITY_TYPES, CANCEL_REASONS, EVENTS, WORD_RESULTS, WORD_SOURCES, directionFromMode } from "../../shared/analytics/events.js?v=16.8.0.2";
import { createActivityTracker } from "../../shared/analytics/session-tracker.js?v=16.8.0.2";
import { createSessionRuntime, finalizeSessionRuntime, persistSessionRuntime, suspendSessionRuntime } from "../../shared/progress/session-builders.js?v=16.8.0.2";
import { clearPracticeSnapshot, loadPracticeSnapshot, savePracticeSnapshot } from "../../shared/state/practice-snapshot-store.js?v=16.8.0.2";
import { testState } from "./state.js?v=16.8.0.2";
import { recordTestWordResults } from "../../shared/progress/word-progress-store.js?v=16.8.0.2";
import { applyTestAnswer, buildTestOptions, initializeTestState, restoreTestStateSnapshot, testAbandonSummary, testCompletionSummary, testSessionPayload, testStateSnapshot } from "../../../packages/alantil-core/test.js";

function persistTestSession(){persistSessionRuntime(testState.session.runtime,testSessionPayload(testState));const snapshot=testStateSnapshot(testState);if(snapshot)savePracticeSnapshot("test",snapshot);}
function attachRuntime(metadata={},startedAt=null){testState.session.runtime=testState.items.length?createSessionRuntime("test",{selected_sources:Array.isArray(metadata.selectedSources)?metadata.selectedSources:[],direction:directionFromMode(testState.mode)}):null;testState.session.id=testState.session.runtime?.id||null;testState.session.startedAt=startedAt||new Date().toISOString();testState.session.tracker=testState.items.length?createActivityTracker(ACTIVITY_TYPES.TEST):null;testState.session.tracker?.start({direction:directionFromMode(testState.mode),limit:testState.limit,items_total:testState.items.length,items_completed:testState.index,questions_total:testState.items.length,questions_answered:testState.index,dictionary_count:metadata.dictionaryCount||0,section_count:metadata.sectionCount||0});}
export function resumeTestSession(words){const snapshot=loadPracticeSnapshot("test");if(!snapshot)return false;const restored=restoreTestStateSnapshot(snapshot,words,words);if(!restored){clearPracticeSnapshot("test");return false;}Object.assign(testState,restored);attachRuntime(testState.session.metadata||{},snapshot.startedAt||null);persistTestSession();return true;}
export function finalizeTestSession(status="interrupted",exitReason="route_change"){const session=testState.session;if(!session.runtime||session.runtime.finalized)return false;const payload=testSessionPayload(testState),result=finalizeSessionRuntime(session.runtime,{status,exitReason,payload});if(result?.id&&payload.words.length){const accuracy=payload.questions_answered?Math.round((payload.correct_total/payload.questions_answered)*100):0;recordTestWordResults({sessionId:result.id,answers:payload.words,accuracy,requiredAccuracy:80,updateMastery:false,completedAt:result.ended_at||new Date().toISOString()});}session.inProgress=false;session.completed=status==="completed";if(status==="completed"||exitReason===CANCEL_REASONS.NEW_SESSION)clearPracticeSnapshot("test");return result;}
function abandonPreviousSession(){if(testState.session.runtime&&!testState.session.runtime.finalized)finalizeTestSession("interrupted",CANCEL_REASONS.NEW_SESSION);const tracker=testState.session.tracker;if(tracker?.getStatus()==="active")tracker.abandon(CANCEL_REASONS.NEW_SESSION,testAbandonSummary(testState));clearPracticeSnapshot("test");}
export function startTest(pool,mode,limit,metadata={},optionPool=pool){abandonPreviousSession();initializeTestState(testState,pool,mode,limit,metadata,optionPool);attachRuntime(metadata);persistTestSession();}
export function pickOptions(item){return buildTestOptions(testState,item);}
export function submitAnswer(answer){const transition=applyTestAnswer(testState,answer);if(!transition)return false;const{item,isCorrect}=transition;trackEvent(EVENTS.WORD_RESULT,{word_id:item.id,source:WORD_SOURCES.TEST,result:isCorrect?WORD_RESULTS.CORRECT:WORD_RESULTS.WRONG,dictionary_id:item.dictionary_id,section_id:item.section_id,set_id:String(item.set_id),direction:directionFromMode(testState.mode)});persistTestSession();return true;}
export function completeTest(){if(!testState.session.inProgress||testState.session.completed)return false;finalizeTestSession("completed",null);return testState.session.tracker?.complete(testCompletionSummary(testState))||false;}
export function suspendTestForResume(){if(!testState.session.inProgress)return false;persistTestSession();suspendSessionRuntime(testState.session.runtime);testState.session.inProgress=false;return true;}