-- Alan Til 16.6.7: canonical songs storage + one-time legacy Google Sheets import.
-- Google Sheets is used only by this historical migration; application runtime reads Supabase.
create extension if not exists http with schema extensions;

create table if not exists public.songs (
  id text primary key,
  slug text unique,
  title_alan_cyrillic text not null,
  title_alan_turkic text,
  title_ru text,
  title_en text,
  title_tr text,
  author text,
  performer text,
  source text,
  category text,
  playlist_id text,
  playlist_title text,
  playlist_description text,
  playlist_order integer,
  info text,
  cover_url text,
  metadata jsonb not null default '{}'::jsonb,
  sort_order integer not null default 0,
  is_published boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.song_lines (
  id bigint generated by default as identity primary key,
  song_id text not null references public.songs(id) on delete cascade,
  line_order integer not null check (line_order > 0),
  text_alan_cyrillic text,
  text_alan_turkic text,
  text_ru text,
  text_en text,
  text_tr text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint song_lines_song_order_key unique (song_id, line_order)
);

create index if not exists song_lines_song_id_line_order_idx on public.song_lines(song_id,line_order);
create index if not exists songs_published_sort_order_idx on public.songs(is_published,sort_order,id);

alter table public.songs enable row level security;
alter table public.song_lines enable row level security;
revoke all on public.songs from anon,authenticated;
revoke all on public.song_lines from anon,authenticated;
grant select on public.songs to anon,authenticated;
grant select on public.song_lines to anon,authenticated;
drop policy if exists songs_public_read on public.songs;
drop policy if exists song_lines_public_read on public.song_lines;
create policy songs_public_read on public.songs for select to anon,authenticated using (is_published=true);
create policy song_lines_public_read on public.song_lines for select to anon,authenticated using (exists(select 1 from public.songs s where s.id=song_lines.song_id and s.is_published=true));

create temporary table _songs_legacy_stage (
  id text,playlist_id text,playlist_title text,playlist_description text,playlist_order text,
  title text,artist text,audio_url text,lyrics text,translation text,info text,song_order text,
  cover_url text,metadata text
) on commit drop;

do $migration$
declare
  body text; pos integer:=1; n integer; ch text; nxt text; fld text:='';
  rowv text[]:=array[]::text[]; quoted boolean:=false; row_no integer:=0;
begin
  select content into body from extensions.http_get('https://docs.google.com/spreadsheets/d/1aQseG2yQfeZiAbxX0dmhnoP7IkoR4w-N/export?format=csv') where status=200;
  if body is null then raise exception 'Legacy songs CSV could not be fetched'; end if;
  n:=length(body);
  while pos<=n loop
    ch:=substr(body,pos,1); nxt:=case when pos<n then substr(body,pos+1,1) else '' end;
    if quoted then
      if ch='"' and nxt='"' then fld:=fld||'"'; pos:=pos+2;
      elsif ch='"' then quoted:=false; pos:=pos+1;
      else fld:=fld||ch; pos:=pos+1; end if;
    else
      if ch='"' then quoted:=true; pos:=pos+1;
      elsif ch=',' then rowv:=array_append(rowv,fld); fld:=''; pos:=pos+1;
      elsif ch=E'\n' or ch=E'\r' then
        rowv:=array_append(rowv,fld); fld:=''; row_no:=row_no+1;
        if row_no>1 and coalesce(rowv[1],'')<>'' then
          while coalesce(array_length(rowv,1),0)<14 loop rowv:=array_append(rowv,''); end loop;
          insert into _songs_legacy_stage values(rowv[1],rowv[2],rowv[3],rowv[4],rowv[5],rowv[6],rowv[7],rowv[8],rowv[9],rowv[10],rowv[11],rowv[12],rowv[13],rowv[14]);
        end if;
        rowv:=array[]::text[];
        if ch=E'\r' and nxt=E'\n' then pos:=pos+2; else pos:=pos+1; end if;
      else fld:=fld||ch; pos:=pos+1; end if;
    end if;
  end loop;
  if fld<>'' or coalesce(array_length(rowv,1),0)>0 then
    rowv:=array_append(rowv,fld); row_no:=row_no+1;
    if row_no>1 and coalesce(rowv[1],'')<>'' then
      while coalesce(array_length(rowv,1),0)<14 loop rowv:=array_append(rowv,''); end loop;
      insert into _songs_legacy_stage values(rowv[1],rowv[2],rowv[3],rowv[4],rowv[5],rowv[6],rowv[7],rowv[8],rowv[9],rowv[10],rowv[11],rowv[12],rowv[13],rowv[14]);
    end if;
  end if;
end
$migration$;

insert into public.songs(id,slug,title_alan_cyrillic,performer,source,category,playlist_id,playlist_title,playlist_description,playlist_order,info,cover_url,metadata,sort_order,is_published)
select trim(id),lower(regexp_replace(trim(id),'[^a-zA-Z0-9]+','-','g')),coalesce(nullif(trim(title),''),trim(id)),nullif(trim(artist),''),'legacy_google_sheets',nullif(trim(playlist_id),''),nullif(trim(playlist_id),''),nullif(trim(playlist_title),''),nullif(trim(playlist_description),''),case when trim(playlist_order)~'^\d+$' then trim(playlist_order)::integer end,nullif(trim(info),''),nullif(trim(cover_url),''),case when nullif(trim(metadata),'') is null then '{}'::jsonb else jsonb_build_object('legacy',metadata) end,case when trim(song_order)~'^\d+$' then trim(song_order)::integer else 0 end,true
from _songs_legacy_stage
on conflict(id) do update set title_alan_cyrillic=excluded.title_alan_cyrillic,performer=excluded.performer,source=excluded.source,category=excluded.category,playlist_id=excluded.playlist_id,playlist_title=excluded.playlist_title,playlist_description=excluded.playlist_description,playlist_order=excluded.playlist_order,info=excluded.info,cover_url=excluded.cover_url,metadata=excluded.metadata,sort_order=excluded.sort_order,updated_at=now();

delete from public.song_lines where song_id in(select trim(id) from _songs_legacy_stage);
with prepared as(
  select trim(id) song_id,
    regexp_split_to_array(replace(replace(coalesce(lyrics,''),E'\r\n',E'\n'),E'\r',E'\n'),E'\n') lyrics_arr,
    regexp_split_to_array(replace(replace(coalesce(translation,''),E'\r\n',E'\n'),E'\r',E'\n'),E'\n') translation_arr
  from _songs_legacy_stage
),expanded as(
  select p.song_id,g line_order,nullif(p.lyrics_arr[g],'') lyric_line,nullif(p.translation_arr[g],'') translation_line
  from prepared p cross join lateral generate_series(1,greatest(cardinality(p.lyrics_arr),cardinality(p.translation_arr),1)) g
)
insert into public.song_lines(song_id,line_order,text_alan_cyrillic,text_ru)
select song_id,line_order,lyric_line,translation_line from expanded order by song_id,line_order;

create or replace view public.v_songs_app with (security_invoker=true) as
select s.id,s.slug,s.title_alan_cyrillic,s.title_alan_turkic,s.title_ru,s.title_en,s.title_tr,s.author,s.performer,s.source,s.category,s.playlist_id,s.playlist_title,s.playlist_description,s.playlist_order,s.info,s.cover_url,s.metadata,s.sort_order,s.updated_at,
  case when bool_or(l.text_alan_cyrillic is not null) then string_agg(coalesce(l.text_alan_cyrillic,''),E'\n' order by l.line_order) end lyrics_alan_cyrillic,
  case when bool_or(l.text_alan_turkic is not null) then string_agg(coalesce(l.text_alan_turkic,''),E'\n' order by l.line_order) end lyrics_alan_turkic,
  case when bool_or(l.text_ru is not null) then string_agg(coalesce(l.text_ru,''),E'\n' order by l.line_order) end lyrics_ru,
  case when bool_or(l.text_en is not null) then string_agg(coalesce(l.text_en,''),E'\n' order by l.line_order) end lyrics_en,
  case when bool_or(l.text_tr is not null) then string_agg(coalesce(l.text_tr,''),E'\n' order by l.line_order) end lyrics_tr
from public.songs s left join public.song_lines l on l.song_id=s.id where s.is_published=true group by s.id;
revoke all on public.v_songs_app from anon,authenticated;
grant select on public.v_songs_app to anon,authenticated;
