begin;

create or replace function public.ashyk_submit_action(p_room_id uuid,p_expected_revision bigint,p_expected_phase_seq bigint,p_action_id text,p_action_type text,p_state jsonb,p_next_active_user_id uuid,p_status text default 'playing') returns public.ashyk_rooms language plpgsql security definer set search_path='' as $$
declare v_actor uuid:=auth.uid();v_room public.ashyk_rooms;v_other uuid;v_actor_index integer;v_other_index integer;v_actor_player integer;v_next_player integer;v_old_scores jsonb;v_new_scores jsonb;v_old_actor_score integer;v_new_actor_score integer;v_old_other_score integer;v_new_other_score integer;v_delta integer;v_old_remaining integer;v_new_remaining integer;v_next_phase text;v_clean_state jsonb;v_winner_player integer;v_winner_user uuid;v_turn_no bigint;
begin
if v_actor is null then raise exception 'authentication required' using errcode='42501';end if;if coalesce(trim(p_action_id),'')='' then raise exception 'missing action id';end if;if p_action_type not in ('shot_result','answer_correct','answer_wrong','skip') then raise exception 'invalid action type';end if;if p_status not in ('playing','finished') then raise exception 'invalid room status';end if;select * into v_room from public.ashyk_rooms where id=p_room_id for update;if v_room.id is null then raise exception 'room not found' using errcode='P0002';end if;if v_actor<>v_room.host_user_id and v_actor is distinct from v_room.guest_user_id then raise exception 'not a room member' using errcode='42501';end if;if exists(select 1 from public.ashyk_action_log l where l.room_id=p_room_id and l.action_id=p_action_id) then return v_room;end if;if v_room.status<>'playing' then raise exception 'room is not playing' using errcode='P0001';end if;if v_actor<>v_room.active_user_id then raise exception 'not your turn' using errcode='42501';end if;if v_room.revision<>p_expected_revision then raise exception 'stale room revision' using errcode='40001';end if;if v_room.phase_seq<>p_expected_phase_seq then raise exception 'stale room phase' using errcode='40001';end if;if v_room.phase_deadline_at is not null and v_room.phase_deadline_at<=now() then return private.ashyk_resolve_timeout_locked(p_room_id);end if;
v_other:=case when v_actor=v_room.host_user_id then v_room.guest_user_id else v_room.host_user_id end;if v_other is null then raise exception 'opponent missing' using errcode='P0001';end if;if p_next_active_user_id<>v_room.host_user_id and p_next_active_user_id is distinct from v_room.guest_user_id then raise exception 'invalid next player';end if;v_actor_index:=case when v_actor=v_room.host_user_id then 0 else 1 end;v_other_index:=case when v_actor_index=0 then 1 else 0 end;v_actor_player:=v_actor_index+1;v_next_player:=case when p_next_active_user_id=v_room.host_user_id then 1 else 2 end;v_old_scores:=coalesce(v_room.game_state->'scores','[0,0]'::jsonb);v_new_scores:=coalesce(p_state->'scores',v_old_scores);if jsonb_typeof(v_old_scores)<>'array' or jsonb_typeof(v_new_scores)<>'array' or jsonb_array_length(v_old_scores)<2 or jsonb_array_length(v_new_scores)<2 then raise exception 'invalid scores';end if;v_old_actor_score:=coalesce((v_old_scores->>v_actor_index)::integer,0);v_new_actor_score:=coalesce((v_new_scores->>v_actor_index)::integer,0);v_old_other_score:=coalesce((v_old_scores->>v_other_index)::integer,0);v_new_other_score:=coalesce((v_new_scores->>v_other_index)::integer,0);if v_old_other_score<>v_new_other_score then raise exception 'opponent score mutation rejected';end if;v_delta:=v_new_actor_score-v_old_actor_score;v_old_remaining:=coalesce((v_room.game_state->>'remainingAshyks')::integer,10);v_new_remaining:=coalesce((p_state->>'remainingAshyks')::integer,v_old_remaining);if v_new_remaining<1 or v_new_remaining>v_old_remaining or v_old_remaining-v_new_remaining>1 then raise exception 'invalid remaining pieces';end if;v_next_phase:=coalesce(p_state->>'phase','first-shot');if v_next_phase not in ('first-shot','bonus-question','bonus-shot') then raise exception 'invalid next phase';end if;
if p_action_type='shot_result' then if v_room.phase not in ('first-shot','bonus-shot') then raise exception 'shot not allowed in this phase';end if;if v_delta not in (-1,0,1,2,3,4,6,15) then raise exception 'invalid shot score delta';end if;if v_delta>0 and v_old_remaining-v_new_remaining<>1 then raise exception 'capture must remove one piece';end if;if v_delta<0 and v_old_remaining<>v_new_remaining then raise exception 'miss cannot remove a piece';end if;if p_status='finished' then if not (coalesce((p_state->>'winByKyt')::boolean,false) or v_new_remaining<=1) then raise exception 'invalid finish';end if;if coalesce((p_state->>'winByKyt')::boolean,false) and v_delta<>0 then raise exception 'kyt win cannot change score';end if;if p_next_active_user_id<>v_actor then raise exception 'finished action must remain with actor';end if;elsif v_next_phase='bonus-question' then if v_room.phase<>'first-shot' or p_next_active_user_id<>v_actor or v_delta<=0 or v_old_remaining-v_new_remaining<>1 or p_state->'question' is null then raise exception 'invalid bonus question transition';end if;elsif v_next_phase='first-shot' then if p_next_active_user_id<>v_other then raise exception 'shot must pass turn';end if;else raise exception 'invalid shot transition';end if;
elsif p_action_type='answer_correct' then if v_room.phase<>'bonus-question' or p_status<>'playing' or v_next_phase<>'bonus-shot' or p_next_active_user_id<>v_actor or v_delta<>3 or v_new_remaining<>v_old_remaining then raise exception 'invalid correct-answer transition';end if;
elsif p_action_type='answer_wrong' then if v_room.phase<>'bonus-question' or p_status<>'playing' or v_next_phase<>'first-shot' or p_next_active_user_id<>v_other or v_delta<>-1 or v_new_remaining<>v_old_remaining then raise exception 'invalid wrong-answer transition';end if;
elsif p_action_type='skip' then if v_room.phase<>'bonus-question' or p_status<>'playing' or v_next_phase<>'first-shot' or p_next_active_user_id<>v_other or v_delta<>0 or v_new_remaining<>v_old_remaining then raise exception 'invalid skip transition';end if;end if;
v_clean_state:=private.ashyk_clean_state(p_state,v_next_phase,v_next_player);v_turn_no:=v_room.turn_no+case when p_status='playing' and p_next_active_user_id<>v_actor then 1 else 0 end;v_winner_user:=null;
if p_status='finished' then if coalesce((p_state->>'winByKyt')::boolean,false) then v_winner_player:=v_actor_player;v_winner_user:=v_actor;elsif coalesce((v_new_scores->>0)::integer,0)=coalesce((v_new_scores->>1)::integer,0) then v_winner_player:=null;v_clean_state:=v_clean_state||jsonb_build_object('winner','draw');elsif coalesce((v_new_scores->>0)::integer,0)>coalesce((v_new_scores->>1)::integer,0) then v_winner_player:=1;v_winner_user:=v_room.host_user_id;else v_winner_player:=2;v_winner_user:=v_room.guest_user_id;end if;if v_winner_player is not null then v_clean_state:=v_clean_state||jsonb_build_object('winner',v_winner_player);end if;end if;
update public.ashyk_rooms set game_state=v_clean_state,active_user_id=p_next_active_user_id,status=p_status,revision=revision+1,turn_no=v_turn_no,phase=v_next_phase,phase_seq=phase_seq+1,phase_started_at=case when p_status='playing' then now() else phase_started_at end,phase_deadline_at=case when p_status='playing' then now()+make_interval(secs=>private.ashyk_phase_seconds(v_clean_state,v_next_phase)) else null end,last_action_id=p_action_id,last_action_type=p_action_type,last_action_actor_user_id=v_actor,winner_user_id=case when p_status='finished' then v_winner_user else winner_user_id end,finish_reason=case when p_status='finished' then case when coalesce((p_state->>'winByKyt')::boolean,false) then 'kyt' else 'score' end else finish_reason end,host_seen_at=case when v_actor=host_user_id then now() else host_seen_at end,guest_seen_at=case when v_actor=guest_user_id then now() else guest_seen_at end,ended_at=case when p_status='finished' then coalesce(ended_at,now()) else ended_at end,updated_at=now() where id=p_room_id returning * into v_room;
insert into public.ashyk_action_log(room_id,revision_after,phase_seq_after,actor_user_id,action_id,action_type) values(v_room.id,v_room.revision,v_room.phase_seq,v_actor,p_action_id,p_action_type) on conflict(room_id,action_id) do nothing;return v_room;
end $$;

commit;
