import React, { useEffect, useMemo, useState } from 'react';
import { Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { toggleFavorite } from '../../packages/alantil-core/favorites.js';
import { FAVORITES_HIDDEN_CONTEXT } from '../../packages/alantil-core/hidden-selection.js';
import { Button, FavoriteButton, Header, Screen } from '../ui/components.js';
import { CompactSegmentedControl, EmptyState, MonoLabel, SurfaceCard } from '../ui/parity.js';
import { msg } from '../i18n.js';
import { loadNativeHiddenWords, saveNativeHiddenWords } from '../platform/hidden-words.js';
import { theme } from '../ui/theme.js';

const C=theme.colors;const T=theme.type;
function BracketCheckbox({selected,onPress,label}){return <Pressable onPress={onPress} accessibilityRole="checkbox" accessibilityState={{checked:selected}} accessibilityLabel={label} style={styles.checkboxHit}><Text style={[styles.checkboxText,selected&&styles.checkboxOn]}>[{selected?'✓':' '}]</Text></Pressable>;}
export function FavoritesScreen({words,settings={},favorites,setFavorites,onBack,onLearn,onTest,onMatch}){
  const m=(key,params)=>msg(settings,key,params),[hiddenIds,setHiddenIds]=useState(()=>new Set()),[direction,setDirection]=useState('kb'),[ready,setReady]=useState(false),rows=useMemo(()=>words.filter((word)=>favorites.has(String(word.id))),[words,favorites]),activeRows=useMemo(()=>rows.filter((word)=>!hiddenIds.has(String(word.id))),[rows,hiddenIds]);
  useEffect(()=>{let alive=true;loadNativeHiddenWords(FAVORITES_HIDDEN_CONTEXT).then((set)=>{if(alive){setHiddenIds(set);setReady(true);}});return()=>{alive=false;};},[]);
  const persist=(next,changed)=>{setHiddenIds(next);saveNativeHiddenWords(FAVORITES_HIDDEN_CONTEXT,next,changed).catch(()=>{});};const toggleWord=(id)=>{const key=String(id),next=new Set(hiddenIds);if(next.has(key))next.delete(key);else next.add(key);persist(next,[key]);};const showAll=()=>{const next=new Set(hiddenIds),changed=rows.map((word)=>String(word.id));changed.forEach((id)=>next.delete(id));persist(next,changed);};const hideAll=()=>{const next=new Set(hiddenIds),changed=rows.map((word)=>String(word.id));changed.forEach((id)=>next.add(id));persist(next,changed);};const unfavorite=(id)=>{const key=String(id),nextHidden=new Set(hiddenIds);nextHidden.delete(key);persist(nextHidden,[key]);setFavorites(toggleFavorite(favorites,id).ids);};
  return <Screen><Header title={m('mobile.practice.favorites')} subtitle={m('mobile.common.words_count',{count:rows.length})} onBack={onBack}/>{rows.length?<><View style={styles.toolbar}><View style={styles.tools}><Pressable disabled={!ready} onPress={showAll}><Text style={styles.tool}>{m('mobile.common.show_all')}</Text></Pressable><Text style={styles.divider}>·</Text><Pressable disabled={!ready} onPress={hideAll}><Text style={styles.tool}>{m('mobile.common.hide_all')}</Text></Pressable></View><MonoLabel>{activeRows.length}/{rows.length}</MonoLabel></View><ScrollView contentContainerStyle={styles.list} showsVerticalScrollIndicator={false}><SurfaceCard>{rows.map((word)=>{const selected=!hiddenIds.has(String(word.id));return <View key={word.id} style={[styles.row,!selected&&styles.rowHidden]}><BracketCheckbox selected={selected} label={m('mobile.common.add_learning')} onPress={()=>toggleWord(word.id)}/><View style={styles.copy}><Text numberOfLines={1} style={styles.primary}>{word.word}</Text><Text numberOfLines={1} style={styles.secondary}>{word.trans}</Text></View><FavoriteButton active onPress={()=>unfavorite(word.id)}/></View>;})}</SurfaceCard></ScrollView><View style={styles.footer}><View style={styles.direction}><CompactSegmentedControl value={direction} items={[["kb",m('mobile.common.alan_ru')],["ru",m('mobile.common.ru_alan')]]} onChange={setDirection}/></View><View style={styles.gameActions}><Button style={styles.gameButton} disabled={!activeRows.length} onPress={()=>onMatch?.(activeRows)}>{m('mobile.practice.match')}</Button><Button style={styles.gameButton} disabled={!activeRows.length} onPress={()=>onTest?.(activeRows)}>{m('mobile.practice.test')}</Button></View><Button primary style={styles.start} disabled={!activeRows.length} onPress={()=>onLearn(activeRows,direction)}>{m('mobile.favorites.learn')}</Button></View></>:<View style={styles.empty}><EmptyState>{m('mobile.favorites.empty')}</EmptyState></View>}</Screen>;
}
const styles=StyleSheet.create({toolbar:{position:'absolute',zIndex:24,top:theme.control.header+4,left:18,right:18,height:34,flexDirection:'row',alignItems:'center',justifyContent:'space-between'},tools:{flexDirection:'row',alignItems:'center',gap:7},tool:{fontFamily:theme.font.terminal,fontSize:11,fontWeight:'700',color:C.text2},divider:{fontFamily:theme.font.terminal,fontSize:11,color:C.text3},list:{paddingTop:theme.control.header+44,paddingHorizontal:12,paddingBottom:154},row:{minHeight:52,flexDirection:'row',alignItems:'center',gap:7,paddingHorizontal:4,borderBottomWidth:1,borderBottomColor:C.lineSoft},rowHidden:{opacity:.48},checkboxHit:{width:38,minHeight:48,alignItems:'center',justifyContent:'center'},checkboxText:{fontFamily:theme.font.terminal,fontSize:14,lineHeight:18,fontWeight:'800',color:C.text3},checkboxOn:{color:C.accentStrong},copy:{flex:1,minWidth:0,minHeight:44,justifyContent:'center'},primary:{fontSize:15,fontWeight:'800',lineHeight:21,color:C.text1},secondary:{fontSize:T.caption,lineHeight:18,color:C.text2},footer:{position:'absolute',zIndex:30,left:12,right:12,bottom:10,gap:7},direction:{width:'100%'},gameActions:{flexDirection:'row',gap:7},gameButton:{flex:1},start:{width:'100%'},empty:{flex:1,marginTop:theme.control.header+24,marginHorizontal:12,justifyContent:'center'}});
