import React,{useEffect,useMemo,useRef,useState}from'react';
import{Image,Pressable,ScrollView,StyleSheet,Text,TextInput,View}from'react-native';
import{formatRating}from'../../packages/alantil-core/social.js';
import{socialMessage}from'../../packages/alantil-core/social-i18n.js';
import{createAshykOnlineAdapter}from'../../packages/ashyk-game/online.js';
import{Button,Screen,ScreenState,SegmentedControl}from'../ui/components.js';
import{theme}from'../ui/theme.js';
import{nativeSupabase}from'../platform/supabase.js';
import{acceptNativeFriendRequest,blockNativeUser,declineNativeFriendRequest,loadNativeFriendsSnapshot,loadNativeLeaderboard,removeNativeFriend,searchNativeUsers,sendNativeFriendRequest,unblockNativeUser}from'../platform/social.js';
const C=theme.colors,MALE=require('../../assets/images/profile/avatar_male.png'),FEMALE=require('../../assets/images/profile/avatar_female.png');
const EMPTY={friends:[],incoming:[],outgoing:[],blocked:[],ashyk_invites:[],ashyk_sent:[]};
function Avatar({gender}){return <View style={s.avatar}><Image source={gender==='female'?FEMALE:MALE} resizeMode="contain" style={s.avatarImage}/></View>}
function StoryProgress({value,label}){const percent=Math.max(0,Math.min(100,Number(value)||0));return <View style={s.storyRow}><Text style={s.storyLabel}>{label}</Text><View style={s.storyTrack}><View style={[s.storyFill,{width:`${percent}%`}]}/></View><Text style={s.storyPercent}>{percent}%</Text></View>}
function UserCard({user,language,actions=[],friend=false}){const t=(key,p)=>socialMessage(language,key,p),stories=user?.story_progress&&typeof user.story_progress==='object'?Object.entries(user.story_progress):[];return <View style={s.card}><View style={s.cardTop}><Avatar gender={user.avatar_gender}/><View style={s.cardCopy}><Text style={s.nickname}>{user.nickname||'—'}</Text><Text style={s.meta}>{t('score',{score:formatRating(user.rating_score)})}</Text>{friend?<Text style={s.meta}>{t('streak',{count:Number(user.streak_days)||0})}</Text>:null}</View></View>{friend&&stories.length?<View style={s.stories}><Text style={s.sectionCaption}>{t('storyProgress')}</Text>{stories.map(([key,row])=><StoryProgress key={key} label={key} value={row?.percent}/>)}</View>:null}{actions.length?<View style={s.actions}>{actions.map((action)=><Button key={action.key} role={action.primary?'generic.primary':'generic.default'} onPress={action.onPress} disabled={action.disabled} style={s.actionButton}>{action.label}</Button>)}</View>:null}</View>}
export function FriendsScreen({settings={},userId='',onSignIn,onOpenAshyk}){const language=settings?.interface_language_code||'ru',t=(key,p)=>socialMessage(language,key,p),[mode,setMode]=useState('friends'),[snapshot,setSnapshot]=useState(EMPTY),[leaderboard,setLeaderboard]=useState([]),[query,setQuery]=useState(''),[results,setResults]=useState([]),[busy,setBusy]=useState(''),[loading,setLoading]=useState(Boolean(userId)),[error,setError]=useState(''),request=useRef(0),online=useMemo(()=>createAshykOnlineAdapter(nativeSupabase),[]);
 const refresh=async()=>{if(!userId){setSnapshot(EMPTY);setLoading(false);return;}const id=++request.current;setLoading(true);setError('');try{const next=await loadNativeFriendsSnapshot();if(id===request.current)setSnapshot(next);}catch(e){if(id===request.current)setError(e?.message||t('error'));}finally{if(id===request.current)setLoading(false);}};
 const loadRank=async()=>{if(!userId)return;setBusy('rating');try{setLeaderboard(await loadNativeLeaderboard());}catch(e){setError(e?.message||t('error'));}finally{setBusy('');}};
 const runSearch=async(value=query)=>{if(!userId)return;setBusy('search');try{setResults(await searchNativeUsers(value));}catch(e){setError(e?.message||t('error'));}finally{setBusy('');}};
 useEffect(()=>{void refresh();if(!userId)return undefined;let timer=null;const schedule=()=>{clearTimeout(timer);timer=setTimeout(()=>void refresh(),120);};const channel=nativeSupabase.channel(`social-mobile:${userId}:${Date.now()}`).on('postgres_changes',{event:'*',schema:'public',table:'friendships'},schedule).on('postgres_changes',{event:'*',schema:'public',table:'ashyk_invites'},schedule).subscribe();return()=>{request.current+=1;clearTimeout(timer);try{channel.unsubscribe();}catch{}try{void nativeSupabase.removeChannel(channel);}catch{}};},[userId]);
 useEffect(()=>{if(mode==='rating'&&!leaderboard.length)void loadRank();},[mode,userId]);
 useEffect(()=>{if(mode!=='search')return undefined;const timer=setTimeout(()=>void runSearch(query),300);return()=>clearTimeout(timer);},[query,mode,userId]);
 const mutate=async(key,fn)=>{if(busy)return;setBusy(key);setError('');try{await fn();await refresh();if(mode==='rating')await loadRank();if(mode==='search')await runSearch(query);}catch(e){setError(e?.message||t('error'));}finally{setBusy('');}};
 const relationActions=(user)=>{if(user.relation==='accepted')return[];if(user.relation==='outgoing')return[{key:'sent',label:t('requested'),disabled:true}];if(user.relation==='incoming')return[{key:'accept',label:t('accept'),primary:true,onPress:()=>{const row=snapshot.incoming.find((item)=>item.user_id===user.user_id);if(row)void mutate(`accept:${row.friendship_id}`,()=>acceptNativeFriendRequest(row.friendship_id));}}];return[{key:'add',label:t('add'),primary:true,onPress:()=>void mutate(`add:${user.user_id}`,()=>sendNativeFriendRequest(user.user_id))}];};
 if(!userId)return <Screen bottomNav><View style={s.guest}><Text style={s.guestTitle}>{t('friends')}</Text><Text style={s.guestText}>{t('signIn')}</Text><Button role="generic.primary" onPress={onSignIn}>{t('accept')}</Button></View></Screen>;
 const acceptInvite=async(invite)=>{if(busy)return;setBusy(`invite:${invite.invite_id}`);try{const result=await online.acceptInvite(invite.invite_id);await refresh();if(result.room)onOpenAshyk?.(result.room,result.invite);}catch(e){setError(e?.message||t('error'));}finally{setBusy('');}};
 const declineInvite=async(invite)=>{await mutate(`decline-invite:${invite.invite_id}`,()=>online.declineInvite(invite.invite_id));};
 let content=null;
 if(mode==='friends')content=<>{snapshot.ashyk_invites.length?<Section title={t('invites')}>{snapshot.ashyk_invites.map((invite)=><UserCard key={invite.invite_id} user={invite} language={language} actions={[{key:'accept',label:t('accept'),primary:true,onPress:()=>void acceptInvite(invite)},{key:'decline',label:t('decline'),onPress:()=>void declineInvite(invite)}]}/>)}</Section>:null}{snapshot.incoming.length?<Section title={t('requests')}>{snapshot.incoming.map((user)=><UserCard key={user.friendship_id} user={user} language={language} actions={[{key:'accept',label:t('accept'),primary:true,onPress:()=>void mutate(`accept:${user.friendship_id}`,()=>acceptNativeFriendRequest(user.friendship_id))},{key:'decline',label:t('decline'),onPress:()=>void mutate(`decline:${user.friendship_id}`,()=>declineNativeFriendRequest(user.friendship_id))}]}/>)}</Section>:null}<Section title={t('friends')}>{snapshot.friends.length?snapshot.friends.map((user)=><UserCard key={user.user_id} user={user} friend language={language} actions={[{key:'remove',label:t('remove'),onPress:()=>void mutate(`remove:${user.user_id}`,()=>removeNativeFriend(user.user_id))},{key:'block',label:t('block'),onPress:()=>void mutate(`block:${user.user_id}`,()=>blockNativeUser(user.user_id))}]}/>):<Text style={s.empty}>{t('emptyFriends')}</Text>}</Section>{snapshot.blocked.length?<Section title={t('block')}>{snapshot.blocked.map((user)=><UserCard key={user.user_id} user={user} language={language} actions={[{key:'unblock',label:t('unblock'),onPress:()=>void mutate(`unblock:${user.user_id}`,()=>unblockNativeUser(user.user_id))}]}/>)}</Section>:null}</>;
 if(mode==='rating')content=<Section title={t('rating')}>{busy==='rating'&&!leaderboard.length?<ScreenState>{t('loading')}</ScreenState>:leaderboard.map((user)=><View key={user.user_id} style={s.rankRow}><Text style={s.rank}>#{user.rank}</Text><View style={{flex:1}}><UserCard user={user} language={language} actions={user.user_id===userId?[]:relationActions(user)}/></View></View>)}</Section>;
 if(mode==='search')content=<><View style={s.searchBox}><TextInput value={query} onChangeText={setQuery} placeholder={t('searchPlaceholder')} placeholderTextColor={C.text3} autoCapitalize="none" style={s.input}/></View><Section title={t('search')}>{busy==='search'&&!results.length?<ScreenState>{t('loading')}</ScreenState>:results.length?results.map((user)=><UserCard key={user.user_id} user={user} language={language} actions={relationActions(user)}/>):<Text style={s.empty}>{t('emptySearch')}</Text>}</Section></>;
 return <Screen bottomNav><View style={s.header}><Text style={s.title}>{t('friends')}</Text><SegmentedControl value={mode} onChange={setMode} items={[["friends",t('friends')],["rating",t('rating')],["search",t('search')]]}/></View><ScrollView contentContainerStyle={s.scroll} keyboardShouldPersistTaps="handled">{error?<Text style={s.error}>{error}</Text>:null}{loading&&!snapshot.friends.length&&!snapshot.incoming.length&&!snapshot.ashyk_invites.length?<ScreenState>{t('loading')}</ScreenState>:content}</ScrollView></Screen>;
}
function Section({title,children}){return <View style={s.section}><Text style={s.sectionTitle}>{title}</Text>{children}</View>}
const s=StyleSheet.create({header:{paddingTop:18,paddingHorizontal:16,paddingBottom:8,gap:12},title:{fontSize:26,fontWeight:'900',color:C.text1},scroll:{paddingHorizontal:16,paddingBottom:theme.control.nav+32,gap:18},section:{gap:10},sectionTitle:{fontSize:15,fontWeight:'900',color:C.text1,textTransform:'uppercase',letterSpacing:.8},sectionCaption:{fontSize:11,fontWeight:'800',color:C.text2,textTransform:'uppercase',letterSpacing:.7},card:{borderWidth:1,borderColor:C.lineStrong,borderRadius:18,backgroundColor:'rgba(246,242,233,.58)',padding:12,gap:10},cardTop:{flexDirection:'row',gap:12,alignItems:'center'},avatar:{width:52,height:52,borderRadius:26,overflow:'hidden',backgroundColor:C.accentSoft,alignItems:'center',justifyContent:'flex-end'},avatarImage:{width:48,height:48},cardCopy:{flex:1,gap:2},nickname:{fontSize:16,fontWeight:'900',color:C.text1},meta:{fontSize:12,color:C.text2},stories:{gap:6},storyRow:{flexDirection:'row',alignItems:'center',gap:7},storyLabel:{width:82,fontSize:10,color:C.text2},storyTrack:{flex:1,height:5,borderRadius:999,overflow:'hidden',backgroundColor:C.line},storyFill:{height:'100%',backgroundColor:C.accent},storyPercent:{width:34,textAlign:'right',fontSize:10,color:C.text2},actions:{flexDirection:'row',flexWrap:'wrap',gap:8},actionButton:{flexGrow:1,minWidth:120},empty:{fontSize:13,lineHeight:19,color:C.text2,paddingVertical:8},error:{fontSize:13,color:C.danger,paddingVertical:8},searchBox:{marginBottom:4},input:{minHeight:46,borderWidth:1,borderColor:C.lineStrong,borderRadius:14,paddingHorizontal:14,fontSize:15,color:C.text1,backgroundColor:'rgba(246,242,233,.58)'},rankRow:{flexDirection:'row',alignItems:'flex-start',gap:8},rank:{width:38,paddingTop:16,fontSize:13,fontWeight:'900',color:C.text2,textAlign:'center'},guest:{flex:1,alignItems:'center',justifyContent:'center',padding:28,gap:16},guestTitle:{fontSize:28,fontWeight:'900',color:C.text1},guestText:{maxWidth:360,textAlign:'center',fontSize:15,lineHeight:22,color:C.text2}});
