import React, { useEffect, useMemo, useRef, useState } from 'react';
import { Animated, BackHandler, PanResponder, Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { LEARNING_GUIDE_STEPS, LEARNING_REPEAT_GUIDE_STEP } from '../../packages/alantil-core/guide-contract.js';
import { buildLearnCardModel } from '../../packages/alantil-core/learn-card.js';
import { buildLearnResultSummary, decideLearnCard, ensureLearnWordStats, exposeCurrentLearnCard, initializeLearnState, learnCompletionSummary, learnSessionWords, undoLearnDecision } from '../../packages/alantil-core/learning.js';
import { favoriteHas, toggleFavorite } from '../../packages/alantil-core/favorites.js';
import { Button, FavoriteButton, Header, ProgressBar, Screen, SectionLabel } from '../ui/components.js';
import { GuideHelpButton, GuideOverlay } from '../ui/guide.js';
import { EmptyState, MetricStrip, MonoLabel, ScreenSection, SurfaceCard } from '../ui/parity.js';
import { theme } from '../ui/theme.js';
import { recordNativeLearnSession } from '../platform/progress.js';
import { loadNativeGuideState, saveNativeGuideState } from '../platform/guide-state.js';
import { clearNativeSessionSnapshot, loadNativeSessionSnapshot, saveNativeSessionSnapshot } from '../platform/session-store.js';

const C=theme.colors;const T=theme.type;
function createState(words,mode,station){const state={currentDict:station?.dictionaryId||'',currentSection:station?.sectionId||'',currentSet:station?.setId||'',mainQueue:[],repeatQueue:[],round:'main',totalPlanned:0,currentStudyId:'',swipeHistory:[],analyticsActions:[],sessionFailMap:{},isAnimating:false,studySession:{inProgress:false,completed:false,wordsPool:[],progressData:{},wordStats:{},metadata:{}}};initializeLearnState(state,words,mode,{stationContext:station||null});return state;}
function contextKey(words,mode,station){return `${station?.key||'practice'}|${mode}|${words.map((word)=>String(word.id)).join(',')}`;}
function serializeState(state,key,startedAt){return{contextKey:key,startedAt,state:{...state,isAnimating:false}};}

export function LearnScreen({words,mode='kb',station,settings={},favorites,setFavorites,onBack}){
  const key=useMemo(()=>contextKey(words,mode,station),[words,mode,station]);
  const [state,setState]=useState(null),[flipped,setFlipped]=useState(false),[cardWidth,setCardWidth]=useState(320),[guideIndex,setGuideIndex]=useState(-1),[repeatGuide,setRepeatGuide]=useState(false);const [,redraw]=useState(0);
  const startedAt=useRef(new Date().toISOString()),recorded=useRef(false),lastExposed=useRef(''),gestureLock=useRef(false),dragging=useRef(false),translateX=useRef(new Animated.Value(0)).current;
  useEffect(()=>{let alive=true;(async()=>{const [saved,guide]=await Promise.all([loadNativeSessionSnapshot('learn'),loadNativeGuideState()]);if(!alive)return;if(saved?.contextKey===key&&saved?.state?.studySession?.inProgress){startedAt.current=saved.startedAt||startedAt.current;saved.state.isAnimating=false;setState(saved.state);}else{if(saved)await clearNativeSessionSnapshot('learn');setState(createState(words,mode,station));}if(!guide.learning_completed)setGuideIndex(0);})();return()=>{alive=false;};},[key,words,mode,station]);
  const persist=()=>state?saveNativeSessionSnapshot('learn',serializeState(state,key,startedAt.current)).catch(()=>{}):Promise.resolve();const back=()=>{persist();onBack();};
  useEffect(()=>{const sub=BackHandler.addEventListener('hardwareBackPress',()=>{back();return true;});return()=>sub.remove();},[state,key,onBack]);
  const exposure=state?exposeCurrentLearnCard(state,{countShow:false}):{item:null,finished:false},item=exposure.item,finish=Boolean(state&&(exposure.finished||(!item&&state.totalPlanned>0))),summary=finish&&state?buildLearnResultSummary(state,words):null,cardModel=useMemo(()=>item?buildLearnCardModel(item,mode,settings):null,[item,mode,settings]);
  useEffect(()=>{if(!state)return;const id=String(item?.id||'');if(!id||lastExposed.current===id)return;const stats=ensureLearnWordStats(state,item);if(stats)stats.show_count+=1;lastExposed.current=id;persist();loadNativeGuideState().then((guide)=>{const failCount=Number(state.sessionFailMap?.[id]||0);if(guide.learning_completed&&!guide.repeat_hint_shown&&Number(stats?.show_count||0)>=2&&failCount>=1)setRepeatGuide(true);});},[item?.id,state,key]);
  useEffect(()=>{if(!state||!finish||recorded.current)return;recorded.current=true;state.studySession.completed=true;state.studySession.inProgress=false;recordNativeLearnSession({sessionId:`learn-${startedAt.current}-${station?.key||'practice'}`,words:learnSessionWords(state),startedAt:startedAt.current}).catch(()=>{});clearNativeSessionSnapshot('learn').catch(()=>{});},[finish,state,station?.key]);
  const finishGuide=async()=>{await saveNativeGuideState({learning_completed:true});setGuideIndex(-1);};const dismissRepeat=async()=>{await saveNativeGuideState({repeat_hint_shown:true});setRepeatGuide(false);};
  const guideNext=async()=>{if(guideIndex===0){setFlipped(true);setGuideIndex(1);return;}if(guideIndex+1>=LEARNING_GUIDE_STEPS.length){await finishGuide();return;}setGuideIndex(guideIndex+1);};
  const settleDecision=(known)=>{if(!state||gestureLock.current)return;gestureLock.current=true;state.isAnimating=true;const target=known?Math.max(420,cardWidth*1.3):-Math.max(420,cardWidth*1.3);Animated.timing(translateX,{toValue:target,duration:180,useNativeDriver:true}).start(()=>{decideLearnCard(state,known);state.isAnimating=false;setFlipped(false);lastExposed.current='';translateX.setValue(0);persist();redraw((value)=>value+1);gestureLock.current=false;if(guideIndex===2)setGuideIndex(3);});};
  const resetDrag=()=>Animated.spring(translateX,{toValue:0,useNativeDriver:true,speed:24,bounciness:4}).start();
  const panResponder=useMemo(()=>PanResponder.create({onMoveShouldSetPanResponder:(_,gesture)=>!gestureLock.current&&Math.abs(gesture.dx)>10&&Math.abs(gesture.dx)>Math.abs(gesture.dy),onPanResponderGrant:()=>{dragging.current=true;},onPanResponderMove:(_,gesture)=>{if(!gestureLock.current)translateX.setValue(gesture.dx);},onPanResponderRelease:(_,gesture)=>{dragging.current=false;const threshold=Math.max(72,cardWidth*.3);if(gesture.dx>threshold)settleDecision(true);else if(gesture.dx<-threshold)settleDecision(false);else resetDrag();},onPanResponderTerminate:()=>{dragging.current=false;resetDrag();}}),[state,cardWidth,key,guideIndex]);
  if(!state)return <Screen><Header title="Учить слова" onBack={onBack}/><View style={styles.center}><EmptyState>Восстанавливаем обучение…</EmptyState></View></Screen>;
  if(finish){const completed=learnCompletionSummary(state);return <Screen><Header title="Результат" onBack={onBack}/><ScrollView contentContainerStyle={styles.results} showsVerticalScrollIndicator={false}><SectionLabel>ОБУЧЕНИЕ ЗАВЕРШЕНО</SectionLabel><SurfaceCard><MetricStrip items={[[String(completed.items_total),'изучено'],[String(completed.known_count),'знаю'],[String(summary?.leftSwipesTotal||0),'не знаю']]}/></SurfaceCard><ScreenSection title="Проблемные слова">{summary?.problemWords?.length?<SurfaceCard>{summary.problemWords.slice(0,7).map((word)=><View key={word.id} style={styles.problemRow}><View style={styles.problemCopy}><Text style={styles.problemWord}>{word.word}</Text><Text style={styles.problemTrans}>{word.trans}</Text></View><MonoLabel style={styles.problemFails}>{word.fails}</MonoLabel></View>)}</SurfaceCard>:<EmptyState>Ошибок нет.</EmptyState>}</ScreenSection><View style={styles.resultFooter}><Button primary style={styles.resultButton} onPress={onBack}>К этапу</Button></View></ScrollView></Screen>;}
  if(!item)return <Screen><Header title="Учить слова" onBack={onBack}/><View style={styles.center}><EmptyState>Нет слов для обучения.</EmptyState></View></Screen>;
  const pending=new Set([...state.mainQueue,...state.repeatQueue].map((word)=>String(word.id))).size,totalDone=Math.max(0,state.totalPlanned-pending),progress=state.totalPlanned?(totalDone/state.totalPlanned)*100:0;const undo=()=>{if(gestureLock.current)return;const action=undoLearnDecision(state);if(action){lastExposed.current='';setFlipped(false);translateX.setValue(0);persist();redraw((value)=>value+1);}};const rotate=translateX.interpolate({inputRange:[-cardWidth,0,cardWidth],outputRange:['-12deg','0deg','12deg'],extrapolate:'clamp'}),opacity=translateX.interpolate({inputRange:[-cardWidth,0,cardWidth],outputRange:[.55,1,.55],extrapolate:'clamp'}),currentGuide=guideIndex>=0?LEARNING_GUIDE_STEPS[guideIndex]:null;
  return <Screen><Header title="Учить слова" onBack={back} sessionStatus={{counter:`${Math.min(totalDone+1,state.totalPlanned)}/${state.totalPlanned}`,mode:mode==='ru'?'РУС → АЛАН':'АЛАН → РУС'}}/><View style={styles.session}><ProgressBar value={progress}/><Animated.View {...panResponder.panHandlers} onLayout={(event)=>setCardWidth(event.nativeEvent.layout.width||320)} style={[styles.cardWrap,{transform:[{translateX},{rotate}],opacity}]}><Pressable accessibilityRole="button" accessibilityLabel="Перевернуть карточку" onPress={()=>{if(!dragging.current&&!gestureLock.current){setFlipped((value)=>!value);if(guideIndex===0)setGuideIndex(1);}}} style={styles.cardPress}><SurfaceCard inset style={[styles.card,flipped&&styles.cardBack]}>{!flipped?<><MonoLabel>НАЖМИТЕ, ЧТОБЫ ПЕРЕВЕРНУТЬ</MonoLabel><Text style={styles.word}>{cardModel.front.primary}</Text></>:<ScrollView style={styles.backScroll} contentContainerStyle={styles.backContent} showsVerticalScrollIndicator={false}><MonoLabel>ПЕРЕВОД</MonoLabel><Text style={styles.translation}>{cardModel.back.primary}</Text>{cardModel.back.synonyms.length?<><MonoLabel style={styles.backLabel}>СИНОНИМЫ</MonoLabel><Text style={styles.copyText}>{cardModel.back.synonyms.join(', ')}</Text></>:null}{cardModel.back.examples.map((group)=><View key={group.index} style={styles.exampleGroup}><MonoLabel style={styles.backLabel}>ПРИМЕР</MonoLabel>{group.lines.map((line,index)=><Text key={`${group.index}-${index}`} style={styles.copyText}>{line}{group.translationLines[index]?` — ${group.translationLines[index]}`:''}</Text>)}</View>)}</ScrollView>}<View style={styles.cardActions}><Pressable disabled={!state.swipeHistory.length||gestureLock.current} onPress={(event)=>{event.stopPropagation?.();undo();}} style={({pressed})=>[styles.cardAction,(!state.swipeHistory.length||gestureLock.current)&&styles.cardActionDisabled,pressed&&styles.pressed]}><Text style={styles.cardActionIcon}>↶</Text><MonoLabel>назад</MonoLabel></Pressable><FavoriteButton active={favoriteHas(favorites,item.id)} onPress={()=>setFavorites(toggleFavorite(favorites,item.id).ids)}/></View></SurfaceCard></Pressable></Animated.View><View style={styles.decisions}><Decision kind="unknown" label="Не знаю" icon="×" disabled={gestureLock.current} onPress={()=>settleDecision(false)}/><Decision kind="known" label="Знаю" icon="✓" disabled={gestureLock.current} onPress={()=>settleDecision(true)}/></View></View><GuideHelpButton onPress={()=>{setRepeatGuide(false);setGuideIndex(0);}}/><GuideOverlay visible={Boolean(currentGuide)} settings={settings} step={currentGuide} onNext={guideNext} onSkip={finishGuide} nextLabel={currentGuide?.id==='favorite'?'OK':''}/><GuideOverlay visible={repeatGuide} settings={settings} step={LEARNING_REPEAT_GUIDE_STEP} onNext={dismissRepeat} onSkip={dismissRepeat} nextLabel="OK"/></Screen>;
}
function Decision({kind,label,icon,onPress,disabled}){return <Pressable accessibilityRole="button" disabled={disabled} onPress={onPress} style={({pressed})=>[styles.decision,disabled&&styles.cardActionDisabled,pressed&&!disabled&&styles.pressed]}><View style={[styles.decisionIcon,kind==='unknown'?styles.unknownIcon:styles.knownIcon]}><Text style={[styles.decisionGlyph,kind==='unknown'?styles.unknownGlyph:styles.knownGlyph]}>{icon}</Text></View><MonoLabel>{label}</MonoLabel></Pressable>;}
const styles=StyleSheet.create({center:{flex:1,justifyContent:'center',paddingHorizontal:20},session:{flex:1,paddingTop:theme.control.header+8,paddingHorizontal:12,paddingBottom:10,gap:12},cardWrap:{flex:1,minHeight:0,alignItems:'center',justifyContent:'center'},cardPress:{width:'100%',height:'100%',alignItems:'center',justifyContent:'center'},card:{width:'100%',maxWidth:560,height:'100%',maxHeight:620,alignItems:'center',justifyContent:'center',paddingHorizontal:24,paddingVertical:26,gap:18},cardBack:{alignItems:'stretch',justifyContent:'flex-start',paddingTop:30,paddingHorizontal:20,paddingBottom:58},word:{maxWidth:'100%',fontSize:42,fontWeight:'900',lineHeight:46,color:C.text1,textAlign:'center'},backScroll:{width:'100%',flex:1},backContent:{width:'100%',paddingTop:4,paddingBottom:50,gap:7},backLabel:{marginTop:12},translation:{fontSize:19,fontWeight:'800',lineHeight:27,color:C.text1},copyText:{fontSize:T.body,lineHeight:21,color:C.text2},exampleGroup:{gap:4},cardActions:{position:'absolute',zIndex:5,left:12,right:12,bottom:10,flexDirection:'row',alignItems:'center',justifyContent:'space-between'},cardAction:{minWidth:44,minHeight:42,padding:7,alignItems:'center',justifyContent:'center',gap:3},cardActionDisabled:{opacity:.28},cardActionIcon:{fontSize:20,lineHeight:20,color:C.text2},decisions:{width:'100%',maxWidth:560,alignSelf:'center',flexDirection:'row',alignItems:'flex-start',justifyContent:'center',gap:58,paddingTop:2},decision:{width:68,minHeight:66,alignItems:'center',gap:5},decisionIcon:{width:44,height:44,borderRadius:22,borderWidth:1,alignItems:'center',justifyContent:'center'},unknownIcon:{borderColor:C.danger,backgroundColor:'rgba(152,86,76,.045)'},knownIcon:{borderColor:C.success,backgroundColor:'rgba(93,118,84,.045)'},unknownGlyph:{color:C.dangerStrong},knownGlyph:{color:C.successStrong},decisionGlyph:{fontSize:22,fontWeight:'800'},results:{paddingTop:theme.control.header+18,paddingHorizontal:12,paddingBottom:24,gap:14},problemRow:{minHeight:52,paddingHorizontal:10,flexDirection:'row',alignItems:'center',borderBottomWidth:1,borderBottomColor:C.lineSoft},problemCopy:{flex:1,minWidth:0},problemWord:{fontSize:15,fontWeight:'700',color:C.text1},problemTrans:{marginTop:2,fontSize:T.caption,color:C.text2},problemFails:{color:C.dangerStrong},resultFooter:{alignItems:'flex-end',paddingTop:2},resultButton:{width:176,maxWidth:'52%'},pressed:{opacity:.7,transform:[{translateY:1}]}});
