import React, { useEffect, useRef, useState } from 'react';
import { ScrollView, StyleSheet, Text, View } from 'react-native';
import { DEFAULT_USER_SETTINGS } from '../../packages/alantil-core/settings.js';
import { filterNickname, providerLabel, validateNicknameRule } from '../../packages/alantil-core/profile.js';
import { Button, FactRows, FormField, Header, InlineMessage, Panel, Screen, ScreenState } from '../ui/components.js';
import { AuthEntryActions } from '../ui/auth-entry-actions.js';
import { theme } from '../ui/theme.js';
import { mobileMsg } from '../i18n.js';
import { bootstrapNativeAuth, getNativeAuthError, getNativeAuthProvider, signOutNative, subscribeNativeAuth } from '../platform/auth.js';
import { checkNativeNickname, createNativeProfile, isNativeProfileApiUnavailable, loadNativeProfile } from '../platform/profile-api.js';
import { ProfileMainArea } from './profile-main.js';

const C=theme.colors;
function nicknameMessage(language,validation){return validation.reason==='required'?mobileMsg(language,'service.vvedite_nikneym'):mobileMsg(language,'service.nickname_requirements');}
function providerFromSession(session){return providerLabel(getNativeAuthProvider(session));}

export function AccountScreen({onBack,onGuest,settings=DEFAULT_USER_SETTINGS}){
  const language=settings?.interface_language_code||'ru',msg=(key,params)=>mobileMsg(language,key,params);
  const [authReady,setAuthReady]=useState(false),[session,setSession]=useState(null),[profile,setProfile]=useState(undefined),[profileLoading,setProfileLoading]=useState(false),[profileError,setProfileError]=useState(null),[authError,setAuthError]=useState(''),[busy,setBusy]=useState(''),[nickname,setNickname]=useState(''),[nicknameStatus,setNicknameStatus]=useState({state:'',message:'',available:false});
  const profileRequest=useRef(0),nicknameRequest=useRef(0);
  const loadProfile=async(nextSession)=>{const requestId=++profileRequest.current;if(!nextSession?.user?.id){setProfile(null);setProfileError(null);setProfileLoading(false);return;}setProfileLoading(true);setProfileError(null);try{const next=await loadNativeProfile(nextSession.user.id);if(requestId===profileRequest.current)setProfile(next);}catch(error){if(requestId===profileRequest.current){setProfile(undefined);setProfileError(error);}}finally{if(requestId===profileRequest.current)setProfileLoading(false);}};
  useEffect(()=>{let mounted=true;const applyAuth=(nextSession,error)=>{if(!mounted)return;setSession(nextSession||null);setAuthError(error?.message||'');setAuthReady(true);setNickname('');setNicknameStatus({state:'',message:'',available:false});void loadProfile(nextSession||null);};bootstrapNativeAuth().then((next)=>applyAuth(next,getNativeAuthError())).catch((error)=>{if(mounted){setAuthReady(true);setSession(null);setProfile(null);setAuthError(error?.message||msg('account.ne_udalos_vypolnit_operatsiyu_povtorite_pozzhe'));}});const unsub=subscribeNativeAuth(applyAuth);return()=>{mounted=false;profileRequest.current+=1;nicknameRequest.current+=1;unsub();};},[]);
  useEffect(()=>{nicknameRequest.current+=1;const requestId=nicknameRequest.current;if(!session?.user?.id||profile!==null||profileError)return undefined;const validation=validateNicknameRule(nickname);if(!validation.valid){setNicknameStatus({state:nickname?'invalid':'',message:nicknameMessage(language,validation),available:false});return undefined;}setNicknameStatus({state:'checking',message:msg('account.proveryaem_nikneym'),available:false});const timer=setTimeout(async()=>{try{const result=await checkNativeNickname(validation.nickname);if(requestId!==nicknameRequest.current)return;setNicknameStatus({state:result.available?'available':'invalid',message:result.available?msg('service.nikneym_svoboden'):msg('service.takoy_nikneym_uzhe_ispolzuetsya'),available:Boolean(result.available)});}catch(error){if(requestId!==nicknameRequest.current)return;if(isNativeProfileApiUnavailable(error)){setProfileError(error);setProfile(undefined);}else setNicknameStatus({state:'invalid',message:error?.message||msg('account.ne_udalos_vypolnit_operatsiyu_povtorite_pozzhe'),available:false});}},350);return()=>clearTimeout(timer);},[nickname,session?.user?.id,profile,profileError,language]);
  const signOut=async()=>{setBusy('logout');setAuthError('');try{await signOutNative();setProfile(null);setProfileError(null);}catch(error){setAuthError(error?.message||msg('account.ne_udalos_vypolnit_operatsiyu_povtorite_pozzhe'));}finally{setBusy('');}};
  const retryProfile=async()=>{if(!session?.user?.id)return;setBusy('retry');setProfileError(null);await loadProfile(session);setBusy('');};
  const createProfile=async()=>{if(!session?.user?.id||busy)return;const validation=validateNicknameRule(nickname);if(!validation.valid){setNicknameStatus({state:'invalid',message:nicknameMessage(language,validation),available:false});return;}setBusy('save');setProfileError(null);try{const availability=await checkNativeNickname(validation.nickname);if(!availability.available){setNicknameStatus({state:'invalid',message:msg('service.takoy_nikneym_uzhe_ispolzuetsya'),available:false});return;}const next=await createNativeProfile(session.user.id,validation.nickname);setProfile(next);setNicknameStatus({state:'',message:'',available:false});}catch(error){if(isNativeProfileApiUnavailable(error)){setProfileError(error);setProfile(undefined);}else setNicknameStatus({state:'invalid',message:error?.message||msg('account.ne_udalos_vypolnit_operatsiyu_povtorite_pozzhe'),available:false});}finally{setBusy('');}};
  const accountTitle=msg('account.akkaunt'),backLabel=msg('common.nazad');let body=null;
  if(!authReady)body=<ScreenState>{msg('account.proveryaem_akkaunt')}</ScreenState>;
  else if(!session?.user)body=<Panel title={accountTitle} style={styles.accountPanel} bodyStyle={styles.accountPanelBody}><View style={styles.accountStack}>{authError?<InlineMessage type="error">{authError}</InlineMessage>:null}<AuthEntryActions settings={settings} allowGuest onGuest={onGuest} guestPresentation="text" disabled={Boolean(busy)}/></View></Panel>;
  else if(profileLoading||profile===undefined&&!profileError)body=<ScreenState>{msg('account.proveryaem_akkaunt')}</ScreenState>;
  else if(profileError)body=<Panel title={accountTitle} style={styles.accountPanel} bodyStyle={styles.accountPanelBody}><View style={styles.accountStack}><InlineMessage type="error">{profileError?.message||msg('account.ne_udalos_vypolnit_operatsiyu_povtorite_pozzhe')}</InlineMessage><FormField label="Email" value={session.user.email||''} editable={false}/><Button role="generic.primary" onPress={retryProfile} disabled={Boolean(busy)}>{busy==='retry'?msg('account.proveryaem'):msg('account.povtorit')}</Button><Button role="profile.signOut" onPress={signOut} disabled={Boolean(busy)}>{msg('account.vyyti')}</Button></View></Panel>;
  else if(!profile){const validation=validateNicknameRule(nickname);body=<Panel title={msg('account.sozdayte_nikneym')} style={styles.accountPanel} bodyStyle={styles.accountPanelBody}><View style={styles.accountStack}>{authError?<InlineMessage type="error">{authError}</InlineMessage>:null}<FormField label="Email" value={session.user.email||''} editable={false}/><FormField label={msg('account.nikneym')} value={nickname} onChangeText={(value)=>setNickname(filterNickname(value))} placeholder="alan_01" autoCapitalize="none" success={nicknameStatus.state==='available'} error={nicknameStatus.state==='invalid'}/><Text style={[styles.accountNicknameMessage,nicknameStatus.state==='available'&&styles.accountNicknameSuccess,nicknameStatus.state==='invalid'&&styles.accountNicknameError]}>{nicknameStatus.message||nicknameMessage(language,validation)}</Text><Button role="profile.create" onPress={createProfile} disabled={Boolean(busy)||!nicknameStatus.available}>{busy==='save'?msg('account.proveryaem'):msg('account.sohranit')}</Button><Button role="profile.signOut" onPress={signOut} disabled={Boolean(busy)}>{msg('account.vyyti')}</Button></View></Panel>;
  }else body=<Panel title={accountTitle} style={styles.accountPanel} bodyStyle={styles.accountPanelBody}><View style={styles.accountStack}>{authError?<InlineMessage type="error">{authError}</InlineMessage>:null}<FactRows rows={[[msg('account.nikneym'),profile.nickname||''],['Email',session.user.email||''],[msg('account.sposob_vhoda'),providerFromSession(session)]]}/><Button role="profile.signOut" onPress={signOut} disabled={Boolean(busy)}>{msg('account.vyyti')}</Button></View></Panel>;
  return <Screen><Header title={accountTitle} onBack={onBack} backLabel={backLabel}/><ScrollView contentContainerStyle={styles.accountScroll} keyboardShouldPersistTaps="handled"><View style={styles.accountView}>{body}</View></ScrollView></Screen>;
}

export function ProfileArea({words,settings=DEFAULT_USER_SETTINGS,onSettingsChange,onAccount,onOpenStory}){return <ProfileMainArea words={words} settings={settings} onSettingsChange={onSettingsChange} onAccount={onAccount} onOpenStory={onOpenStory}/>;}

const styles=StyleSheet.create({accountScroll:{paddingTop:theme.control.header+theme.chrome.contentRestGap,paddingHorizontal:0,paddingBottom:theme.safeArea.bottomContentGap+16},accountView:{width:'100%',maxWidth:theme.account.maxWidth,alignSelf:'center'},accountPanel:{width:'100%',margin:0,borderWidth:0,borderRadius:0,backgroundColor:'transparent',shadowOpacity:0,elevation:0},accountPanelBody:{paddingHorizontal:16,paddingTop:8,paddingBottom:18},accountStack:{gap:14},accountNicknameMessage:{minHeight:20,fontSize:13,lineHeight:18,color:C.text2},accountNicknameSuccess:{color:C.success},accountNicknameError:{color:C.danger},});
