import React, { useEffect, useMemo, useRef, useState } from 'react';
import { BackHandler, Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { applyStationTestAnswer, buildStationTestSessionState, stationTestActiveSnapshot, stationTestPayload, stationTestResult } from '../../packages/alantil-core/station-test.js';
import { toggleFavorite } from '../../packages/alantil-core/favorites.js';
import { Button, FavoriteButton, Header, Screen } from '../ui/components.js';
import { EmptyState } from '../ui/parity.js';
import { useMobileMsg, useRuntimeSettings, useSemanticTypography } from '../ui/runtime-settings.js';
import { theme } from '../ui/theme.js';
import { recordNativeTestSession } from '../platform/progress.js';
import { clearNativeSessionSnapshot, loadNativeSessionSnapshot, saveNativeSessionSnapshot } from '../platform/session-store.js';

const C=theme.colors;

export function StationTestScreen({station,allWords,mode='kb',favorites=new Set(),setFavorites=()=>{},onBack}){
  const m=useMobileMsg(),{settings}=useRuntimeSettings(),type=useSemanticTypography();
  const [session,setSession]=useState(null),[selectedId,setSelectedId]=useState('');const [,redraw]=useState(0),recorded=useRef(false);
  const createSession=(interrupted=null)=>buildStationTestSessionState({station,optionWords:allWords,mode,interrupted,id:`station-${Date.now()}-${Math.random().toString(36).slice(2,8)}`,startedAt:new Date().toISOString()});
  useEffect(()=>{let alive=true;(async()=>{const interrupted=await loadNativeSessionSnapshot('station-test'),next=createSession(interrupted);if(alive)setSession(next);})();return()=>{alive=false;};},[station,allWords,mode]);
  const question=session?.questions?.[session.index],done=Boolean(session&&!question),result=useMemo(()=>done?stationTestResult(session,stationTestPayload(session)):null,[done,session]);
  useEffect(()=>{setSelectedId('');},[session?.index]);
  useEffect(()=>{if(!done||!result||recorded.current)return;recorded.current=true;session.completed=true;const payload=stationTestPayload(session);recordNativeTestSession({sessionId:session.id,answers:payload.words.map((row)=>({word_id:row.word_id,result:row.result})),accuracy:payload.accuracy,requiredAccuracy:payload.required_accuracy,updateMastery:true,startedAt:session.startedAt,type:'station_test',stationKey:station?.key||'',phase:payload.phase||session.phase||''}).catch(()=>{});clearNativeSessionSnapshot('station-test').catch(()=>{});},[done,result,session,station?.key]);
  const back=()=>{if(session&&!session.completed)saveNativeSessionSnapshot('station-test',stationTestActiveSnapshot(session)).catch(()=>{});onBack();};
  const retry=async()=>{await clearNativeSessionSnapshot('station-test').catch(()=>{});recorded.current=false;setSelectedId('');const next=createSession(null);setSession(next);redraw((value)=>value+1);saveNativeSessionSnapshot('station-test',stationTestActiveSnapshot(next)).catch(()=>{});};
  useEffect(()=>{const sub=BackHandler.addEventListener('hardwareBackPress',()=>{back();return true;});return()=>sub.remove();},[session,onBack]);
  if(!session)return <Screen><Header title={m('mobile.test.title')} subtitle={station?.name||''} onBack={onBack}/><View style={styles.center}><EmptyState>{m('mobile.stage.restoring')}</EmptyState></View></Screen>;
  if(done&&result){
    const levelSymbol=result.masteryLevel?'⌃'.repeat(result.masteryLevel):'—';
    return <Screen><Header title={m('mobile.stage.results')} subtitle={station?.name||''} onBack={onBack}/><View style={styles.resultView}><View style={styles.resultSummary}><Text style={styles.resultMark}>{levelSymbol}</Text><Text style={[styles.resultScore,type.result,result.passed?styles.scorePassed:styles.scoreFailed]}>{result.payload.accuracy}%</Text><Text style={[styles.resultStatus,type.caption]}>{result.passed?m('mobile.stage.passed'):m('mobile.stage.repeat')} · {result.payload.correct_total}/{result.payload.questions_total}</Text></View><ScrollView contentContainerStyle={styles.resultList} showsVerticalScrollIndicator={false}>{session.answers.map((answer,index)=>{const source=session.questions[index],correct=answer.result==='correct',selected=source?.options?.find((option)=>String(option.id)===String(answer.wrongWordId||source?.item?.id)),wordId=String(answer.wordId||source?.item?.id||'');return <View key={`${wordId}-${index}`} style={styles.resultRow}><View style={[styles.resultDot,correct?styles.resultDotCorrect:styles.resultDotWrong]}><Text style={styles.resultDotGlyph}>{correct?'✓':'×'}</Text></View><View style={styles.resultCopy}><Text numberOfLines={1} style={[styles.resultPrimary,type.emphasis]}>{session.mode==='ru'?source?.item?.trans:source?.item?.word}</Text>{!correct?<Text numberOfLines={1} style={[styles.resultWrong,type.micro]}>{m('mobile.common.your_answer')}: {selected?.text||'—'}</Text>:null}<Text numberOfLines={1} style={[styles.resultCorrect,type.micro]}>{m('mobile.common.correct')}: {session.mode==='ru'?source?.item?.word:source?.item?.trans}</Text></View><FavoriteButton active={favorites.has(wordId)} onPress={()=>setFavorites(toggleFavorite(favorites,wordId).ids)}/></View>;})}</ScrollView><View style={styles.footer}><View style={styles.footerButton}><Button action text onPress={onBack}>{m('mobile.stage.to_station')}</Button></View>{!result.passed?<View style={styles.footerButton}><Button action primary onPress={retry}>{m('mobile.common.retry')}</Button></View>:null}</View></View></Screen>;
  }
  const prompt=session.mode==='ru'?question.item.trans:question.item.word;
  const submit=()=>{if(!selectedId)return;applyStationTestAnswer(session,selectedId);saveNativeSessionSnapshot('station-test',stationTestActiveSnapshot(session)).catch(()=>{});setSelectedId('');setSession(session);redraw((value)=>value+1);};
  return <Screen><Header title={m('mobile.test.title')} subtitle={station?.name||''} onBack={back} sessionStatus={{counter:`${session.index+1}/${session.questions.length}`,mode:mode==='ru'?m('mobile.common.ru_alan').toUpperCase():m('mobile.common.alan_ru').toUpperCase()}}/><View style={styles.testView}><ScrollView contentContainerStyle={styles.testScroll} showsVerticalScrollIndicator={false}><View style={styles.promptBlock}><Text style={[styles.prompt,type.display]}>{prompt}</Text></View><View style={styles.options}>{question.options.map((option)=>{const selected=selectedId===String(option.id);return <Pressable accessibilityRole="button" accessibilityState={{selected}} key={`${question.item.id}-${option.id}`} onPress={()=>setSelectedId(String(option.id))} style={({pressed})=>[styles.option,selected&&styles.optionSelected,pressed&&styles.optionPressed]}><Text style={[styles.optionText,type.emphasis,selected&&styles.optionTextSelected]}>{option.text}</Text></Pressable>;})}</View></ScrollView><View style={styles.answerBar}><View style={styles.answerButton}><Button action primary disabled={!selectedId} onPress={submit}>{m('mobile.common.answer')}</Button></View></View></View></Screen>;
}

const styles=StyleSheet.create({center:{flex:1,justifyContent:'center',paddingHorizontal:20},testView:{flex:1,paddingTop:theme.control.header+theme.chrome.contentRestGap,paddingHorizontal:14,paddingBottom:theme.chrome.actionEdgeGap},testScroll:{flexGrow:1,paddingTop:4,paddingBottom:70,gap:12},promptBlock:{flexGrow:1,minHeight:150,maxWidth:520,width:'100%',alignSelf:'center',alignItems:'center',justifyContent:'center',paddingHorizontal:22},prompt:{color:C.text1,textAlign:'center'},options:{width:'100%',maxWidth:520,alignSelf:'center',gap:8},option:{minHeight:theme.control.normal,borderWidth:1,borderColor:C.line,borderRadius:2,backgroundColor:'rgba(246,242,233,.46)',alignItems:'center',justifyContent:'center',paddingHorizontal:12,paddingVertical:9},optionSelected:{borderColor:C.accentStrong,backgroundColor:C.accentSoft},optionPressed:{transform:[{translateY:1}],opacity:.8},optionText:{color:C.text1,textAlign:'center'},optionTextSelected:{color:C.accentStrong},answerBar:{position:'absolute',zIndex:20,left:14,right:14,bottom:theme.chrome.actionEdgeGap,alignItems:'flex-end'},answerButton:{width:180,maxWidth:'52%'},resultView:{flex:1},resultSummary:{position:'absolute',zIndex:30,top:theme.control.header+4,left:14,right:14,height:116,minHeight:116,padding:8,borderBottomWidth:1,borderBottomColor:C.lineSoft,alignItems:'center',justifyContent:'center'},resultMark:{fontFamily:theme.font.terminal,fontSize:18,fontWeight:'900',color:C.accentStrong,textAlign:'center'},resultScore:{fontFamily:theme.font.terminal,textAlign:'center',marginTop:3},scorePassed:{color:C.successStrong},scoreFailed:{color:C.dangerStrong},resultStatus:{color:C.text2,textAlign:'center',marginTop:6},resultList:{paddingTop:theme.control.header+136,paddingHorizontal:14,paddingBottom:70},resultRow:{minHeight:62,flexDirection:'row',alignItems:'center',gap:10,borderBottomWidth:1,borderBottomColor:C.lineSoft,paddingVertical:7},resultDot:{width:24,height:24,borderRadius:12,borderWidth:1,alignItems:'center',justifyContent:'center'},resultDotCorrect:{borderColor:C.success,backgroundColor:C.successSoft},resultDotWrong:{borderColor:C.danger,backgroundColor:C.dangerSoft},resultDotGlyph:{fontSize:13,fontWeight:'900',color:C.text1},resultCopy:{flex:1,minWidth:0},resultPrimary:{color:C.text1},resultWrong:{marginTop:3,color:C.dangerStrong},resultCorrect:{marginTop:3,color:C.successStrong},footer:{position:'absolute',zIndex:30,left:14,right:14,bottom:theme.chrome.actionEdgeGap,flexDirection:'row',justifyContent:'flex-end',gap:8},footerButton:{width:176,maxWidth:'48%'}});