import AsyncStorage from '@react-native-async-storage/async-storage';
import * as WebBrowser from 'expo-web-browser';
import { AppState, Linking } from 'react-native';
import { setNativeStorageScope } from './storage-scope.js';

const SUPABASE_URL='https://pybrzgedqjmosbmilcea.supabase.co';
const SUPABASE_KEY='sb_publishable_11TY-fBEAogA9JKnAku3vg_hjRxTa_a';
export const NATIVE_AUTH_REDIRECT_URL='alantil://auth/callback';
const SESSION_KEY='alantil:16.1:auth-session';
const listeners=new Set();
let currentSession=null,initialized=false,syncStartedForUser='',lastAuthError=null,bootstrapPromise=null,refreshPromise=null,callbackPromise=null,oauthFlowPromise=null,lastHandledCallbackUrl='';
WebBrowser.maybeCompleteAuthSession();
function emit(){listeners.forEach((listener)=>{try{listener(currentSession,lastAuthError);}catch{}});}
function setAuthError(error){lastAuthError=error||null;emit();return lastAuthError;}
async function triggerAccountSync(){const userId=String(currentSession?.user?.id||'');if(!userId||syncStartedForUser===userId)return;syncStartedForUser=userId;try{const {synchronizeNativeAccount}=await import('./cloud-sync.js');await synchronizeNativeAccount();}catch{syncStartedForUser='';}}
function parseCallback(url){const value=String(url||'');if(!value.startsWith(NATIVE_AUTH_REDIRECT_URL))return null;const hash=value.includes('#')?value.slice(value.indexOf('#')+1):'',query=value.includes('?')?value.slice(value.indexOf('?')+1,value.includes('#')?value.indexOf('#'):undefined):'',params=new URLSearchParams(hash||query);const oauthError=params.get('error_description')||params.get('error')||'';if(oauthError){const error=new Error(oauthError);error.code='OAUTH_CALLBACK_ERROR';throw error;}const accessToken=params.get('access_token')||'',refreshToken=params.get('refresh_token')||'',expiresIn=Number(params.get('expires_in')||3600);if(!accessToken)return null;return {access_token:accessToken,refresh_token:refreshToken,expires_at:Date.now()+Math.max(60,expiresIn)*1000,token_type:params.get('token_type')||'bearer',user:null};}
async function persist(session){currentSession=session||null;setNativeStorageScope(currentSession?.user?.id||'');lastAuthError=null;if(currentSession)await AsyncStorage.setItem(SESSION_KEY,JSON.stringify(currentSession));else{await AsyncStorage.removeItem(SESSION_KEY);syncStartedForUser='';lastHandledCallbackUrl='';}emit();void triggerAccountSync();return currentSession;}
async function fetchUser(accessToken){if(!accessToken)return null;const response=await fetch(`${SUPABASE_URL}/auth/v1/user`,{headers:{apikey:SUPABASE_KEY,Authorization:`Bearer ${accessToken}`}});if(!response.ok){const error=new Error(`Auth user request failed (${response.status})`);error.status=response.status;throw error;}return response.json();}
async function refreshSession(session){if(!session?.refresh_token)return null;const response=await fetch(`${SUPABASE_URL}/auth/v1/token?grant_type=refresh_token`,{method:'POST',headers:{apikey:SUPABASE_KEY,'Content-Type':'application/json'},body:JSON.stringify({refresh_token:session.refresh_token})});if(!response.ok){const error=new Error(`Session refresh failed (${response.status})`);error.status=response.status;throw error;}const data=await response.json();return {access_token:data.access_token,refresh_token:data.refresh_token||session.refresh_token,expires_at:Date.now()+Math.max(60,Number(data.expires_in||3600))*1000,token_type:data.token_type||'bearer',user:data.user||session.user||null};}
export async function refreshNativeAuthSession({clearOnFailure=true}={}){if(refreshPromise)return refreshPromise;if(!currentSession?.refresh_token)return currentSession;refreshPromise=(async()=>{try{const refreshed=await refreshSession(currentSession);if(!refreshed)throw new Error('Session refresh returned no session');return await persist(refreshed);}catch(error){if(clearOnFailure)await persist(null);setAuthError(error);throw error;}})().finally(()=>{refreshPromise=null;});return refreshPromise;}
async function ensureFreshSession(){if(currentSession?.expires_at&&currentSession.expires_at<=Date.now()+60000)await refreshNativeAuthSession();return currentSession;}
export async function handleNativeAuthUrl(url){const value=String(url||'');if(!value.startsWith(NATIVE_AUTH_REDIRECT_URL))return currentSession;if(value===lastHandledCallbackUrl&&currentSession?.user)return currentSession;if(callbackPromise)return callbackPromise;callbackPromise=(async()=>{let parsed;try{parsed=parseCallback(value);}catch(error){setAuthError(error);throw error;}if(!parsed)return currentSession;if(currentSession?.access_token===parsed.access_token&&currentSession?.user){lastHandledCallbackUrl=value;return currentSession;}try{parsed.user=await fetchUser(parsed.access_token);if(!parsed.user)throw new Error('Authenticated user was not returned');const session=await persist(parsed);lastHandledCallbackUrl=value;return session;}catch(error){setAuthError(error);throw error;}})().finally(()=>{callbackPromise=null;});return callbackPromise;}
async function bootstrapImpl(){if(!initialized){initialized=true;Linking.addEventListener('url',({url})=>{handleNativeAuthUrl(url).catch(()=>{});});AppState.addEventListener('change',(state)=>{if(state==='active')ensureFreshSession().then(()=>triggerAccountSync()).catch(()=>{});});}
  try{const initialUrl=await Linking.getInitialURL();if(initialUrl?.startsWith(NATIVE_AUTH_REDIRECT_URL))await handleNativeAuthUrl(initialUrl);}catch(error){setAuthError(error);}
  if(!currentSession){try{const raw=await AsyncStorage.getItem(SESSION_KEY);currentSession=raw?JSON.parse(raw):null;setNativeStorageScope(currentSession?.user?.id||'');}catch(error){currentSession=null;setNativeStorageScope('');setAuthError(error);}}
  if(currentSession?.expires_at&&currentSession.expires_at<=Date.now()+60000){try{await refreshNativeAuthSession();}catch{}}
  if(currentSession?.access_token&&!currentSession.user){try{currentSession.user=await fetchUser(currentSession.access_token);await persist(currentSession);}catch(error){await persist(null);setAuthError(error);}}
  setNativeStorageScope(currentSession?.user?.id||'');void triggerAccountSync();emit();return currentSession;
}
export async function bootstrapNativeAuth(){if(!bootstrapPromise)bootstrapPromise=bootstrapImpl().finally(()=>{bootstrapPromise=null;});return bootstrapPromise;}
export function subscribeNativeAuth(listener){listeners.add(listener);return()=>listeners.delete(listener);}
export function getNativeAuthSession(){return currentSession;}
export function getNativeAuthError(){return lastAuthError;}
export function getNativeAuthProvider(session=currentSession){const user=session?.user;if(!user)return '';return String(user?.app_metadata?.provider||user?.identities?.[0]?.provider||user?.user_metadata?.provider||'').trim().toLowerCase();}
export async function signInWithGoogleNative(){if(oauthFlowPromise)return oauthFlowPromise;lastAuthError=null;emit();const authorize=new URL(`${SUPABASE_URL}/auth/v1/authorize`);authorize.searchParams.set('provider','google');authorize.searchParams.set('redirect_to',NATIVE_AUTH_REDIRECT_URL);authorize.searchParams.set('prompt','select_account');oauthFlowPromise=(async()=>{try{const result=await WebBrowser.openAuthSessionAsync(authorize.toString(),NATIVE_AUTH_REDIRECT_URL);if(result?.type==='success'&&result.url)return await handleNativeAuthUrl(result.url);if(result?.type==='cancel'||result?.type==='dismiss')return currentSession;return currentSession;}catch(error){setAuthError(error);throw error;}})().finally(()=>{oauthFlowPromise=null;});return oauthFlowPromise;}
export async function signOutNative(){const token=currentSession?.access_token;if(token){try{await fetch(`${SUPABASE_URL}/auth/v1/logout`,{method:'POST',headers:{apikey:SUPABASE_KEY,Authorization:`Bearer ${token}`}});}catch{}}return persist(null);}
async function authorizedRequest(path,options,session){const headers={apikey:SUPABASE_KEY,'Content-Type':'application/json',...(session?.access_token?{Authorization:`Bearer ${session.access_token}`} :{}),...(options.headers||{})};return fetch(`${SUPABASE_URL}${path}`,{...options,headers});}
export async function nativeAuthFetch(path,options={}){await bootstrapNativeAuth();await ensureFreshSession();let response=await authorizedRequest(path,options,currentSession);if(response.status===401&&currentSession?.refresh_token){await refreshNativeAuthSession();response=await authorizedRequest(path,options,currentSession);}return response;}
bootstrapNativeAuth().catch(()=>{});
