import {isTerminalRefreshError} from '../../packages/alantil-core/auth-failure.js';
import AsyncStorage from '@react-native-async-storage/async-storage';
import * as WebBrowser from 'expo-web-browser';
import { AppState, Linking } from 'react-native';
import { setNativeStorageScope } from './storage-scope.js';
import { NATIVE_SUPABASE_AUTH_STORAGE_KEY, NATIVE_SUPABASE_PUBLISHABLE_KEY, NATIVE_SUPABASE_URL, nativeSupabase } from './supabase.native.js';

export const NATIVE_AUTH_REDIRECT_URL='alantil://auth/callback';
const SESSION_KEY='alantil:16.1:auth-session';
const OAUTH_PENDING_KEY='alantil:16.6.6:oauth-pending';
const AUTH_FLOW_KEY='alantil:16.8:auth-flow';
const AUTH_MIGRATION_KEY='alantil:16.8:auth-migration-v1';
const OAUTH_PENDING_MAX_AGE_MS=15*60*1000;
const KNOWN_AUTH_FLOWS=new Set(['legacy_google','recovery','signup']);
const PASSWORD_SETUP_FLOWS=new Set(['legacy_google','recovery']);
const listeners=new Set();
let currentSession=null,currentAuthFlow='',initialized=false,syncStartedForUser='',lastAuthError=null,bootstrapPromise=null,refreshPromise=null,callbackPromise=null,oauthFlowPromise=null,lastHandledCallbackUrl='',authMigrationRequired=false,authSubscription=null,appStateSubscription=null,linkSubscription=null;

function normalizeAuthFlow(value){const flow=String(value||'').trim().toLowerCase();return KNOWN_AUTH_FLOWS.has(flow)?flow:'';}
function postAuthFlow(value){const flow=normalizeAuthFlow(value);return PASSWORD_SETUP_FLOWS.has(flow)?flow:'';}
function emit(){listeners.forEach((listener)=>{try{listener(currentSession,lastAuthError,currentAuthFlow);}catch{}});}
function setAuthError(error){lastAuthError=error||null;emit();return lastAuthError;}
function normalizeSession(session){if(!session)return null;const rawExpiresAt=Number(session.expires_at||0),expiresAt=rawExpiresAt&&rawExpiresAt<1e12?rawExpiresAt*1000:rawExpiresAt;return {...session,expires_at:expiresAt||0};}
async function setAuthFlow(flow,{notify=true}={}){currentAuthFlow=postAuthFlow(flow);try{if(currentAuthFlow)await AsyncStorage.setItem(AUTH_FLOW_KEY,currentAuthFlow);else await AsyncStorage.removeItem(AUTH_FLOW_KEY);}catch{}if(notify)emit();return currentAuthFlow;}
async function restoreAuthFlow(){let raw='';try{raw=await AsyncStorage.getItem(AUTH_FLOW_KEY);}catch{}currentAuthFlow=postAuthFlow(raw);return currentAuthFlow;}
async function applyOneTimeAuthMigration({preserveSession=false}={}){
  let migrated=false;
  try{migrated=(await AsyncStorage.getItem(AUTH_MIGRATION_KEY))==='1';}catch{}
  if(migrated)return false;
  let hasStoredSession=false;
  try{
    const [sdkSession,legacySession]=await Promise.all([AsyncStorage.getItem(NATIVE_SUPABASE_AUTH_STORAGE_KEY),AsyncStorage.getItem(SESSION_KEY)]);
    hasStoredSession=Boolean(sdkSession||legacySession);
    await AsyncStorage.setItem(AUTH_MIGRATION_KEY,'1');
  }catch{return false;}
  if(preserveSession||!hasStoredSession)return false;
  try{await AsyncStorage.multiRemove([NATIVE_SUPABASE_AUTH_STORAGE_KEY,SESSION_KEY,AUTH_FLOW_KEY,OAUTH_PENDING_KEY]);}catch{}
  try{await nativeSupabase.auth.signOut({scope:'local'});}catch{}
  currentSession=null;currentAuthFlow='';syncStartedForUser='';lastHandledCallbackUrl='';authMigrationRequired=true;setNativeStorageScope('');
  return true;
}
export function consumeNativeAuthMigrationRequired(){const required=authMigrationRequired;authMigrationRequired=false;return required;}
export function getNativeAuthFlow(){return currentAuthFlow;}
export async function clearNativeAuthFlow(){return setAuthFlow('');}
function nativeRedirectUrl(flow=''){const normalized=normalizeAuthFlow(flow);return normalized?NATIVE_AUTH_REDIRECT_URL+'?auth_flow='+encodeURIComponent(normalized):NATIVE_AUTH_REDIRECT_URL;}
async function triggerAccountSync(){const userId=String(currentSession?.user?.id||'');if(!userId||syncStartedForUser===userId)return;syncStartedForUser=userId;try{const {synchronizeNativeAccount}=await import('./cloud-sync.js');const ok=await synchronizeNativeAccount();if(!ok&&syncStartedForUser===userId)syncStartedForUser='';}catch{syncStartedForUser='';}}
function callbackParams(url){const value=String(url||'');if(!value.startsWith(NATIVE_AUTH_REDIRECT_URL))return null;const parsed=new URL(value),query=new URLSearchParams(parsed.search||''),hash=new URLSearchParams(String(parsed.hash||'').replace(/^#/,'')),read=(key)=>String(hash.get(key)||query.get(key)||'').trim(),authError=read('error_description')||read('error')||read('error_code');if(authError){const error=new Error(authError);error.code='AUTH_CALLBACK_ERROR';throw error;}return {code:read('code'),flowId:read('sb_flow_id')||read('flow_id'),authFlow:normalizeAuthFlow(read('auth_flow')),type:read('type'),accessToken:read('access_token'),refreshToken:read('refresh_token')};}
function oauthFlowId(url){try{const parsed=new URL(String(url||''));return String(parsed.searchParams.get('sb_flow_id')||parsed.searchParams.get('flow_id')||'').trim();}catch{return '';}}
function assertMobileOAuthUrl(url,expectedRedirect){let parsed;try{parsed=new URL(String(url||''));}catch{throw new Error('Supabase returned an invalid Google OAuth URL');}const redirect=String(parsed.searchParams.get('redirect_to')||parsed.searchParams.get('redirectTo')||'').trim();if(redirect!==expectedRedirect){const error=new Error('Google OAuth did not preserve the native callback URL');error.code='OAUTH_REDIRECT_MISMATCH';throw error;}return parsed.toString();}
async function clearPendingOAuth(){try{await AsyncStorage.removeItem(OAUTH_PENDING_KEY);}catch{}}
async function writePendingOAuth(authUrl,flowId='',authFlow=''){const redirectTo=nativeRedirectUrl(authFlow),pending={provider:'google',redirectTo,authFlow:postAuthFlow(authFlow),flowId:String(flowId||oauthFlowId(authUrl)||'').trim(),startedAt:Date.now()};await AsyncStorage.setItem(OAUTH_PENDING_KEY,JSON.stringify(pending));return pending;}
async function readPendingOAuth(){let raw='';try{raw=await AsyncStorage.getItem(OAUTH_PENDING_KEY);}catch{return null;}if(!raw)return null;let pending=null;try{pending=JSON.parse(raw);}catch{await clearPendingOAuth();return null;}if(!String(pending?.redirectTo||'').startsWith(NATIVE_AUTH_REDIRECT_URL)||pending?.provider!=='google'||!Number(pending?.startedAt)||Date.now()-Number(pending.startedAt)>OAUTH_PENDING_MAX_AGE_MS){await clearPendingOAuth();return null;}return pending;}
async function validatePendingCallback(params){const pending=await readPendingOAuth();if(!pending){const {data,error}=await nativeSupabase.auth.getSession();if(!error&&data?.session?.user)return {pending:null,existingSession:data.session};const nextError=new Error('OAuth callback does not belong to an active mobile sign-in flow');nextError.code='OAUTH_FLOW_NOT_PENDING';throw nextError;}if(pending.flowId&&params?.flowId&&pending.flowId!==params.flowId){const error=new Error('OAuth callback belongs to a different sign-in flow');error.code='OAUTH_FLOW_MISMATCH';throw error;}return {pending,existingSession:null};}
async function persist(session){currentSession=normalizeSession(session);setNativeStorageScope(currentSession?.user?.id||'');lastAuthError=null;if(currentSession)await AsyncStorage.setItem(SESSION_KEY,JSON.stringify(currentSession));else{await AsyncStorage.removeItem(SESSION_KEY);syncStartedForUser='';lastHandledCallbackUrl='';}emit();void triggerAccountSync();return currentSession;}
async function dismissAuthBrowser(){try{await WebBrowser.dismissBrowser();}catch{}try{WebBrowser.dismissAuthSession();}catch{}}
async function sessionFromCallback(params){if(params?.code){const options=params.flowId?{flowId:params.flowId}:undefined,{data,error}=await nativeSupabase.auth.exchangeCodeForSession(params.code,options);if(error)throw error;if(!data?.session?.user)throw new Error('Authenticated session was not returned after PKCE exchange');return data.session;}if(params?.accessToken||params?.refreshToken){if(!params.accessToken||!params.refreshToken)throw new Error('Auth callback did not include both access and refresh tokens');const {data,error}=await nativeSupabase.auth.setSession({access_token:params.accessToken,refresh_token:params.refreshToken});if(error)throw error;if(!data?.session?.user)throw new Error('Authenticated session was not returned after token callback');return data.session;}const {data,error}=await nativeSupabase.auth.getSession();if(error)throw error;if(data?.session?.user)return data.session;throw new Error('Auth callback did not include a PKCE code or session tokens');}
async function restoreLegacySession(){let raw='';try{raw=await AsyncStorage.getItem(SESSION_KEY);}catch{return null;}if(!raw)return null;let legacy=null;try{legacy=JSON.parse(raw);}catch{await AsyncStorage.removeItem(SESSION_KEY);return null;}if(!legacy?.access_token||!legacy?.refresh_token){await AsyncStorage.removeItem(SESSION_KEY);return null;}try{const {data,error}=await nativeSupabase.auth.setSession({access_token:legacy.access_token,refresh_token:legacy.refresh_token});if(error)throw error;if(!data?.session?.user)throw new Error('Legacy session could not be restored');return data.session;}catch{await AsyncStorage.removeItem(SESSION_KEY);return null;}}
function bindNativeAuthEvents(){if(!authSubscription){const {data}=nativeSupabase.auth.onAuthStateChange((event,session)=>{void(async()=>{if(event==='PASSWORD_RECOVERY'){await setAuthFlow('recovery',{notify:false});if(session?.user)await persist(session);else emit();return;}if(event==='SIGNED_OUT'){await setAuthFlow('',{notify:false});await persist(null);return;}if(session?.user)await persist(session);})().catch((error)=>setAuthError(error));});authSubscription=data?.subscription||null;}if(!linkSubscription)linkSubscription=Linking.addEventListener('url',({url})=>{handleNativeAuthUrl(url).catch(()=>{});});if(!appStateSubscription){if(AppState.currentState==='active')nativeSupabase.auth.startAutoRefresh();appStateSubscription=AppState.addEventListener('change',(state)=>{if(state==='active'){nativeSupabase.auth.startAutoRefresh();ensureFreshSession().then(()=>triggerAccountSync()).catch(()=>{});}else nativeSupabase.auth.stopAutoRefresh();});}}

export async function refreshNativeAuthSession({clearOnFailure=true}={}){if(refreshPromise)return refreshPromise;if(!currentSession?.refresh_token)return currentSession;refreshPromise=(async()=>{try{const {data,error}=await nativeSupabase.auth.refreshSession({refresh_token:currentSession.refresh_token});if(error)throw error;if(!data?.session?.user)throw new Error('Session refresh returned no session');return await persist(data.session);}catch(error){if(clearOnFailure&&isTerminalRefreshError(error)){try{await nativeSupabase.auth.signOut({scope:'local'});}catch{}await setAuthFlow('',{notify:false});await persist(null);}setAuthError(error);throw error;}})().finally(()=>{refreshPromise=null;});return refreshPromise;}
async function ensureFreshSession(){if(currentSession?.expires_at&&currentSession.expires_at<=Date.now()+60000)await refreshNativeAuthSession();return currentSession;}
export async function handleNativeAuthUrl(url){const value=String(url||'');if(!value.startsWith(NATIVE_AUTH_REDIRECT_URL))return currentSession;if(value===lastHandledCallbackUrl&&currentSession?.user)return currentSession;if(callbackPromise)return callbackPromise;callbackPromise=(async()=>{try{const params=callbackParams(value),callbackFlow=normalizeAuthFlow(params?.authFlow),emailFlow=callbackFlow==='recovery'||callbackFlow==='signup';let validation={pending:null,existingSession:null};if(!emailFlow)validation=await validatePendingCallback(params);const resolvedFlow=postAuthFlow(callbackFlow||validation.pending?.authFlow);await setAuthFlow(resolvedFlow,{notify:false});const flowId=params.flowId||validation.pending?.flowId||'',session=validation.existingSession||await sessionFromCallback({...params,flowId}),saved=await persist(session);lastHandledCallbackUrl=value;return saved;}catch(error){setAuthError(error);throw error;}finally{await clearPendingOAuth();await dismissAuthBrowser();}})().finally(()=>{callbackPromise=null;});return callbackPromise;}
async function bootstrapImpl(){let initialUrl='';try{initialUrl=await Linking.getInitialURL()||'';}catch(error){setAuthError(error);}
  if(!initialized){initialized=true;await applyOneTimeAuthMigration({preserveSession:initialUrl.startsWith(NATIVE_AUTH_REDIRECT_URL)});await restoreAuthFlow();bindNativeAuthEvents();}
  try{if(initialUrl.startsWith(NATIVE_AUTH_REDIRECT_URL))await handleNativeAuthUrl(initialUrl);}catch(error){setAuthError(error);}
  if(!currentSession){try{const {data,error}=await nativeSupabase.auth.getSession();if(error)throw error;if(data?.session?.user)await persist(data.session);}catch(error){setAuthError(error);}}
  if(!currentSession){const restored=await restoreLegacySession();if(restored)await persist(restored);}
  if(!currentSession&&currentAuthFlow)await setAuthFlow('',{notify:false});
  if(currentSession?.expires_at&&currentSession.expires_at<=Date.now()+60000){try{await refreshNativeAuthSession();}catch{}}
  if(currentSession?.access_token&&!currentSession.user){try{const {data,error}=await nativeSupabase.auth.getUser(currentSession.access_token);if(error)throw error;if(!data?.user)throw new Error('Authenticated user was not returned');currentSession={...currentSession,user:data.user};await persist(currentSession);}catch(error){await setAuthFlow('',{notify:false});await persist(null);setAuthError(error);}}
  setNativeStorageScope(currentSession?.user?.id||'');void triggerAccountSync();emit();return currentSession;
}
export async function bootstrapNativeAuth(){if(!bootstrapPromise)bootstrapPromise=bootstrapImpl().finally(()=>{bootstrapPromise=null;});return bootstrapPromise;}
export function subscribeNativeAuth(listener){listeners.add(listener);return()=>listeners.delete(listener);}
export function getNativeAuthSession(){return currentSession;}
export function getNativeAuthError(){return lastAuthError;}
export function getNativeAuthProvider(session=currentSession){const user=session?.user;if(!user)return '';const providers=Array.isArray(user?.app_metadata?.providers)?user.app_metadata.providers.map((value)=>String(value||'').toLowerCase()):[];if(providers.includes('email')||user?.app_metadata?.provider==='email')return 'email';return String(user?.app_metadata?.provider||user?.identities?.[0]?.provider||user?.user_metadata?.provider||'').trim().toLowerCase();}

async function signInWithGoogleFlow(authFlow=''){if(oauthFlowPromise)return oauthFlowPromise;lastAuthError=null;emit();oauthFlowPromise=(async()=>{let pendingWritten=false;const flow=postAuthFlow(authFlow);try{await clearPendingOAuth();await setAuthFlow(flow,{notify:false});const redirectTo=nativeRedirectUrl(flow);const {data,error}=await nativeSupabase.auth.signInWithOAuth({provider:'google',options:{redirectTo,skipBrowserRedirect:true,queryParams:{prompt:'select_account'}}});if(error)throw error;if(!data?.url)throw new Error('Supabase did not return a Google OAuth URL');const authUrl=assertMobileOAuthUrl(data.url,redirectTo);await writePendingOAuth(authUrl,data.flowId,flow);pendingWritten=true;const result=await WebBrowser.openAuthSessionAsync(authUrl,NATIVE_AUTH_REDIRECT_URL,{showInRecents:true});if(result?.type==='success'&&result.url)return await handleNativeAuthUrl(result.url);if(result?.type==='cancel'||result?.type==='dismiss'){await clearPendingOAuth();if(flow)await setAuthFlow('');return currentSession;}await clearPendingOAuth();if(flow)await setAuthFlow('');return currentSession;}catch(error){if(pendingWritten)await clearPendingOAuth();if(flow)await setAuthFlow('',{notify:false});setAuthError(error);throw error;}})().finally(()=>{oauthFlowPromise=null;});return oauthFlowPromise;}
export async function signInWithGoogleNative(){return signInWithGoogleFlow('');}
export async function signInWithLegacyGoogleNative(){return signInWithGoogleFlow('legacy_google');}
export async function signInWithEmailNative(email,password){await setAuthFlow('',{notify:false});lastAuthError=null;const {data,error}=await nativeSupabase.auth.signInWithPassword({email:String(email||'').trim().toLowerCase(),password:String(password||'')});if(error){setAuthError(error);throw error;}if(!data?.session?.user)throw new Error('Authenticated session was not returned');return persist(data.session);}
export async function signUpWithEmailNative(email,password){await setAuthFlow('',{notify:false});lastAuthError=null;const {data,error}=await nativeSupabase.auth.signUp({email:String(email||'').trim().toLowerCase(),password:String(password||''),options:{emailRedirectTo:nativeRedirectUrl('signup')}});if(error){setAuthError(error);throw error;}if(data?.session?.user)await persist(data.session);return data;}
export async function sendPasswordResetNative(email){lastAuthError=null;const {data,error}=await nativeSupabase.auth.resetPasswordForEmail(String(email||'').trim().toLowerCase(),{redirectTo:nativeRedirectUrl('recovery')});if(error){setAuthError(error);throw error;}return data;}
export async function updateNativePassword(password){lastAuthError=null;const flow=currentAuthFlow,originalUserId=String(currentSession?.user?.id||'');const {data,error}=await nativeSupabase.auth.updateUser({password:String(password||'')});if(error){setAuthError(error);throw error;}const {data:sessionData,error:sessionError}=await nativeSupabase.auth.getSession();if(sessionError){setAuthError(sessionError);throw sessionError;}if(!sessionData?.session?.user)throw new Error('Authenticated session was not returned');const updatedUserId=String(sessionData.session.user.id||'');if(flow==='legacy_google'&&originalUserId&&updatedUserId!==originalUserId){const identityError=new Error('Account identity changed during legacy Google migration');setAuthError(identityError);throw identityError;}await setAuthFlow('',{notify:false});await persist(sessionData.session);return data;}
export async function signOutNative(){let error=null;await clearPendingOAuth();lastHandledCallbackUrl='';try{const result=await nativeSupabase.auth.signOut({scope:'local'});error=result?.error||null;}catch(nextError){error=nextError;}await setAuthFlow('',{notify:false});await persist(null);if(error){setAuthError(error);throw error;}return null;}
async function authorizedRequest(path,options,session){const headers={apikey:NATIVE_SUPABASE_PUBLISHABLE_KEY,'Content-Type':'application/json',...(session?.access_token?{Authorization:'Bearer '+session.access_token}:{}),...(options.headers||{})};return fetch(NATIVE_SUPABASE_URL+path,{...options,headers});}
export async function nativeAuthFetch(path,options={},expectedUserId=null){const guard=()=>{if(expectedUserId!==null&&String(currentSession?.user?.id||'')!==String(expectedUserId))throw new Error('Account changed during request');};guard();await bootstrapNativeAuth();guard();await ensureFreshSession();guard();let response=await authorizedRequest(path,options,currentSession);if(response.status===401&&currentSession?.refresh_token){await refreshNativeAuthSession();guard();response=await authorizedRequest(path,options,currentSession);}return response;}
