import AsyncStorage from '@react-native-async-storage/async-storage';
import { normalizeFavoriteSyncRows, resolveFavoriteSyncRows } from '../../packages/alantil-core/favorites.js';
import { hiddenSelectionIds, hiddenSelectionKey, LEGACY_HIDDEN_CONTEXT, setHiddenSelectionIds } from '../../packages/alantil-core/hidden-selection.js';
import { getNativeAuthSession, nativeAuthFetch } from './auth.js';
import { migrateLegacyNativeValueToGuest, nativeScopedStorageKey } from './storage-scope.js';

const LEGACY_KEY='alantil:16.1:hidden-words';
const CONTEXT_KEY='alantil:16.6.1:hidden-words-by-context';
const MIGRATION_KEY='alantil:16.6.1:hidden-words-context-migrated';
const SYNC_KEY='alantil:16.4.1:hidden-words-sync';
async function key(base){await migrateLegacyNativeValueToGuest(base);return nativeScopedStorageKey(base);}
async function readJson(base,fallback){try{const raw=await AsyncStorage.getItem(await key(base));return raw?JSON.parse(raw):fallback;}catch{return fallback;}}
async function writeJson(base,value){await AsyncStorage.setItem(await key(base),JSON.stringify(value));}
function asSet(values){return new Set((Array.isArray(values)?values:Array.from(values||[])).map(String).filter(Boolean));}
async function migrateLegacyOnce(){const marker=await readJson(MIGRATION_KEY,false);if(marker)return;const legacy=asSet(await readJson(LEGACY_KEY,[])),current=await readJson(CONTEXT_KEY,{});let next=current&&typeof current==='object'&&!Array.isArray(current)?current:{};if(legacy.size&&!hiddenSelectionIds(next,LEGACY_HIDDEN_CONTEXT).size)next=setHiddenSelectionIds(next,LEGACY_HIDDEN_CONTEXT,legacy);await writeJson(CONTEXT_KEY,next);await writeJson(MIGRATION_KEY,true);}
async function readMap(){await migrateLegacyOnce();const value=await readJson(CONTEXT_KEY,{});return value&&typeof value==='object'&&!Array.isArray(value)?value:{};}
async function writeMap(value){await writeJson(CONTEXT_KEY,value&&typeof value==='object'?value:{});}
async function readContext(context=LEGACY_HIDDEN_CONTEXT){return hiddenSelectionIds(await readMap(),context);}
async function writeContext(context,nextIds){const map=await readMap(),next=setHiddenSelectionIds(map,context,nextIds);await writeMap(next);return hiddenSelectionIds(next,context);}
async function readLegacySyncRows(){const active=await readContext(LEGACY_HIDDEN_CONTEXT),stored=normalizeFavoriteSyncRows(await readJson(SYNC_KEY,[])),map=new Map(stored.map((row)=>[row.id,row]));for(const id of active)if(!map.has(id))map.set(id,{id,is_active:true,updated_at:null});return Array.from(map.values());}
async function applyLegacySyncRows(rows){const normalized=normalizeFavoriteSyncRows(rows),active=new Set(normalized.filter((row)=>row.is_active).map((row)=>row.id));await Promise.all([writeContext(LEGACY_HIDDEN_CONTEXT,active),writeJson(SYNC_KEY,normalized)]);return active;}
export async function loadNativeHiddenWords(context=LEGACY_HIDDEN_CONTEXT){return readContext(context);}
export async function saveNativeHiddenWords(contextOrIds,nextOrChanged=[],changedIds=[]){const legacyCall=contextOrIds instanceof Set||Array.isArray(contextOrIds),context=legacyCall?LEGACY_HIDDEN_CONTEXT:contextOrIds||LEGACY_HIDDEN_CONTEXT,nextIds=legacyCall?contextOrIds:nextOrChanged,explicitChanged=legacyCall?nextOrChanged:changedIds,before=await readContext(context),set=asSet(nextIds),changed=new Set((explicitChanged||[]).map(String));for(const id of new Set([...before,...set]))if(before.has(id)!==set.has(id))changed.add(id);await writeContext(context,set);if(hiddenSelectionKey(context)!==hiddenSelectionKey(LEGACY_HIDDEN_CONTEXT))return set;const now=new Date().toISOString(),rows=await readLegacySyncRows(),map=new Map(rows.map((row)=>[row.id,row]));for(const id of changed)map.set(id,{id,is_active:set.has(id),updated_at:now});await writeJson(SYNC_KEY,Array.from(map.values()));const session=getNativeAuthSession();if(session?.user?.id){for(const id of changed){try{await nativeAuthFetch('/rest/v1/user_hidden_words?on_conflict=user_id,word_id',{method:'POST',headers:{Prefer:'resolution=merge-duplicates,return=minimal'},body:JSON.stringify({user_id:session.user.id,word_id:String(id),is_hidden:set.has(String(id)),updated_at:now})});}catch{}}}return set;}
export async function mergeNativeCloudHiddenWords(){const session=getNativeAuthSession();if(!session?.user?.id)return readContext(LEGACY_HIDDEN_CONTEXT);const localRows=await readLegacySyncRows();try{const response=await nativeAuthFetch('/rest/v1/user_hidden_words?select=word_id,is_hidden,updated_at');if(response.ok){const rows=await response.json(),cloudRows=(Array.isArray(rows)?rows:[]).map((row)=>({id:String(row?.word_id||''),is_active:row?.is_hidden!==false,updated_at:row?.updated_at||null})).filter((row)=>row.id);return applyLegacySyncRows(resolveFavoriteSyncRows(localRows,cloudRows));}}catch{}return readContext(LEGACY_HIDDEN_CONTEXT);}
