import AsyncStorage from '@react-native-async-storage/async-storage';
import { normalizeFavoriteSyncRows } from '../../packages/alantil-core/favorites.js';
import { migrateStoredUserSettings, normalizeSyncTimestamp, normalizeUserSettings } from '../../packages/alantil-core/settings.js';
import { getNativeStorageScope, migrateLegacyNativeValueToGuest, nativeScopedStorageKey } from './storage-scope.js';

const KEYS=Object.freeze({settings:'alantil:16.1:settings',settingsSync:'alantil:16.4.1:settings-sync',favorites:'alantil:16.1:favorites',favoriteSync:'alantil:16.4.1:favorite-sync',songFavorites:'alantil:16.1:song-favorites',songFavoriteSync:'alantil:16.4.1:song-favorite-sync',legacyOnboarding:'alantil:16.1:onboarding-complete',authChoice:'alantil:16.6.3:auth-choice-complete'});
async function scopedKey(base,scope=getNativeStorageScope()){const key=nativeScopedStorageKey(base,scope);await migrateLegacyNativeValueToGuest(base);return key;}
async function readJson(base,fallback,scope=getNativeStorageScope()){try{const raw=await AsyncStorage.getItem(await scopedKey(base,scope));return raw?JSON.parse(raw):fallback;}catch{return fallback;}}
async function writeJson(base,value,scope=getNativeStorageScope()){await AsyncStorage.setItem(await scopedKey(base,scope),JSON.stringify(value));}
async function queuePreferences(scope){try{const {queueNativePreferences}=await import('./cloud-sync.js');if(getNativeStorageScope()===scope)await queueNativePreferences();}catch{}}
async function queueFavoriteDiff(kind,before,after,updatedAt,scope){try{const {queueNativeFavoriteChange}=await import('./cloud-sync.js');const ids=new Set([...before,...after]);for(const id of ids){const was=before.has(id),is=after.has(id);if(was!==is&&getNativeStorageScope()===scope)await queueNativeFavoriteChange(kind,id,is,updatedAt);}}catch{}}
function config(kind){return kind==='song'?{values:KEYS.songFavorites,sync:KEYS.songFavoriteSync}:{values:KEYS.favorites,sync:KEYS.favoriteSync};}
async function loadFavoriteSet(kind,scope=getNativeStorageScope()){const value=await readJson(config(kind).values,[],scope);return new Set(Array.isArray(value)?value.map(String):[]);}
async function writeFavoriteSet(kind,set,scope){await writeJson(config(kind).values,Array.from(set).map(String),scope);}
export async function loadNativeFavoriteSyncRows(kind='word',scope=getNativeStorageScope()){const set=await loadFavoriteSet(kind,scope),stored=normalizeFavoriteSyncRows(await readJson(config(kind).sync,[],scope)),map=new Map(stored.map((row)=>[row.id,row]));for(const id of set)if(!map.has(id))map.set(id,{id,is_active:true,updated_at:null});return Array.from(map.values());}
export async function applyNativeFavoriteSyncRows(kind='word',rows=[],scope=getNativeStorageScope()){const normalized=normalizeFavoriteSyncRows(rows),active=new Set(normalized.filter((row)=>row.is_active).map((row)=>row.id));await Promise.all([writeFavoriteSet(kind,active,scope),writeJson(config(kind).sync,normalized,scope)]);return active;}
async function saveFavoriteSet(kind,ids,scope){const before=await loadFavoriteSet(kind,scope),after=new Set(Array.from(ids instanceof Set?ids:new Set(ids||[])).map(String)),now=new Date().toISOString(),rows=await loadNativeFavoriteSyncRows(kind,scope),map=new Map(rows.map((row)=>[row.id,row]));let changed=false;for(const id of new Set([...before,...after])){const was=before.has(id),is=after.has(id);if(was!==is){map.set(id,{id,is_active:is,updated_at:now});changed=true;}}await Promise.all([writeFavoriteSet(kind,after,scope),writeJson(config(kind).sync,Array.from(map.values()),scope)]);if(changed)void queueFavoriteDiff(kind,before,after,now,scope);return after;}
export async function loadNativeSettings(scope=getNativeStorageScope()){let raw=null,hasStoredSettings=false;try{const key=await scopedKey(KEYS.settings,scope),stored=await AsyncStorage.getItem(key);hasStoredSettings=stored!==null;raw=stored?JSON.parse(stored):{};}catch{raw={};}const migrated=migrateStoredUserSettings(raw,hasStoredSettings),normalized=normalizeUserSettings(migrated||{});if(hasStoredSettings&&JSON.stringify(normalized)!==JSON.stringify(raw)){try{await writeJson(KEYS.settings,normalized,scope);}catch{}}return normalized;}
export async function loadNativeSettingsSyncTimestamp(scope=getNativeStorageScope()){const raw=await readJson(KEYS.settingsSync,null,scope);return normalizeSyncTimestamp(raw?.updated_at||raw);}
export async function saveNativeSettings(settings,{sync=true,updatedAt='',scope=getNativeStorageScope()}={}){const normalized=normalizeUserSettings(settings),timestamp=normalizeSyncTimestamp(updatedAt)||new Date().toISOString();await Promise.all([writeJson(KEYS.settings,normalized,scope),writeJson(KEYS.settingsSync,{updated_at:timestamp},scope)]);if(sync)void queuePreferences(scope);return normalized;}
export async function applyNativeSettingsFromSync(settings,updatedAt,scope=getNativeStorageScope()){return saveNativeSettings(settings,{sync:false,updatedAt,scope});}
export async function loadNativeFavorites(scope=getNativeStorageScope()){return loadFavoriteSet('word',scope);}
export async function saveNativeFavorites(ids,scope=getNativeStorageScope()){return saveFavoriteSet('word',ids,scope);}
export async function loadNativeSongFavorites(scope=getNativeStorageScope()){return loadFavoriteSet('song',scope);}
export async function saveNativeSongFavorites(ids,scope=getNativeStorageScope()){return saveFavoriteSet('song',ids,scope);}
export async function hasCompletedNativeOnboarding(){return (await AsyncStorage.getItem(await scopedKey(KEYS.legacyOnboarding)))==='1';}
export async function markNativeOnboardingComplete(){await AsyncStorage.setItem(await scopedKey(KEYS.legacyOnboarding),'1');}
export async function hasCompletedNativeAuthChoice(){const direct=(await AsyncStorage.getItem(await scopedKey(KEYS.authChoice)))==='1';if(direct)return true;return hasCompletedNativeOnboarding();}
export async function markNativeAuthChoiceComplete(){await AsyncStorage.setItem(await scopedKey(KEYS.authChoice),'1');}
